<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="GitHub Copilot" />

<meta name="date" content="2026-04-02" />

<title>Dummy Spatial Scaling Analysis: Contaminants and Isotopes</title>

<script src="contaminent_distance_decay_analysis_files/header-attrs-2.29/header-attrs.js"></script>
<script src="contaminent_distance_decay_analysis_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="contaminent_distance_decay_analysis_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="contaminent_distance_decay_analysis_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="contaminent_distance_decay_analysis_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="contaminent_distance_decay_analysis_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="contaminent_distance_decay_analysis_files/navigation-1.1/tabsets.js"></script>
<link href="contaminent_distance_decay_analysis_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="contaminent_distance_decay_analysis_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Dummy Spatial Scaling Analysis:
Contaminants and Isotopes</h1>
<h4 class="author">GitHub Copilot</h4>
<h4 class="date">2026-04-02</h4>

</div>


<div id="overview" class="section level2">
<h2>Overview</h2>
<p>This report creates a dummy tissue dataset for sampled individuals
across latitude and longitude, then evaluates distance-decay
relationships for:</p>
<ul>
<li>DDT</li>
<li>PCP</li>
<li>Isotope signature (delta13C and delta15N combined)</li>
<li>Overall multivariate similarity</li>
</ul>
<p>In the spirit of broad spatial-scaling analyses, we compare multiple
distance-decay functions (exponential, power-law, and log-linear),
evaluate isolated curves per variable, and assess generality with a
pooled model and null randomization.</p>
</div>
<div id="create-dummy-data" class="section level2">
<h2>1) Create Dummy Data</h2>
<pre class="r"><code># Three broad spatial clusters to create realistic distance structure.
n_sites &lt;- 60
cluster &lt;- sample(c(&quot;North&quot;, &quot;Central&quot;, &quot;South&quot;), n_sites, replace = TRUE, prob = c(0.3, 0.4, 0.3))

lat &lt;- ifelse(cluster == &quot;North&quot;, 45 + rnorm(n_sites, 0, 1.3),
              ifelse(cluster == &quot;Central&quot;, 37 + rnorm(n_sites, 0, 1.2),
                     30 + rnorm(n_sites, 0, 1.4)))

lon &lt;- ifelse(cluster == &quot;North&quot;, -122 + rnorm(n_sites, 0, 1.5),
              ifelse(cluster == &quot;Central&quot;, -118 + rnorm(n_sites, 0, 1.3),
                     -112 + rnorm(n_sites, 0, 1.6)))

# Add smooth spatial signals and noise to generate trait-like chemistry.
spatial_grad &lt;- scale(lat) - 0.6 * scale(lon)

DDT &lt;- pmax(0.01, 2.5 + 1.1 * as.numeric(spatial_grad) + rnorm(n_sites, 0, 0.45))
PCP &lt;- pmax(0.01, 1.8 + 0.9 * as.numeric(scale(lat + lon)) + rnorm(n_sites, 0, 0.40))
delta13C &lt;- -24 + 1.7 * as.numeric(scale(lat)) + rnorm(n_sites, 0, 0.7)
delta15N &lt;- 8 + 1.3 * as.numeric(scale(-lon)) + rnorm(n_sites, 0, 0.6)

dummy_data &lt;- data.frame(
  site_id = sprintf(&quot;S%03d&quot;, seq_len(n_sites)),
  cluster = cluster,
  latitude = lat,
  longitude = lon,
  DDT = DDT,
  PCP = PCP,
  delta13C = delta13C,
  delta15N = delta15N,
  stringsAsFactors = FALSE
)

write.csv(dummy_data, file.path(out_dir, &quot;dummy_tissue_data.csv&quot;), row.names = FALSE)
head(dummy_data)</code></pre>
<pre><code>##   site_id cluster latitude longitude       DDT       PCP  delta13C delta15N
## 1    S001   North 45.59209 -123.8018 4.7469774 1.7674484 -21.28073 9.268207
## 2    S002   North 45.91629 -118.9445 3.8279195 3.8750820 -22.26581 8.210108
## 3    S003 Central 37.78042 -117.7954 2.6523973 1.7698248 -24.88659 7.422422
## 4    S004   North 44.20840 -122.1262 3.8830082 2.2226239 -22.48324 8.009819
## 5    S005   South 29.34502 -110.4182 0.0100000 1.3988361 -24.72457 5.773977
## 6    S006   South 28.26645 -112.1175 0.5067989 0.3252838 -25.14597 7.010978</code></pre>
</div>
<div id="pairwise-distance-and-similarity" class="section level2">
<h2>2) Pairwise Distance and Similarity</h2>
<pre class="r"><code># Haversine distance in km.
haversine_km &lt;- function(lat1, lon1, lat2, lon2) {
  r &lt;- 6371
  to_rad &lt;- pi / 180
  dlat &lt;- (lat2 - lat1) * to_rad
  dlon &lt;- (lon2 - lon1) * to_rad
  a &lt;- sin(dlat / 2)^2 + cos(lat1 * to_rad) * cos(lat2 * to_rad) * sin(dlon / 2)^2
  2 * r * atan2(sqrt(a), sqrt(1 - a))
}

# Convert a distance in variable space into a 0-1 similarity.
sim_from_diff &lt;- function(x, scale_val) {
  exp(-abs(x) / scale_val)
}

n &lt;- nrow(dummy_data)
pairs &lt;- vector(&quot;list&quot;, n * (n - 1) / 2)
k &lt;- 1

sd_DDT &lt;- sd(dummy_data$DDT)
sd_PCP &lt;- sd(dummy_data$PCP)
sd_iso &lt;- sd(c(dummy_data$delta13C, dummy_data$delta15N))

for (i in 1:(n - 1)) {
  for (j in (i + 1):n) {
    d_geo &lt;- haversine_km(dummy_data$latitude[i], dummy_data$longitude[i],
                          dummy_data$latitude[j], dummy_data$longitude[j])

    d_ddt &lt;- dummy_data$DDT[i] - dummy_data$DDT[j]
    d_pcp &lt;- dummy_data$PCP[i] - dummy_data$PCP[j]
    d_iso &lt;- sqrt((dummy_data$delta13C[i] - dummy_data$delta13C[j])^2 +
                  (dummy_data$delta15N[i] - dummy_data$delta15N[j])^2)

    sim_ddt &lt;- sim_from_diff(d_ddt, sd_DDT)
    sim_pcp &lt;- sim_from_diff(d_pcp, sd_PCP)
    sim_iso &lt;- exp(-d_iso / sd_iso)
    sim_all &lt;- mean(c(sim_ddt, sim_pcp, sim_iso))

    pairs[[k]] &lt;- data.frame(
      site_i = dummy_data$site_id[i],
      site_j = dummy_data$site_id[j],
      distance_km = d_geo,
      sim_DDT = sim_ddt,
      sim_PCP = sim_pcp,
      sim_isotope = sim_iso,
      sim_overall = sim_all,
      stringsAsFactors = FALSE
    )
    k &lt;- k + 1
  }
}

pairwise_df &lt;- do.call(rbind, pairs)
write.csv(pairwise_df, file.path(out_dir, &quot;pairwise_distance_similarity.csv&quot;), row.names = FALSE)
summary(pairwise_df$distance_km)</code></pre>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
##    2.732  262.141  976.400  966.067 1270.096 2399.069</code></pre>
</div>
<div id="fit-distance-decay-curves-isolated-overall"
class="section level2">
<h2>3) Fit Distance-Decay Curves (Isolated + Overall)</h2>
<pre class="r"><code>fit_decay_models &lt;- function(distance, similarity) {
  dat &lt;- data.frame(distance = pmax(distance, 0), sim = pmin(pmax(similarity, 1e-6), 0.999999))

  # Exponential: sim = a * exp(-b * d)
  exp_fit &lt;- try(nls(sim ~ a * exp(-b * distance),
                     data = dat,
                     start = list(a = 0.9, b = 0.001),
                     control = nls.control(maxiter = 200)),
                 silent = TRUE)

  # Power-law: sim = a * (d + 1)^(-b)
  pow_fit &lt;- try(nls(sim ~ a * (distance + 1)^(-b),
                     data = dat,
                     start = list(a = 0.9, b = 0.1),
                     control = nls.control(maxiter = 200)),
                 silent = TRUE)

  # Log-linear: sim = a + b * log(d + 1)
  loglin_fit &lt;- lm(sim ~ log(distance + 1), data = dat)

  get_row &lt;- function(name, fit_obj, type) {
    if (inherits(fit_obj, &quot;try-error&quot;)) {
      return(data.frame(model = name, model_type = type, intercept = NA, slope = NA, AIC = NA, stringsAsFactors = FALSE))
    }
    if (type == &quot;lm&quot;) {
      co &lt;- coef(fit_obj)
      return(data.frame(
        model = name,
        model_type = type,
        intercept = unname(co[1]),
        slope = unname(co[2]),
        AIC = AIC(fit_obj),
        stringsAsFactors = FALSE
      ))
    }
    co &lt;- coef(fit_obj)
    data.frame(
      model = name,
      model_type = type,
      intercept = unname(co[1]),
      slope = unname(co[2]),
      AIC = AIC(fit_obj),
      stringsAsFactors = FALSE
    )
  }

  model_table &lt;- rbind(
    get_row(&quot;exponential&quot;, exp_fit, &quot;nls&quot;),
    get_row(&quot;power_law&quot;, pow_fit, &quot;nls&quot;),
    get_row(&quot;log_linear&quot;, loglin_fit, &quot;lm&quot;)
  )

  list(models = list(exp = exp_fit, pow = pow_fit, loglin = loglin_fit), table = model_table)
}

responses &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
fit_list &lt;- lapply(responses, function(v) fit_decay_models(pairwise_df$distance_km, pairwise_df[[v]]))
names(fit_list) &lt;- responses

model_summary &lt;- do.call(rbind, lapply(names(fit_list), function(v) {
  tab &lt;- fit_list[[v]]$table
  tab$response &lt;- v
  tab
}))
model_summary &lt;- model_summary[, c(&quot;response&quot;, &quot;model&quot;, &quot;model_type&quot;, &quot;intercept&quot;, &quot;slope&quot;, &quot;AIC&quot;)]

write.csv(model_summary, file.path(out_dir, &quot;distance_decay_model_summary.csv&quot;), row.names = FALSE)
model_summary</code></pre>
<pre><code>##       response       model model_type intercept         slope         AIC
## 1      sim_DDT exponential        nls 0.8918950  0.0009622721 -2076.38411
## 2      sim_DDT   power_law        nls 3.6157787  0.3385742219  -838.75084
## 3      sim_DDT  log_linear         lm 1.8645784 -0.2228697010 -1518.18375
## 4      sim_PCP exponential        nls 0.6160458  0.0004370203    31.46004
## 5      sim_PCP   power_law        nls 1.6630616  0.2158928413    63.21563
## 6      sim_PCP  log_linear         lm 1.1286117 -0.1092268215    37.65328
## 7  sim_isotope exponential        nls 0.9479722  0.0001194906 -6058.70794
## 8  sim_isotope   power_law        nls 1.2668346  0.0624370404 -5251.88429
## 9  sim_isotope  log_linear         lm 1.2130795 -0.0564808150 -5326.04029
## 10 sim_overall exponential        nls 0.8012607  0.0004013999 -3647.31623
## 11 sim_overall   power_law        nls 1.8910954  0.1899085175 -2932.16033
## 12 sim_overall  log_linear         lm 1.4020899 -0.1295257823 -3213.99493</code></pre>
</div>
<div id="null-model-randomized-tissue-composition"
class="section level2">
<h2>4) Null Model (Randomized Tissue Composition)</h2>
<pre class="r"><code>get_log_slope &lt;- function(distance, similarity) {
  fit &lt;- lm(similarity ~ log(distance + 1))
  unname(coef(fit)[2])
}

obs_slopes &lt;- c(
  DDT = get_log_slope(pairwise_df$distance_km, pairwise_df$sim_DDT),
  PCP = get_log_slope(pairwise_df$distance_km, pairwise_df$sim_PCP),
  isotope = get_log_slope(pairwise_df$distance_km, pairwise_df$sim_isotope),
  overall = get_log_slope(pairwise_df$distance_km, pairwise_df$sim_overall)
)

n_perm &lt;- 199
null_slopes &lt;- matrix(NA_real_, nrow = n_perm, ncol = 4)
colnames(null_slopes) &lt;- names(obs_slopes)

for (p in seq_len(n_perm)) {
  perm &lt;- dummy_data
  perm$DDT &lt;- sample(perm$DDT)
  perm$PCP &lt;- sample(perm$PCP)
  perm$delta13C &lt;- sample(perm$delta13C)
  perm$delta15N &lt;- sample(perm$delta15N)

  kk &lt;- 1
  sim_DDT &lt;- numeric(nrow(pairwise_df))
  sim_PCP &lt;- numeric(nrow(pairwise_df))
  sim_iso &lt;- numeric(nrow(pairwise_df))
  sim_all &lt;- numeric(nrow(pairwise_df))

  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      d_ddt &lt;- perm$DDT[i] - perm$DDT[j]
      d_pcp &lt;- perm$PCP[i] - perm$PCP[j]
      d_iso &lt;- sqrt((perm$delta13C[i] - perm$delta13C[j])^2 + (perm$delta15N[i] - perm$delta15N[j])^2)

      s1 &lt;- sim_from_diff(d_ddt, sd_DDT)
      s2 &lt;- sim_from_diff(d_pcp, sd_PCP)
      s3 &lt;- exp(-d_iso / sd_iso)

      sim_DDT[kk] &lt;- s1
      sim_PCP[kk] &lt;- s2
      sim_iso[kk] &lt;- s3
      sim_all[kk] &lt;- mean(c(s1, s2, s3))
      kk &lt;- kk + 1
    }
  }

  null_slopes[p, &quot;DDT&quot;] &lt;- get_log_slope(pairwise_df$distance_km, sim_DDT)
  null_slopes[p, &quot;PCP&quot;] &lt;- get_log_slope(pairwise_df$distance_km, sim_PCP)
  null_slopes[p, &quot;isotope&quot;] &lt;- get_log_slope(pairwise_df$distance_km, sim_iso)
  null_slopes[p, &quot;overall&quot;] &lt;- get_log_slope(pairwise_df$distance_km, sim_all)
}

null_summary &lt;- data.frame(
  response = names(obs_slopes),
  observed_slope = as.numeric(obs_slopes),
  null_mean = apply(null_slopes, 2, mean, na.rm = TRUE),
  null_sd = apply(null_slopes, 2, sd, na.rm = TRUE),
  p_lower = sapply(seq_along(obs_slopes), function(i) mean(null_slopes[, i] &lt;= obs_slopes[i], na.rm = TRUE)),
  p_upper = sapply(seq_along(obs_slopes), function(i) mean(null_slopes[, i] &gt;= obs_slopes[i], na.rm = TRUE)),
  stringsAsFactors = FALSE
)

write.csv(null_summary, file.path(out_dir, &quot;null_model_slope_comparison.csv&quot;), row.names = FALSE)
null_summary</code></pre>
<pre><code>##         response observed_slope     null_mean     null_sd p_lower p_upper
## DDT          DDT    -0.22286971 -3.502068e-04 0.006412642       0       1
## PCP          PCP    -0.10922682  6.055237e-04 0.006477364       0       1
## isotope  isotope    -0.05648081 -1.126967e-04 0.001844510       0       1
## overall  overall    -0.12952578  4.754011e-05 0.003252082       0       1</code></pre>
</div>
<div id="visualization-isolated-curves-and-generality"
class="section level2">
<h2>5) Visualization: Isolated Curves and Generality</h2>
<pre class="r"><code>par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))

plot_decay &lt;- function(distance, similarity, title_txt) {
  plot(distance, similarity,
       pch = 16, cex = 0.35,
       col = rgb(0, 0, 0, 0.18),
       xlab = &quot;Distance (km)&quot;, ylab = &quot;Similarity&quot;,
       main = title_txt)

  dseq &lt;- seq(min(distance), max(distance), length.out = 300)

  fobj &lt;- fit_decay_models(distance, similarity)$models

  if (!inherits(fobj$exp, &quot;try-error&quot;)) {
    ce &lt;- coef(fobj$exp)
    lines(dseq, ce[1] * exp(-ce[2] * dseq), lwd = 2, col = &quot;firebrick&quot;)
  }
  if (!inherits(fobj$pow, &quot;try-error&quot;)) {
    cp &lt;- coef(fobj$pow)
    lines(dseq, cp[1] * (dseq + 1)^(-cp[2]), lwd = 2, col = &quot;darkorange3&quot;)
  }
  cl &lt;- coef(fobj$loglin)
  lines(dseq, cl[1] + cl[2] * log(dseq + 1), lwd = 2, col = &quot;steelblue4&quot;)

  legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.8,
         legend = c(&quot;Exponential&quot;, &quot;Power-law&quot;, &quot;Log-linear&quot;),
         col = c(&quot;firebrick&quot;, &quot;darkorange3&quot;, &quot;steelblue4&quot;), lwd = 2)
}

plot_decay(pairwise_df$distance_km, pairwise_df$sim_DDT, &quot;DDT decay&quot;)
plot_decay(pairwise_df$distance_km, pairwise_df$sim_PCP, &quot;PCP decay&quot;)
plot_decay(pairwise_df$distance_km, pairwise_df$sim_isotope, &quot;Isotope decay&quot;)
plot_decay(pairwise_df$distance_km, pairwise_df$sim_overall, &quot;Overall decay&quot;)</code></pre>
<p><img src="outputs/figures/plotting-1.png" width="1056" /></p>
<pre class="r"><code># Generality panel: all responses in one view.
plot(pairwise_df$distance_km, pairwise_df$sim_DDT,
     pch = 16, cex = 0.25, col = rgb(178, 34, 34, 110, maxColorValue = 255),
     xlab = &quot;Distance (km)&quot;, ylab = &quot;Similarity&quot;, main = &quot;Generality across response types&quot;)
points(pairwise_df$distance_km, pairwise_df$sim_PCP,
       pch = 16, cex = 0.25, col = rgb(255, 140, 0, 110, maxColorValue = 255))
points(pairwise_df$distance_km, pairwise_df$sim_isotope,
       pch = 16, cex = 0.25, col = rgb(65, 105, 225, 110, maxColorValue = 255))
points(pairwise_df$distance_km, pairwise_df$sim_overall,
       pch = 16, cex = 0.25, col = rgb(34, 139, 34, 110, maxColorValue = 255))
legend(&quot;topright&quot;, bty = &quot;n&quot;,
       legend = c(&quot;DDT&quot;, &quot;PCP&quot;, &quot;Isotope&quot;, &quot;Overall&quot;),
       col = c(&quot;firebrick&quot;, &quot;darkorange3&quot;, &quot;royalblue&quot;, &quot;darkgreen&quot;),
       pch = 16)</code></pre>
<p><img src="outputs/figures/generality-1.png" width="768" /></p>
<pre class="r"><code># Pooled model to evaluate broad generality.
long_df &lt;- rbind(
  data.frame(response = &quot;DDT&quot;, distance_km = pairwise_df$distance_km, sim = pairwise_df$sim_DDT),
  data.frame(response = &quot;PCP&quot;, distance_km = pairwise_df$distance_km, sim = pairwise_df$sim_PCP),
  data.frame(response = &quot;isotope&quot;, distance_km = pairwise_df$distance_km, sim = pairwise_df$sim_isotope),
  data.frame(response = &quot;overall&quot;, distance_km = pairwise_df$distance_km, sim = pairwise_df$sim_overall)
)

pooled_fit &lt;- lm(sim ~ log(distance_km + 1) * response, data = long_df)
summary(pooled_fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = sim ~ log(distance_km + 1) * response, data = long_df)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.94276 -0.08482 -0.01533  0.06494  0.66360 
## 
## Coefficients:
##                                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                           1.864578   0.022991   81.10   &lt;2e-16 ***
## log(distance_km + 1)                 -0.222870   0.003504  -63.61   &lt;2e-16 ***
## responseisotope                      -0.651499   0.032514  -20.04   &lt;2e-16 ***
## responseoverall                      -0.462489   0.032514  -14.22   &lt;2e-16 ***
## responsePCP                          -0.735967   0.032514  -22.64   &lt;2e-16 ***
## log(distance_km + 1):responseisotope  0.166389   0.004955   33.58   &lt;2e-16 ***
## log(distance_km + 1):responseoverall  0.093344   0.004955   18.84   &lt;2e-16 ***
## log(distance_km + 1):responsePCP      0.113643   0.004955   22.93   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1556 on 7072 degrees of freedom
## Multiple R-squared:  0.6866, Adjusted R-squared:  0.6863 
## F-statistic:  2213 on 7 and 7072 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="output-files" class="section level2">
<h2>6) Output Files</h2>
<pre class="r"><code>cat(&quot;Generated files in outputs/:\n\n&quot;)</code></pre>
<p>Generated files in outputs/:</p>
<pre class="r"><code>print(list.files(out_dir, full.names = TRUE))</code></pre>
<p>[1] “outputs/cross_species_decay_summary.csv”<br />
[2] “outputs/distance_decay_model_summary.csv”<br />
[3] “outputs/dummy_tissue_data.csv”<br />
[4] “outputs/dyadic_mixed_model_blocked_cv.csv”<br />
[5] “outputs/dyadic_mixed_model_fixed_effects.csv”<br />
[6] “outputs/dyadic_trophic_model_blocked_cv.csv”<br />
[7] “outputs/dyadic_trophic_model_fixed_effects.csv”<br />
[8] “outputs/dyadic_trophic_transfer_comparison.csv”<br />
[9] “outputs/figures”<br />
[10] “outputs/gam_predicted_ddt_surface.csv”<br />
[11] “outputs/null_model_slope_comparison.csv”<br />
[12] “outputs/pairwise_distance_similarity.csv”<br />
[13] “outputs/real_testcase_distance_decay_model_summary.csv” [14]
“outputs/real_testcase_distance_decay_plots.png”<br />
[15] “outputs/real_testcase_null_model_summary.csv”<br />
[16] “outputs/real_testcase_pairwise_distance_similarity.csv” [17]
“outputs/real_testcase_prepared_data.csv”<br />
[18] “outputs/real_testcase_reported_fields_dictionary.csv”<br />
[19] “outputs/spatial_cv_loao_results.csv”<br />
[20] “outputs/spatiotemporal_scaling_model_summary.csv”</p>
</div>
<div id="interpretation-notes" class="section level2">
<h2>Interpretation Notes</h2>
<ul>
<li>More negative slopes indicate stronger distance-decay.</li>
<li>Compare AIC across exponential, power-law, and log-linear forms for
each response to identify best-supported decay shape.</li>
<li>Compare observed slope versus null distribution to evaluate whether
spatial structure exceeds random expectation.</li>
<li>Isolated curves show variable-specific scaling; pooled interaction
model evaluates generality across response types.</li>
</ul>
</div>
<div id="real-data-test-case-zd-stamp-samples-xlsx"
class="section level2">
<h2>7) Real-Data Test Case: ZD Stamp Samples (xlsx)</h2>
<pre class="r"><code>real_file_candidates &lt;- c(
  &quot;ZD_stamp_samples(AutoRecovered).xlsx&quot;,
  &quot;../ZD_stamp_samples(AutoRecovered).xlsx&quot;
)
real_file &lt;- real_file_candidates[file.exists(real_file_candidates)][1]

if (length(real_file) == 0 || !file.exists(real_file)) {
  cat(&quot;Real dataset file not found:&quot;, real_file, &quot;\n&quot;)
} else {
  if (!requireNamespace(&quot;readxl&quot;, quietly = TRUE)) {
    install.packages(&quot;readxl&quot;, repos = &quot;https://cran.r-project.org/&quot;)
  }
  library(readxl)

  samp &lt;- read_excel(real_file, sheet = &quot;stamp_samples&quot;)
  chem &lt;- read_excel(real_file, sheet = &quot;stamp_chemistry&quot;)
  fields_meta &lt;- read_excel(real_file, sheet = &quot;reported_fields&quot;)

  names(samp) &lt;- toupper(names(samp))
  names(chem) &lt;- tolower(names(chem))

  # Keep biodiversity-relevant sample metadata for interpretation.
  meta &lt;- unique(data.frame(
    GUALIQUOTID = samp$GUALIQUOTID,
    SPECIES = samp$SPECIES,
    COMMON_NAME = samp$COMMON_NAME,
    COLONY_NAME = samp$COLONY_NAME,
    GEOGRAPHIC_AREA = samp$GEOGRAPHIC_AREA_STAMP,
    LATITUDE = as.numeric(samp$LATITUDE),
    LONGITUDE = as.numeric(samp$LONGITUDE),
    COLLECTION_YEAR = as.numeric(samp$COLLECTION_YEAR),
    stringsAsFactors = FALSE
  ))

  chem$value &lt;- suppressWarnings(as.numeric(chem$value))
  if (&quot;detected&quot; %in% names(chem)) {
    chem &lt;- chem[isTRUE(chem$detected) | chem$detected %in% c(TRUE, &quot;TRUE&quot;, &quot;true&quot;, 1), ]
  }
  chem &lt;- chem[!is.na(chem$value), ]
  chem$analyte_lower &lt;- tolower(chem$analyte)

  # Approved defaults:
  # 1) DDT-family sum (DDT + DDE + DDD)
  # 2) PCB sum as PCP proxy
  # 3) Detected-only rows
  # 4) Unit harmonization within each metric
  ddt_idx &lt;- grepl(&quot;ddt|dde|ddd&quot;, chem$analyte_lower)
  pcb_idx &lt;- grepl(&quot;pcb&quot;, chem$analyte_lower)

  d13_name &lt;- if (any(grepl(&quot;d13c&quot;, chem$analyte_lower))) sort(unique(chem$analyte_lower[grepl(&quot;d13c&quot;, chem$analyte_lower)]))[1] else NA_character_
  d15_name &lt;- if (any(grepl(&quot;d15n&quot;, chem$analyte_lower))) sort(unique(chem$analyte_lower[grepl(&quot;d15n&quot;, chem$analyte_lower)]))[1] else NA_character_

  mode_unit &lt;- function(df) {
    if (!(&quot;units&quot; %in% names(df)) || nrow(df) == 0) return(NA_character_)
    ux &lt;- df$units
    ux &lt;- ux[!is.na(ux) &amp; ux != &quot;&quot;]
    if (length(ux) == 0) return(NA_character_)
    names(sort(table(ux), decreasing = TRUE))[1]
  }

  ddt_df &lt;- chem[ddt_idx, ]
  pcb_df &lt;- chem[pcb_idx, ]
  ddt_unit &lt;- mode_unit(ddt_df)
  pcb_unit &lt;- mode_unit(pcb_df)
  if (!is.na(ddt_unit)) ddt_df &lt;- ddt_df[ddt_df$units == ddt_unit, ]
  if (!is.na(pcb_unit)) pcb_df &lt;- pcb_df[pcb_df$units == pcb_unit, ]

  ddt_tbl &lt;- if (nrow(ddt_df) &gt; 0) {
    x &lt;- ddt_df[, c(&quot;gualiquotid&quot;, &quot;value&quot;)]
    names(x) &lt;- c(&quot;GUALIQUOTID&quot;, &quot;DDT_real&quot;)
    aggregate(DDT_real ~ GUALIQUOTID, data = x, FUN = sum, na.rm = TRUE)
  } else {
    data.frame(GUALIQUOTID = character(0), DDT_real = numeric(0), stringsAsFactors = FALSE)
  }

  pcp_tbl &lt;- if (nrow(pcb_df) &gt; 0) {
    x &lt;- pcb_df[, c(&quot;gualiquotid&quot;, &quot;value&quot;)]
    names(x) &lt;- c(&quot;GUALIQUOTID&quot;, &quot;PCP_or_PCB&quot;)
    aggregate(PCP_or_PCB ~ GUALIQUOTID, data = x, FUN = sum, na.rm = TRUE)
  } else {
    data.frame(GUALIQUOTID = character(0), PCP_or_PCB = numeric(0), stringsAsFactors = FALSE)
  }

  iso13_tbl &lt;- if (!is.na(d13_name)) {
    x &lt;- chem[chem$analyte_lower == d13_name, c(&quot;gualiquotid&quot;, &quot;value&quot;)]
    names(x) &lt;- c(&quot;GUALIQUOTID&quot;, &quot;delta13C_real&quot;)
    aggregate(delta13C_real ~ GUALIQUOTID, data = x, FUN = mean, na.rm = TRUE)
  } else {
    data.frame(GUALIQUOTID = character(0), delta13C_real = numeric(0), stringsAsFactors = FALSE)
  }

  iso15_tbl &lt;- if (!is.na(d15_name)) {
    x &lt;- chem[chem$analyte_lower == d15_name, c(&quot;gualiquotid&quot;, &quot;value&quot;)]
    names(x) &lt;- c(&quot;GUALIQUOTID&quot;, &quot;delta15N_real&quot;)
    aggregate(delta15N_real ~ GUALIQUOTID, data = x, FUN = mean, na.rm = TRUE)
  } else {
    data.frame(GUALIQUOTID = character(0), delta15N_real = numeric(0), stringsAsFactors = FALSE)
  }

  real_dat &lt;- Reduce(function(a, b) merge(a, b, by = &quot;GUALIQUOTID&quot;, all = TRUE),
                     list(meta, ddt_tbl, pcp_tbl, iso13_tbl, iso15_tbl))

  real_dat &lt;- real_dat[
    !is.na(real_dat$LATITUDE) &amp; !is.na(real_dat$LONGITUDE) &amp;
      !is.na(real_dat$DDT_real) &amp; !is.na(real_dat$PCP_or_PCB) &amp;
      !is.na(real_dat$delta13C_real) &amp; !is.na(real_dat$delta15N_real),
  ]

  write.csv(real_dat, file.path(out_dir, &quot;real_testcase_prepared_data.csv&quot;), row.names = FALSE)
  write.csv(fields_meta, file.path(out_dir, &quot;real_testcase_reported_fields_dictionary.csv&quot;), row.names = FALSE)

  cat(&quot;Rows available for full real-data testcase:&quot;, nrow(real_dat), &quot;\n&quot;)
  cat(&quot;DDT metric:&quot;, &quot;family sum (DDT + DDE + DDD)&quot;, &quot;\n&quot;)
  cat(&quot;DDT unit retained:&quot;, ifelse(is.na(ddt_unit), &quot;none&quot;, ddt_unit), &quot;\n&quot;)
  cat(&quot;PCP proxy metric:&quot;, &quot;PCB sum&quot;, &quot;\n&quot;)
  cat(&quot;PCB unit retained:&quot;, ifelse(is.na(pcb_unit), &quot;none&quot;, pcb_unit), &quot;\n&quot;)
  cat(&quot;Isotope analytes used:&quot;, ifelse(is.na(d13_name), &quot;none&quot;, d13_name), &quot;,&quot;,
      ifelse(is.na(d15_name), &quot;none&quot;, d15_name), &quot;\n&quot;)
  cat(&quot;Reported fields dictionary rows:&quot;, nrow(fields_meta), &quot;\n&quot;)
}</code></pre>
<pre><code>## Rows available for full real-data testcase: 216 
## DDT metric: family sum (DDT + DDE + DDD) 
## DDT unit retained: ng/g ww 
## PCP proxy metric: PCB sum 
## PCB unit retained: ng/g ww 
## Isotope analytes used: d13c , d15n 
## Reported fields dictionary rows: 17</code></pre>
</div>
<div id="real-data-distance-decay-null-spatial-scaling"
class="section level2">
<h2>8) Real-Data Distance-Decay + Null Spatial Scaling</h2>
<pre class="r"><code>if (exists(&quot;real_dat&quot;) &amp;&amp; nrow(real_dat) &gt; 10) {
  # Isotope standardization avoids one isotope dominating Euclidean distance.
  real_dat$z13 &lt;- as.numeric(scale(real_dat$delta13C_real))
  real_dat$z15 &lt;- as.numeric(scale(real_dat$delta15N_real))

  n_real &lt;- nrow(real_dat)
  pair_real &lt;- vector(&quot;list&quot;, n_real * (n_real - 1) / 2)
  kk &lt;- 1

  sd_ddt_real &lt;- sd(real_dat$DDT_real)
  sd_pcp_real &lt;- sd(real_dat$PCP_or_PCB)

  for (i in 1:(n_real - 1)) {
    for (j in (i + 1):n_real) {
      d_geo &lt;- haversine_km(real_dat$LATITUDE[i], real_dat$LONGITUDE[i],
                            real_dat$LATITUDE[j], real_dat$LONGITUDE[j])

      sim_ddt &lt;- sim_from_diff(real_dat$DDT_real[i] - real_dat$DDT_real[j], sd_ddt_real)
      sim_pcp &lt;- sim_from_diff(real_dat$PCP_or_PCB[i] - real_dat$PCP_or_PCB[j], sd_pcp_real)

      d_iso &lt;- sqrt((real_dat$z13[i] - real_dat$z13[j])^2 + (real_dat$z15[i] - real_dat$z15[j])^2)
      sim_iso &lt;- exp(-d_iso)
      sim_all &lt;- mean(c(sim_ddt, sim_pcp, sim_iso))

      pair_real[[kk]] &lt;- data.frame(
        id_i = real_dat$GUALIQUOTID[i],
        id_j = real_dat$GUALIQUOTID[j],
        area_i = real_dat$GEOGRAPHIC_AREA[i],
        area_j = real_dat$GEOGRAPHIC_AREA[j],
        species_i = real_dat$SPECIES[i],
        species_j = real_dat$SPECIES[j],
        year_i = real_dat$COLLECTION_YEAR[i],
        year_j = real_dat$COLLECTION_YEAR[j],
        time_lag_years = abs(real_dat$COLLECTION_YEAR[i] - real_dat$COLLECTION_YEAR[j]),
        distance_km = d_geo,
        sim_DDT = sim_ddt,
        sim_PCP_or_PCB = sim_pcp,
        sim_isotope = sim_iso,
        sim_overall = sim_all,
        stringsAsFactors = FALSE
      )
      kk &lt;- kk + 1
    }
  }

  pair_real &lt;- do.call(rbind, pair_real)

  real_model_summary &lt;- do.call(rbind, lapply(c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;), function(v) {
    tab &lt;- fit_decay_models(pair_real$distance_km, pair_real[[v]])$table
    tab$response &lt;- v
    tab
  }))
  real_model_summary &lt;- real_model_summary[, c(&quot;response&quot;, &quot;model&quot;, &quot;model_type&quot;, &quot;intercept&quot;, &quot;slope&quot;, &quot;AIC&quot;)]

  # Null model: constrained randomization within geographic area.
  n_perm_real &lt;- 499
  obs_real &lt;- c(
    sim_DDT = unname(coef(lm(sim_DDT ~ log(distance_km + 1), data = pair_real))[2]),
    sim_PCP_or_PCB = unname(coef(lm(sim_PCP_or_PCB ~ log(distance_km + 1), data = pair_real))[2]),
    sim_isotope = unname(coef(lm(sim_isotope ~ log(distance_km + 1), data = pair_real))[2]),
    sim_overall = unname(coef(lm(sim_overall ~ log(distance_km + 1), data = pair_real))[2])
  )

  null_real &lt;- matrix(NA_real_, nrow = n_perm_real, ncol = length(obs_real))
  colnames(null_real) &lt;- names(obs_real)

  for (p in seq_len(n_perm_real)) {
    perm &lt;- real_dat

    # Spatially constrained null preserves broad area and species structure.
    grp &lt;- paste(perm$GEOGRAPHIC_AREA, perm$SPECIES, sep = &quot;||&quot;)
    split_idx &lt;- split(seq_len(nrow(perm)), grp)
    for (idx in split_idx) {
      if (length(idx) &gt; 1) {
        perm$DDT_real[idx] &lt;- sample(perm$DDT_real[idx])
        perm$PCP_or_PCB[idx] &lt;- sample(perm$PCP_or_PCB[idx])
        perm$z13[idx] &lt;- sample(perm$z13[idx])
        perm$z15[idx] &lt;- sample(perm$z15[idx])
      }
    }

    m &lt;- nrow(perm)
    a &lt;- numeric(nrow(pair_real))
    b &lt;- numeric(nrow(pair_real))
    c &lt;- numeric(nrow(pair_real))
    d &lt;- numeric(nrow(pair_real))
    z &lt;- 1

    for (i in 1:(m - 1)) {
      for (j in (i + 1):m) {
        s1 &lt;- sim_from_diff(perm$DDT_real[i] - perm$DDT_real[j], sd_ddt_real)
        s2 &lt;- sim_from_diff(perm$PCP_or_PCB[i] - perm$PCP_or_PCB[j], sd_pcp_real)
        s3 &lt;- exp(-sqrt((perm$z13[i] - perm$z13[j])^2 + (perm$z15[i] - perm$z15[j])^2))
        a[z] &lt;- s1
        b[z] &lt;- s2
        c[z] &lt;- s3
        d[z] &lt;- mean(c(s1, s2, s3))
        z &lt;- z + 1
      }
    }

    null_real[p, &quot;sim_DDT&quot;] &lt;- coef(lm(a ~ log(pair_real$distance_km + 1)))[2]
    null_real[p, &quot;sim_PCP_or_PCB&quot;] &lt;- coef(lm(b ~ log(pair_real$distance_km + 1)))[2]
    null_real[p, &quot;sim_isotope&quot;] &lt;- coef(lm(c ~ log(pair_real$distance_km + 1)))[2]
    null_real[p, &quot;sim_overall&quot;] &lt;- coef(lm(d ~ log(pair_real$distance_km + 1)))[2]
  }

  null_real_summary &lt;- data.frame(
    response = names(obs_real),
    observed_slope = as.numeric(obs_real),
    null_mean = apply(null_real, 2, mean, na.rm = TRUE),
    null_sd = apply(null_real, 2, sd, na.rm = TRUE),
    p_lower = sapply(seq_along(obs_real), function(i) mean(null_real[, i] &lt;= obs_real[i], na.rm = TRUE)),
    p_upper = sapply(seq_along(obs_real), function(i) mean(null_real[, i] &gt;= obs_real[i], na.rm = TRUE)),
    stringsAsFactors = FALSE
  )

  write.csv(pair_real, file.path(out_dir, &quot;real_testcase_pairwise_distance_similarity.csv&quot;), row.names = FALSE)
  write.csv(real_model_summary, file.path(out_dir, &quot;real_testcase_distance_decay_model_summary.csv&quot;), row.names = FALSE)
  write.csv(null_real_summary, file.path(out_dir, &quot;real_testcase_null_model_summary.csv&quot;), row.names = FALSE)

  real_model_summary
  null_real_summary
} else {
  cat(&quot;Not enough complete real-data rows for full test-case decay analysis.\n&quot;)
}</code></pre>
<pre><code>##                      response observed_slope    null_mean      null_sd p_lower
## sim_DDT               sim_DDT   -0.018202740 -0.002442948 0.0009696398       0
## sim_PCP_or_PCB sim_PCP_or_PCB   -0.008165508  0.002243559 0.0007515016       0
## sim_isotope       sim_isotope   -0.022838142 -0.017025062 0.0010557232       0
## sim_overall       sim_overall   -0.016402130 -0.005741484 0.0005400921       0
##                p_upper
## sim_DDT              1
## sim_PCP_or_PCB       1
## sim_isotope          1
## sim_overall          1</code></pre>
</div>
<div id="real-data-distance-decay-plots" class="section level2">
<h2>9) Real-Data Distance-Decay Plots</h2>
<div id="a.-scatter-plots-with-all-three-functional-fits-aic-in-legend"
class="section level3">
<h3>A. Scatter plots with all three functional fits (AIC in legend)</h3>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping plots.\n&quot;)
} else {
  # Helper: scatter + exponential + power-law + log-linear fits, AIC in legend.
  draw_all_fits &lt;- function(x, y, ylab, title_txt) {
    ok &lt;- is.finite(x) &amp; is.finite(y)
    x &lt;- x[ok]; y &lt;- y[ok]
    plot(x, y, xlab = &quot;Distance (km)&quot;, ylab = ylab, main = title_txt,
         pch = 16, cex = 0.4, col = rgb(0, 0, 0, 0.18))
    if (length(x) &lt; 6) return(invisible(NULL))
    dseq &lt;- seq(0.1, max(x), length.out = 300)
    fits &lt;- fit_decay_models(x, y)
    at   &lt;- fits$table
    get_aic &lt;- function(nm) { v &lt;- at$AIC[at$model == nm]; if (length(v) &amp;&amp; is.finite(v)) round(v) else NA }
    leg_labs &lt;- character(3); leg_show &lt;- logical(3)
    if (!inherits(fits$models$exp, &quot;try-error&quot;)) {
      ce &lt;- coef(fits$models$exp)
      lines(dseq, ce[1] * exp(-ce[2] * dseq), lwd = 2.2, col = &quot;firebrick&quot;)
      leg_labs[1] &lt;- sprintf(&quot;Exponential (AIC=%s)&quot;, get_aic(&quot;exponential&quot;))
      leg_show[1] &lt;- TRUE
    }
    if (!inherits(fits$models$pow, &quot;try-error&quot;)) {
      cp &lt;- coef(fits$models$pow)
      lines(dseq, cp[1] * (dseq + 1)^(-cp[2]), lwd = 2.2, col = &quot;darkorange3&quot;)
      leg_labs[2] &lt;- sprintf(&quot;Power-law (AIC=%s)&quot;, get_aic(&quot;power_law&quot;))
      leg_show[2] &lt;- TRUE
    }
    cl &lt;- coef(fits$models$loglin)
    lines(dseq, cl[1] + cl[2] * log(dseq + 1), lwd = 2.2, col = &quot;steelblue4&quot;)
    leg_labs[3] &lt;- sprintf(&quot;Log-linear (AIC=%s)&quot;, get_aic(&quot;log_linear&quot;))
    leg_show[3] &lt;- TRUE
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.7,
           legend = leg_labs[leg_show],
           col = c(&quot;firebrick&quot;, &quot;darkorange3&quot;, &quot;steelblue4&quot;)[leg_show], lwd = 2.2)
  }

  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  draw_all_fits(pair_real$distance_km, pair_real$sim_DDT,        &quot;Similarity (DDT family)&quot;, &quot;DDT – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_PCP_or_PCB, &quot;Similarity (PCB proxy)&quot;,  &quot;PCP/PCB – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_isotope,    &quot;Similarity (isotope)&quot;,    &quot;Isotope – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_overall,    &quot;Similarity (overall)&quot;,    &quot;Overall – Distance Decay (all species)&quot;)

  # Save standalone PNG.
  png(file.path(out_dir, &quot;real_testcase_distance_decay_plots.png&quot;), width = 1800, height = 1400, res = 180)
  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  draw_all_fits(pair_real$distance_km, pair_real$sim_DDT,        &quot;Similarity (DDT family)&quot;, &quot;DDT – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_PCP_or_PCB, &quot;Similarity (PCB proxy)&quot;,  &quot;PCP/PCB – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_isotope,    &quot;Similarity (isotope)&quot;,    &quot;Isotope – Distance Decay (all species)&quot;)
  draw_all_fits(pair_real$distance_km, pair_real$sim_overall,    &quot;Similarity (overall)&quot;,    &quot;Overall – Distance Decay (all species)&quot;)
  dev.off()
}</code></pre>
<p><img src="outputs/figures/real-scatter-fits-1.png" width="1152" /></p>
<pre><code>## quartz_off_screen 
##                 2</code></pre>
</div>
<div id="b.-binned-mean-similarity-95-ci-by-distance"
class="section level3">
<h3>B. Binned mean similarity ± 95% CI by distance</h3>
<pre class="r"><code>if (exists(&quot;pair_real&quot;)) {
  # Compute per-bin mean ± 95% CI (t-based).
  bin_sim &lt;- function(df, var, n_bins = 12) {
    df &lt;- df[is.finite(df[[var]]) &amp; is.finite(df$distance_km), ]
    if (nrow(df) &lt; 10) return(NULL)
    n_bins &lt;- min(n_bins, floor(nrow(df) / 4))
    brks &lt;- seq(min(df$distance_km), max(df$distance_km), length.out = n_bins + 1)
    df$bin &lt;- cut(df$distance_km, breaks = brks, labels = FALSE, include.lowest = TRUE)
    mids &lt;- (brks[-length(brks)] + brks[-1]) / 2
    out &lt;- lapply(seq_len(n_bins), function(b) {
      vals &lt;- df[[var]][df$bin == b]
      if (length(vals) &lt; 3) return(NULL)
      se &lt;- sd(vals) / sqrt(length(vals))
      ci &lt;- qt(0.975, df = length(vals) - 1) * se
      data.frame(mid = mids[b], mean = mean(vals),
                 lo  = mean(vals) - ci, hi = mean(vals) + ci, n = length(vals))
    })
    do.call(rbind, Filter(Negate(is.null), out))
  }

  plot_binned &lt;- function(bd, ylab, title_txt, col_line = &quot;firebrick&quot;) {
    if (is.null(bd) || nrow(bd) &lt; 2) { plot.new(); title(title_txt); return(invisible()) }
    ylim_r &lt;- c(pmax(0, min(bd$lo, na.rm = TRUE) - 0.04),
                pmin(1, max(bd$hi, na.rm = TRUE) + 0.06))
    plot(bd$mid, bd$mean, type = &quot;n&quot;, xlim = range(bd$mid), ylim = ylim_r,
         xlab = &quot;Distance (km)&quot;, ylab = ylab, main = title_txt)
    polygon(c(bd$mid, rev(bd$mid)), c(bd$hi, rev(bd$lo)),
            col = adjustcolor(col_line, alpha.f = 0.18), border = NA)
    lines(bd$mid, bd$mean, lwd = 2.5, col = col_line)
    points(bd$mid, bd$mean, pch = 21, bg = &quot;white&quot;, col = col_line, cex = 1.3, lwd = 1.8)
    text(bd$mid, bd$hi + diff(ylim_r) * 0.04,
         labels = paste0(&quot;n=&quot;, bd$n), cex = 0.52, srt = 45, adj = 0)
  }

  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  plot_binned(bin_sim(pair_real, &quot;sim_DDT&quot;),        &quot;Mean Similarity (DDT)&quot;,     &quot;DDT – Binned Mean ± 95% CI (all species)&quot;,     &quot;firebrick&quot;)
  plot_binned(bin_sim(pair_real, &quot;sim_PCP_or_PCB&quot;), &quot;Mean Similarity (PCP/PCB)&quot;, &quot;PCP/PCB – Binned Mean ± 95% CI (all species)&quot;, &quot;darkorange3&quot;)
  plot_binned(bin_sim(pair_real, &quot;sim_isotope&quot;),    &quot;Mean Similarity (isotope)&quot;, &quot;Isotope – Binned Mean ± 95% CI (all species)&quot;, &quot;steelblue4&quot;)
  plot_binned(bin_sim(pair_real, &quot;sim_overall&quot;),    &quot;Mean Similarity (overall)&quot;, &quot;Overall – Binned Mean ± 95% CI (all species)&quot;, &quot;darkorchid4&quot;)
}</code></pre>
<p><img src="outputs/figures/real-binned-ci-1.png" width="1152" /></p>
</div>
<div id="c.-observed-vs.-null-slope-distributions"
class="section level3">
<h3>C. Observed vs. null: slope distributions</h3>
<pre class="r"><code>if (exists(&quot;null_real_summary&quot;) &amp;&amp; nrow(null_real_summary) &gt; 0) {
  resp_labels &lt;- c(sim_DDT = &quot;DDT&quot;, sim_PCP_or_PCB = &quot;PCP/PCB&quot;,
                   sim_isotope = &quot;Isotope&quot;, sim_overall = &quot;Overall&quot;)
  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  for (rv in names(resp_labels)) {
    row &lt;- null_real_summary[null_real_summary$response == rv, ]
    if (nrow(row) == 0) next
    obs  &lt;- row$observed_slope
    nmn  &lt;- row$null_mean
    nsd  &lt;- row$null_sd
    set.seed(42); null_draw &lt;- rnorm(2000, mean = nmn, sd = nsd)
    xlim_r &lt;- range(c(null_draw, obs)) + c(-1, 1) * 0.01 * diff(range(c(null_draw, obs)))
    hist(null_draw, breaks = 50, col = grey(0.82), border = &quot;white&quot;, freq = FALSE,
         main = paste(resp_labels[rv], &quot;– Observed vs. Null Slopes&quot;),
         xlab = &quot;Log-linear slope&quot;, xlim = xlim_r)
    abline(v = obs, col = &quot;firebrick&quot;, lwd = 2.8)
    abline(v = nmn, col = &quot;steelblue4&quot;, lwd = 2, lty = 2)
    pval &lt;- min(row$p_lower, row$p_upper)
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.75,
           legend = c(sprintf(&quot;Observed: %.4f&quot;, obs),
                      sprintf(&quot;Null mean: %.4f&quot;, nmn),
                      sprintf(&quot;p = %.3f&quot;, pval)),
           col = c(&quot;firebrick&quot;, &quot;steelblue4&quot;, NA), lwd = c(2.8, 2, NA), lty = c(1, 2, NA))
  }
} else {
  cat(&quot;null_real_summary not available.\n&quot;)
}</code></pre>
<p><img src="outputs/figures/real-null-slopes-1.png" width="1152" /></p>
</div>
<div id="d.-observed-vs.-null-decay-curve-comparison"
class="section level3">
<h3>D. Observed vs. null: decay curve comparison</h3>
<pre class="r"><code>if (exists(&quot;pair_real&quot;) &amp;&amp; exists(&quot;null_real_summary&quot;) &amp;&amp; nrow(null_real_summary) &gt; 0) {
  resp_vars  &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
  resp_names &lt;- c(&quot;DDT&quot;, &quot;PCP/PCB&quot;, &quot;Isotope&quot;, &quot;Overall&quot;)
  col_obs    &lt;- c(&quot;firebrick&quot;, &quot;darkorange3&quot;, &quot;steelblue4&quot;, &quot;darkorchid4&quot;)

  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  for (ii in seq_along(resp_vars)) {
    rv &lt;- resp_vars[ii]
    x  &lt;- pair_real$distance_km; y &lt;- pair_real[[rv]]
    ok &lt;- is.finite(x) &amp; is.finite(y); x &lt;- x[ok]; y &lt;- y[ok]
    dseq &lt;- seq(0.1, max(x), length.out = 300)

    obs_lm  &lt;- lm(y ~ log(x + 1))
    obs_a   &lt;- coef(obs_lm)[1]; obs_b &lt;- coef(obs_lm)[2]
    obs_hat &lt;- obs_a + obs_b * log(dseq + 1)

    nr         &lt;- null_real_summary[null_real_summary$response == rv, ]
    null_b_mn  &lt;- nr$null_mean; null_b_sd &lt;- nr$null_sd
    null_mn    &lt;- obs_a + null_b_mn * log(dseq + 1)
    null_hi    &lt;- obs_a + (null_b_mn + 2 * null_b_sd) * log(dseq + 1)
    null_lo    &lt;- obs_a + (null_b_mn - 2 * null_b_sd) * log(dseq + 1)

    ylim_r &lt;- range(c(0, 1, obs_hat, null_mn, null_lo, null_hi), na.rm = TRUE)
    plot(x, y, pch = 16, cex = 0.35, col = rgb(0, 0, 0, 0.12),
         xlab = &quot;Distance (km)&quot;, ylab = &quot;Similarity&quot;,
         main = paste(resp_names[ii], &quot;– Observed vs. Null Decay&quot;),
         ylim = ylim_r)
    polygon(c(dseq, rev(dseq)), c(null_hi, rev(null_lo)),
            col = adjustcolor(&quot;grey50&quot;, alpha.f = 0.28), border = NA)
    lines(dseq, null_mn,  col = &quot;grey40&quot;,      lwd = 2,   lty = 2)
    lines(dseq, obs_hat,  col = col_obs[ii],   lwd = 2.5)
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.75,
           legend = c(&quot;Observed (log-linear)&quot;, &quot;Null mean&quot;, &quot;Null ± 2 SD band&quot;),
           col = c(col_obs[ii], &quot;grey40&quot;, adjustcolor(&quot;grey50&quot;, 0.5)),
           lwd = c(2.5, 2, 8), lty = c(1, 2, 1))
  }
}</code></pre>
<p><img src="outputs/figures/real-null-decay-bands-1.png" width="1152" /></p>
</div>
</div>
<div id="species-level-distance-decay-analysis" class="section level2">
<h2>10) Species-Level Distance-Decay Analysis</h2>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping species breakdown.\n&quot;)
} else {
  species_list &lt;- sort(unique(c(pair_real$species_i, pair_real$species_j)))
  species_list &lt;- species_list[!is.na(species_list) &amp; nchar(trimws(species_list)) &gt; 0]

  for (sp in species_list) {
    pr_sp &lt;- pair_real[pair_real$species_i == sp &amp; pair_real$species_j == sp, ]
    if (nrow(pr_sp) &lt; 10 || length(unique(pr_sp$distance_km)) &lt; 4) next

    cat(&quot;\n\n### Species:&quot;, sp, &quot;(&quot;, nrow(pr_sp), &quot;within-species pairs)\n\n&quot;)

    # Scatter + all three fits.
    par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
    draw_all_fits(pr_sp$distance_km, pr_sp$sim_DDT,        &quot;Similarity (DDT)&quot;,     paste0(sp, &quot; – DDT&quot;))
    draw_all_fits(pr_sp$distance_km, pr_sp$sim_PCP_or_PCB, &quot;Similarity (PCP/PCB)&quot;, paste0(sp, &quot; – PCP/PCB&quot;))
    draw_all_fits(pr_sp$distance_km, pr_sp$sim_isotope,    &quot;Similarity (isotope)&quot;, paste0(sp, &quot; – Isotope&quot;))
    draw_all_fits(pr_sp$distance_km, pr_sp$sim_overall,    &quot;Similarity (overall)&quot;, paste0(sp, &quot; – Overall&quot;))

    # Binned mean ± 95% CI.
    par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
    plot_binned(bin_sim(pr_sp, &quot;sim_DDT&quot;),        &quot;Mean Sim. (DDT)&quot;,     paste0(sp, &quot; – DDT ± 95% CI&quot;),     &quot;firebrick&quot;)
    plot_binned(bin_sim(pr_sp, &quot;sim_PCP_or_PCB&quot;), &quot;Mean Sim. (PCP/PCB)&quot;, paste0(sp, &quot; – PCP/PCB ± 95% CI&quot;), &quot;darkorange3&quot;)
    plot_binned(bin_sim(pr_sp, &quot;sim_isotope&quot;),    &quot;Mean Sim. (isotope)&quot;, paste0(sp, &quot; – Isotope ± 95% CI&quot;), &quot;steelblue4&quot;)
    plot_binned(bin_sim(pr_sp, &quot;sim_overall&quot;),    &quot;Mean Sim. (overall)&quot;, paste0(sp, &quot; – Overall ± 95% CI&quot;), &quot;darkorchid4&quot;)

    # Species-level model fit table.
    sp_fits &lt;- do.call(rbind, lapply(c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;), function(v) {
      x &lt;- pr_sp$distance_km; y &lt;- pr_sp[[v]]
      ok &lt;- is.finite(x) &amp; is.finite(y)
      if (sum(ok) &lt; 8) return(NULL)
      tab &lt;- fit_decay_models(x[ok], y[ok])$table
      tab$response &lt;- v; tab
    }))
    if (!is.null(sp_fits) &amp;&amp; nrow(sp_fits) &gt; 0) {
      best &lt;- sp_fits[!is.na(sp_fits$AIC), ]
      best &lt;- best[order(best$response, best$AIC), ]
      cat(&quot;\n**Best-fit models (lowest AIC per response):**\n\n&quot;)
      top &lt;- do.call(rbind, lapply(split(best, best$response), function(d) d[1, ]))
      print(knitr::kable(top[, c(&quot;response&quot;,&quot;model&quot;,&quot;intercept&quot;,&quot;slope&quot;,&quot;AIC&quot;)], digits = 4,
                         row.names = FALSE))
      cat(&quot;\n&quot;)
    }
  }
}</code></pre>
<div id="species-larus-glaucescens-66-within-species-pairs"
class="section level3">
<h3>Species: Larus glaucescens ( 66 within-species pairs)</h3>
<p><img src="outputs/figures/species-breakdown-1.png" width="1152" /><img src="outputs/figures/species-breakdown-2.png" width="1152" />
<strong>Best-fit models (lowest AIC per response):</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">response</th>
<th align="left">model</th>
<th align="right">intercept</th>
<th align="right">slope</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sim_DDT</td>
<td align="left">exponential</td>
<td align="right">0.5052</td>
<td align="right">0.0002</td>
<td align="right">25.9027</td>
</tr>
<tr class="even">
<td align="left">sim_isotope</td>
<td align="left">power_law</td>
<td align="right">0.3072</td>
<td align="right">0.0223</td>
<td align="right">-6.4346</td>
</tr>
<tr class="odd">
<td align="left">sim_overall</td>
<td align="left">log_linear</td>
<td align="right">0.4182</td>
<td align="right">-0.0070</td>
<td align="right">-42.5915</td>
</tr>
<tr class="even">
<td align="left">sim_PCP_or_PCB</td>
<td align="left">log_linear</td>
<td align="right">0.4453</td>
<td align="right">-0.0032</td>
<td align="right">16.1815</td>
</tr>
</tbody>
</table>
</div>
<div id="species-larus-hyperboreus-36-within-species-pairs"
class="section level3">
<h3>Species: Larus hyperboreus ( 36 within-species pairs)</h3>
<p><img src="outputs/figures/species-breakdown-3.png" width="1152" /><img src="outputs/figures/species-breakdown-4.png" width="1152" />
<strong>Best-fit models (lowest AIC per response):</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">response</th>
<th align="left">model</th>
<th align="right">intercept</th>
<th align="right">slope</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sim_DDT</td>
<td align="left">power_law</td>
<td align="right">0.7654</td>
<td align="right">0.0160</td>
<td align="right">-24.2855</td>
</tr>
<tr class="even">
<td align="left">sim_isotope</td>
<td align="left">exponential</td>
<td align="right">0.3259</td>
<td align="right">0.0006</td>
<td align="right">-4.3907</td>
</tr>
<tr class="odd">
<td align="left">sim_overall</td>
<td align="left">log_linear</td>
<td align="right">0.6029</td>
<td align="right">-0.0057</td>
<td align="right">-36.5499</td>
</tr>
<tr class="even">
<td align="left">sim_PCP_or_PCB</td>
<td align="left">exponential</td>
<td align="right">0.7290</td>
<td align="right">-0.0001</td>
<td align="right">-13.9482</td>
</tr>
</tbody>
</table>
</div>
<div id="species-uria-aalge-8515-within-species-pairs"
class="section level3">
<h3>Species: Uria aalge ( 8515 within-species pairs)</h3>
<p><img src="outputs/figures/species-breakdown-5.png" width="1152" /><img src="outputs/figures/species-breakdown-6.png" width="1152" />
<strong>Best-fit models (lowest AIC per response):</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">response</th>
<th align="left">model</th>
<th align="right">intercept</th>
<th align="right">slope</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sim_DDT</td>
<td align="left">exponential</td>
<td align="right">0.6332</td>
<td align="right">3e-04</td>
<td align="right">2678.154</td>
</tr>
<tr class="even">
<td align="left">sim_isotope</td>
<td align="left">exponential</td>
<td align="right">0.3812</td>
<td align="right">3e-04</td>
<td align="right">-2075.631</td>
</tr>
<tr class="odd">
<td align="left">sim_overall</td>
<td align="left">exponential</td>
<td align="right">0.5358</td>
<td align="right">3e-04</td>
<td align="right">-4205.723</td>
</tr>
<tr class="even">
<td align="left">sim_PCP_or_PCB</td>
<td align="left">exponential</td>
<td align="right">0.5948</td>
<td align="right">2e-04</td>
<td align="right">3818.317</td>
</tr>
</tbody>
</table>
</div>
<div id="species-uria-lomvia-1326-within-species-pairs"
class="section level3">
<h3>Species: Uria lomvia ( 1326 within-species pairs)</h3>
<p><img src="outputs/figures/species-breakdown-7.png" width="1152" /><img src="outputs/figures/species-breakdown-8.png" width="1152" />
<strong>Best-fit models (lowest AIC per response):</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">response</th>
<th align="left">model</th>
<th align="right">intercept</th>
<th align="right">slope</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sim_DDT</td>
<td align="left">exponential</td>
<td align="right">0.6915</td>
<td align="right">0.0003</td>
<td align="right">37.4555</td>
</tr>
<tr class="even">
<td align="left">sim_isotope</td>
<td align="left">power_law</td>
<td align="right">0.4257</td>
<td align="right">0.0924</td>
<td align="right">-436.5934</td>
</tr>
<tr class="odd">
<td align="left">sim_overall</td>
<td align="left">exponential</td>
<td align="right">0.5697</td>
<td align="right">0.0003</td>
<td align="right">-1158.0910</td>
</tr>
<tr class="even">
<td align="left">sim_PCP_or_PCB</td>
<td align="left">exponential</td>
<td align="right">0.6522</td>
<td align="right">0.0002</td>
<td align="right">239.3143</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="cross-species-summary-table" class="section level2">
<h2>11) Cross-Species Summary Table</h2>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping cross-species summary.\n&quot;)
} else {
  sp_all &lt;- sort(unique(c(pair_real$species_i, pair_real$species_j)))
  sp_all &lt;- sp_all[!is.na(sp_all) &amp; nchar(trimws(sp_all)) &gt; 0]

  sp_rows &lt;- lapply(sp_all, function(sp) {
    pr_sp &lt;- pair_real[pair_real$species_i == sp &amp; pair_real$species_j == sp, ]
    if (nrow(pr_sp) &lt; 10) return(NULL)
    lapply(c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;), function(v) {
      x  &lt;- pr_sp$distance_km
      y  &lt;- pr_sp[[v]]
      ok &lt;- is.finite(x) &amp; is.finite(y)
      if (sum(ok) &lt; 8) return(NULL)
      fits &lt;- fit_decay_models(x[ok], y[ok])
      tab  &lt;- fits$table[!is.na(fits$table$AIC), ]
      if (nrow(tab) == 0) return(NULL)
      best &lt;- tab[which.min(tab$AIC), ]
      r2   &lt;- summary(lm(y[ok] ~ log(x[ok] + 1)))$r.squared
      data.frame(
        Species    = sp,
        Response   = v,
        N_pairs    = sum(ok),
        Best_model = best$model,
        Intercept  = round(best$intercept, 4),
        Slope      = round(best$slope, 4),
        Best_AIC   = round(best$AIC, 1),
        R2_loglin  = round(r2, 3),
        stringsAsFactors = FALSE
      )
    })
  })

  sp_summary &lt;- do.call(rbind, Filter(Negate(is.null),
                 unlist(sp_rows, recursive = FALSE)))

  if (!is.null(sp_summary) &amp;&amp; nrow(sp_summary) &gt; 0) {
    sp_summary$Response &lt;- gsub(&quot;sim_DDT&quot;,        &quot;DDT&quot;,     sp_summary$Response)
    sp_summary$Response &lt;- gsub(&quot;sim_PCP_or_PCB&quot;, &quot;PCP/PCB&quot;, sp_summary$Response)
    sp_summary$Response &lt;- gsub(&quot;sim_isotope&quot;,    &quot;Isotope&quot;, sp_summary$Response)
    sp_summary$Response &lt;- gsub(&quot;sim_overall&quot;,    &quot;Overall&quot;, sp_summary$Response)

    write.csv(sp_summary, file.path(out_dir, &quot;cross_species_decay_summary.csv&quot;),
              row.names = FALSE)

    print(knitr::kable(
      sp_summary, row.names = FALSE,
      col.names = c(&quot;Species&quot;, &quot;Response&quot;, &quot;N pairs&quot;, &quot;Best model&quot;,
                    &quot;Intercept&quot;, &quot;Slope&quot;, &quot;Best AIC&quot;, &quot;R\u00b2 (log-lin)&quot;),
      caption = paste(&quot;Table 1. Cross-species distance-decay comparison.&quot;,
                      &quot;Best-supported functional form (lowest AIC) per response per species,&quot;,
                      &quot;with slope, best-model AIC, and log-linear R\u00b2.&quot;)
    ))
  }
}</code></pre>
<table>
<caption>Table 1. Cross-species distance-decay comparison.
Best-supported functional form (lowest AIC) per response per species,
with slope, best-model AIC, and log-linear R².</caption>
<colgroup>
<col width="20%" />
<col width="10%" />
<col width="9%" />
<col width="13%" />
<col width="11%" />
<col width="9%" />
<col width="10%" />
<col width="14%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Species</th>
<th align="left">Response</th>
<th align="right">N pairs</th>
<th align="left">Best model</th>
<th align="right">Intercept</th>
<th align="right">Slope</th>
<th align="right">Best AIC</th>
<th align="right">R² (log-lin)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Larus glaucescens</td>
<td align="left">DDT</td>
<td align="right">66</td>
<td align="left">exponential</td>
<td align="right">0.5052</td>
<td align="right">0.0002</td>
<td align="right">25.9</td>
<td align="right">0.011</td>
</tr>
<tr class="even">
<td align="left">Larus glaucescens</td>
<td align="left">PCP/PCB</td>
<td align="right">66</td>
<td align="left">log_linear</td>
<td align="right">0.4453</td>
<td align="right">-0.0032</td>
<td align="right">16.2</td>
<td align="right">0.001</td>
</tr>
<tr class="odd">
<td align="left">Larus glaucescens</td>
<td align="left">Isotope</td>
<td align="right">66</td>
<td align="left">power_law</td>
<td align="right">0.3072</td>
<td align="right">0.0223</td>
<td align="right">-6.4</td>
<td align="right">0.006</td>
</tr>
<tr class="even">
<td align="left">Larus glaucescens</td>
<td align="left">Overall</td>
<td align="right">66</td>
<td align="left">log_linear</td>
<td align="right">0.4182</td>
<td align="right">-0.0070</td>
<td align="right">-42.6</td>
<td align="right">0.012</td>
</tr>
<tr class="odd">
<td align="left">Larus hyperboreus</td>
<td align="left">DDT</td>
<td align="right">36</td>
<td align="left">power_law</td>
<td align="right">0.7654</td>
<td align="right">0.0160</td>
<td align="right">-24.3</td>
<td align="right">0.035</td>
</tr>
<tr class="even">
<td align="left">Larus hyperboreus</td>
<td align="left">PCP/PCB</td>
<td align="right">36</td>
<td align="left">exponential</td>
<td align="right">0.7290</td>
<td align="right">-0.0001</td>
<td align="right">-13.9</td>
<td align="right">0.006</td>
</tr>
<tr class="odd">
<td align="left">Larus hyperboreus</td>
<td align="left">Isotope</td>
<td align="right">36</td>
<td align="left">exponential</td>
<td align="right">0.3259</td>
<td align="right">0.0006</td>
<td align="right">-4.4</td>
<td align="right">0.017</td>
</tr>
<tr class="even">
<td align="left">Larus hyperboreus</td>
<td align="left">Overall</td>
<td align="right">36</td>
<td align="left">log_linear</td>
<td align="right">0.6029</td>
<td align="right">-0.0057</td>
<td align="right">-36.5</td>
<td align="right">0.012</td>
</tr>
<tr class="odd">
<td align="left">Uria aalge</td>
<td align="left">DDT</td>
<td align="right">8515</td>
<td align="left">exponential</td>
<td align="right">0.6332</td>
<td align="right">0.0003</td>
<td align="right">2678.2</td>
<td align="right">0.027</td>
</tr>
<tr class="even">
<td align="left">Uria aalge</td>
<td align="left">PCP/PCB</td>
<td align="right">8515</td>
<td align="left">exponential</td>
<td align="right">0.5948</td>
<td align="right">0.0002</td>
<td align="right">3818.3</td>
<td align="right">0.007</td>
</tr>
<tr class="odd">
<td align="left">Uria aalge</td>
<td align="left">Isotope</td>
<td align="right">8515</td>
<td align="left">exponential</td>
<td align="right">0.3812</td>
<td align="right">0.0003</td>
<td align="right">-2075.6</td>
<td align="right">0.056</td>
</tr>
<tr class="even">
<td align="left">Uria aalge</td>
<td align="left">Overall</td>
<td align="right">8515</td>
<td align="left">exponential</td>
<td align="right">0.5358</td>
<td align="right">0.0003</td>
<td align="right">-4205.7</td>
<td align="right">0.044</td>
</tr>
<tr class="odd">
<td align="left">Uria lomvia</td>
<td align="left">DDT</td>
<td align="right">1326</td>
<td align="left">exponential</td>
<td align="right">0.6915</td>
<td align="right">0.0003</td>
<td align="right">37.5</td>
<td align="right">0.113</td>
</tr>
<tr class="even">
<td align="left">Uria lomvia</td>
<td align="left">PCP/PCB</td>
<td align="right">1326</td>
<td align="left">exponential</td>
<td align="right">0.6522</td>
<td align="right">0.0002</td>
<td align="right">239.3</td>
<td align="right">0.017</td>
</tr>
<tr class="odd">
<td align="left">Uria lomvia</td>
<td align="left">Isotope</td>
<td align="right">1326</td>
<td align="left">power_law</td>
<td align="right">0.4257</td>
<td align="right">0.0924</td>
<td align="right">-436.6</td>
<td align="right">0.139</td>
</tr>
<tr class="even">
<td align="left">Uria lomvia</td>
<td align="left">Overall</td>
<td align="right">1326</td>
<td align="left">exponential</td>
<td align="right">0.5697</td>
<td align="right">0.0003</td>
<td align="right">-1158.1</td>
<td align="right">0.148</td>
</tr>
<tr class="odd">
<td align="left">Uria spp.</td>
<td align="left">DDT</td>
<td align="right">66</td>
<td align="left">exponential</td>
<td align="right">0.8674</td>
<td align="right">0.0006</td>
<td align="right">-120.2</td>
<td align="right">0.440</td>
</tr>
<tr class="even">
<td align="left">Uria spp.</td>
<td align="left">PCP/PCB</td>
<td align="right">66</td>
<td align="left">log_linear</td>
<td align="right">0.7247</td>
<td align="right">-0.0188</td>
<td align="right">-38.0</td>
<td align="right">0.093</td>
</tr>
<tr class="odd">
<td align="left">Uria spp.</td>
<td align="left">Isotope</td>
<td align="right">66</td>
<td align="left">log_linear</td>
<td align="right">0.5197</td>
<td align="right">-0.0371</td>
<td align="right">-18.1</td>
<td align="right">0.227</td>
</tr>
<tr class="even">
<td align="left">Uria spp.</td>
<td align="left">Overall</td>
<td align="right">66</td>
<td align="left">log_linear</td>
<td align="right">0.7039</td>
<td align="right">-0.0280</td>
<td align="right">-110.7</td>
<td align="right">0.405</td>
</tr>
</tbody>
</table>
</div>
<div id="functional-form-comparison-fitted-equations"
class="section level2">
<h2>12) Functional Form Comparison: Fitted Equations</h2>
<p>For each response the three candidate decay functions are fit to
all-species-pooled pairwise data. The table reports the explicit fitted
equations, AIC, 394AIC (relative to best model per response), and
non-linear R0b2; the plot overlays all three curves on the raw
scatter.</p>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available.\n&quot;)
} else {
  resp_vars  &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
  resp_names &lt;- c(&quot;DDT family&quot;, &quot;PCP / PCB proxy&quot;,
                  &quot;Isotope (\u03b413C + \u03b415N)&quot;, &quot;Overall multivariate&quot;)

  eq_rows &lt;- do.call(rbind, lapply(seq_along(resp_vars), function(ii) {
    v  &lt;- resp_vars[ii]
    x  &lt;- pair_real$distance_km
    y  &lt;- pair_real[[v]]
    ok &lt;- is.finite(x) &amp; is.finite(y)
    x  &lt;- x[ok]; y &lt;- y[ok]

    fits &lt;- fit_decay_models(x, y)
    tab  &lt;- fits$table

    r2_nls &lt;- function(fit_obj, yhat_fn) {
      if (inherits(fit_obj, &quot;try-error&quot;)) return(NA_real_)
      tryCatch({
        yhat &lt;- yhat_fn(coef(fit_obj))
        1 - sum((y - yhat)^2) / sum((y - mean(y))^2)
      }, error = function(e) NA_real_)
    }

    cl     &lt;- coef(fits$models$loglin)
    ll_r2  &lt;- summary(fits$models$loglin)$r.squared

    build_row &lt;- function(model_nm, eq_str, aic_val, r2_val) {
      data.frame(Response = resp_names[ii], Model = model_nm,
                 Equation = eq_str,
                 AIC  = round(aic_val, 1),
                 R2   = round(r2_val,  3),
                 stringsAsFactors = FALSE)
    }

    rows &lt;- list()
    if (!inherits(fits$models$exp, &quot;try-error&quot;)) {
      ce &lt;- coef(fits$models$exp)
      rows[[&quot;exp&quot;]] &lt;- build_row(
        &quot;Exponential&quot;,
        sprintf(&quot;sim = %.4f x exp(-%.2e x d)&quot;, ce[1], ce[2]),
        tab$AIC[tab$model == &quot;exponential&quot;],
        r2_nls(fits$models$exp, function(co) co[1] * exp(-co[2] * x)))
    }
    if (!inherits(fits$models$pow, &quot;try-error&quot;)) {
      cp &lt;- coef(fits$models$pow)
      rows[[&quot;pow&quot;]] &lt;- build_row(
        &quot;Power-law&quot;,
        sprintf(&quot;sim = %.4f x (d+1)^(-%.4f)&quot;, cp[1], cp[2]),
        tab$AIC[tab$model == &quot;power_law&quot;],
        r2_nls(fits$models$pow, function(co) co[1] * (x + 1)^(-co[2])))
    }
    rows[[&quot;ll&quot;]] &lt;- build_row(
      &quot;Log-linear&quot;,
      sprintf(&quot;sim = %.4f + (%.4f) x log(d+1)&quot;, cl[1], cl[2]),
      tab$AIC[tab$model == &quot;log_linear&quot;],
      ll_r2)

    rows_df           &lt;- do.call(rbind, rows)
    best_aic          &lt;- min(rows_df$AIC, na.rm = TRUE)
    rows_df$Delta_AIC &lt;- round(rows_df$AIC - best_aic, 1)
    rows_df$Best      &lt;- ifelse(rows_df$Delta_AIC == 0, &quot;*&quot;, &quot;&quot;)
    rows_df
  }))

  print(knitr::kable(
    eq_rows[, c(&quot;Response&quot;, &quot;Model&quot;, &quot;Equation&quot;, &quot;AIC&quot;, &quot;Delta_AIC&quot;, &quot;R2&quot;, &quot;Best&quot;)],
    row.names = FALSE,
    col.names = c(&quot;Response&quot;, &quot;Model&quot;, &quot;Fitted equation&quot;, &quot;AIC&quot;, &quot;\u0394AIC&quot;, &quot;R\u00b2&quot;, &quot;Best&quot;),
    caption = paste(&quot;Table 2. Fitted equations for each functional form (all species pooled).&quot;,
                    &quot;\u0394AIC relative to best model per response. * = best supported functional form.&quot;)
  ))
  cat(&quot;\n&quot;)
}</code></pre>
<table>
<caption>Table 2. Fitted equations for each functional form (all species
pooled). ΔAIC relative to best model per response. * = best supported
functional form.</caption>
<colgroup>
<col width="22%" />
<col width="12%" />
<col width="37%" />
<col width="9%" />
<col width="7%" />
<col width="6%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="left">Model</th>
<th align="left">Fitted equation</th>
<th align="right">AIC</th>
<th align="right">ΔAIC</th>
<th align="right">R²</th>
<th align="left">Best</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DDT family</td>
<td align="left">Exponential</td>
<td align="left">sim = 0.6457 x exp(-2.54e-04 x d)</td>
<td align="right">6488.3</td>
<td align="right">0.0</td>
<td align="right">0.092</td>
<td align="left">*</td>
</tr>
<tr class="even">
<td align="left">DDT family</td>
<td align="left">Power-law</td>
<td align="left">sim = 0.6015 x (d+1)^(-0.0307)</td>
<td align="right">8317.6</td>
<td align="right">1829.3</td>
<td align="right">0.018</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">DDT family</td>
<td align="left">Log-linear</td>
<td align="left">sim = 0.6109 + (-0.0182) x log(d+1)</td>
<td align="right">8272.6</td>
<td align="right">1784.3</td>
<td align="right">0.020</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">PCP / PCB proxy</td>
<td align="left">Exponential</td>
<td align="left">sim = 0.5762 x exp(-1.50e-04 x d)</td>
<td align="right">7994.1</td>
<td align="right">0.0</td>
<td align="right">0.030</td>
<td align="left">*</td>
</tr>
<tr class="odd">
<td align="left">PCP / PCB proxy</td>
<td align="left">Power-law</td>
<td align="left">sim = 0.5406 x (d+1)^(-0.0149)</td>
<td align="right">8618.9</td>
<td align="right">624.8</td>
<td align="right">0.004</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">PCP / PCB proxy</td>
<td align="left">Log-linear</td>
<td align="left">sim = 0.5437 + (-0.0082) x log(d+1)</td>
<td align="right">8612.7</td>
<td align="right">618.6</td>
<td align="right">0.004</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Isotope (δ13C + δ15N)</td>
<td align="left">Exponential</td>
<td align="left">sim = 0.3384 x exp(-2.65e-04 x d)</td>
<td align="right">-8200.1</td>
<td align="right">474.0</td>
<td align="right">0.042</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Isotope (δ13C + δ15N)</td>
<td align="left">Power-law</td>
<td align="left">sim = 0.4015 x (d+1)^(-0.0732)</td>
<td align="right">-8660.9</td>
<td align="right">13.2</td>
<td align="right">0.061</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Isotope (δ13C + δ15N)</td>
<td align="left">Log-linear</td>
<td align="left">sim = 0.4004 + (-0.0228) x log(d+1)</td>
<td align="right">-8674.1</td>
<td align="right">0.0</td>
<td align="right">0.062</td>
<td align="left">*</td>
</tr>
<tr class="even">
<td align="left">Overall multivariate</td>
<td align="left">Exponential</td>
<td align="left">sim = 0.5192 x exp(-2.14e-04 x d)</td>
<td align="right">-14430.8</td>
<td align="right">0.0</td>
<td align="right">0.104</td>
<td align="left">*</td>
</tr>
<tr class="odd">
<td align="left">Overall multivariate</td>
<td align="left">Power-law</td>
<td align="left">sim = 0.5129 x (d+1)^(-0.0339)</td>
<td align="right">-12729.3</td>
<td align="right">1701.5</td>
<td align="right">0.036</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Overall multivariate</td>
<td align="left">Log-linear</td>
<td align="left">sim = 0.5183 + (-0.0164) x log(d+1)</td>
<td align="right">-12791.0</td>
<td align="right">1639.8</td>
<td align="right">0.039</td>
<td align="left"></td>
</tr>
</tbody>
</table>
<pre class="r"><code>if (exists(&quot;pair_real&quot;)) {
  resp_vars  &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
  resp_names &lt;- c(&quot;DDT family&quot;, &quot;PCP / PCB proxy&quot;,
                  &quot;Isotope (d13C + d15N)&quot;, &quot;Overall multivariate&quot;)

  par(mfrow = c(2, 2), mar = c(4.5, 4.5, 3.5, 1.5))

  for (ii in seq_along(resp_vars)) {
    v  &lt;- resp_vars[ii]
    x  &lt;- pair_real$distance_km
    y  &lt;- pair_real[[v]]
    ok &lt;- is.finite(x) &amp; is.finite(y)
    x  &lt;- x[ok]; y &lt;- y[ok]

    plot(x, y, pch = 16, cex = 0.30, col = rgb(0, 0, 0, 0.08),
         xlab = &quot;Geographic distance (km)&quot;, ylab = &quot;Chemical similarity&quot;,
         main = resp_names[ii])

    dseq &lt;- seq(0.5, max(x), length.out = 500)
    fits &lt;- fit_decay_models(x, y)
    tab  &lt;- fits$table

    leg_txt &lt;- character(0); leg_col &lt;- character(0)
    leg_lty &lt;- integer(0);   leg_lwd &lt;- numeric(0)

    if (!inherits(fits$models$exp, &quot;try-error&quot;)) {
      ce    &lt;- coef(fits$models$exp)
      lines(dseq, ce[1] * exp(-ce[2] * dseq), col = &quot;firebrick&quot;, lwd = 2.5, lty = 1)
      aic_e &lt;- round(tab$AIC[tab$model == &quot;exponential&quot;], 0)
      leg_txt &lt;- c(leg_txt, sprintf(&quot;Exp: %.3f*e^(-%.1e*d)  [AIC=%s]&quot;,   ce[1], ce[2], aic_e))
      leg_col &lt;- c(leg_col, &quot;firebrick&quot;);   leg_lty &lt;- c(leg_lty, 1); leg_lwd &lt;- c(leg_lwd, 2.5)
    }
    if (!inherits(fits$models$pow, &quot;try-error&quot;)) {
      cp    &lt;- coef(fits$models$pow)
      lines(dseq, cp[1] * (dseq + 1)^(-cp[2]), col = &quot;darkorange3&quot;, lwd = 2.5, lty = 2)
      aic_p &lt;- round(tab$AIC[tab$model == &quot;power_law&quot;], 0)
      leg_txt &lt;- c(leg_txt, sprintf(&quot;Power: %.3f*(d+1)^(-%.3f)  [AIC=%s]&quot;, cp[1], cp[2], aic_p))
      leg_col &lt;- c(leg_col, &quot;darkorange3&quot;); leg_lty &lt;- c(leg_lty, 2); leg_lwd &lt;- c(leg_lwd, 2.5)
    }
    cl    &lt;- coef(fits$models$loglin)
    lines(dseq, cl[1] + cl[2] * log(dseq + 1), col = &quot;steelblue4&quot;, lwd = 2.5, lty = 3)
    aic_l &lt;- round(tab$AIC[tab$model == &quot;log_linear&quot;], 0)
    leg_txt &lt;- c(leg_txt, sprintf(&quot;Log-lin: %.3f + %.3f*log(d+1)  [AIC=%s]&quot;, cl[1], cl[2], aic_l))
    leg_col &lt;- c(leg_col, &quot;steelblue4&quot;); leg_lty &lt;- c(leg_lty, 3); leg_lwd &lt;- c(leg_lwd, 2.5)

    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.62,
           legend = leg_txt, col = leg_col, lty = leg_lty, lwd = leg_lwd)
  }
}</code></pre>
<div class="figure">
<img src="outputs/figures/fitted-curves-plot-1.png" alt="Fitted distance-decay curves: exponential (red, solid), power-law (orange, dashed), log-linear (blue, dotted). Legend shows fitted equation and AIC for each form." width="1344" />
<p class="caption">
Fitted distance-decay curves: exponential (red, solid), power-law
(orange, dashed), log-linear (blue, dotted). Legend shows fitted
equation and AIC for each form.
</p>
</div>
</div>
<div id="interpretation-and-discussion" class="section level2">
<h2>13) Interpretation and Discussion</h2>
<div id="overview-1" class="section level3">
<h3>Overview</h3>
<p>This analysis characterised spatial distance-decay in chemical
similarity across 23220 pairwise comparisons drawn from seabird tissue
samples collected across Alaskan and North Pacific geographic areas.
Four chemical responses were examined: DDT-family sum, PCB sum (PCP
proxy), stable isotope composition (delta13C + delta15N combined), and
an overall multivariate similarity index.</p>
</div>
<div id="ddt-strong-exponentially-structured-spatial-decay"
class="section level3">
<h3>DDT: Strong, Exponentially Structured Spatial Decay</h3>
<p>DDT-family similarity showed the strongest and most spatially
structured distance-decay of any response (observed log-linear slope =
-0.0182, null mean = -0.0024, p &lt; 0.002). The <strong>exponential
model</strong> substantially outperformed power-law and log-linear
alternatives (ΔAIC &gt; 1784), with the fitted form:</p>
<blockquote>
<p><em>sim</em> = 0.6457 × exp(−2.54 × 10⁻⁴ × <em>d</em>)</p>
</blockquote>
<p>This implies rapid initial similarity loss at short distances —
consistent with point-source pollution that attenuates with distance
from coastal urbanisation and agricultural watersheds. Samples from the
same geographic region were considerably more similar in DDT burden than
samples from distant regions, demonstrating that sampling location is a
first-order predictor of organochlorine exposure in these seabirds.</p>
</div>
<div id="pcp-pcb-weaker-but-statistically-significant-decay"
class="section level3">
<h3>PCP / PCB: Weaker but Statistically Significant Decay</h3>
<p>PCB-based similarity showed a weaker signal (slope = -0.0082, null =
0.0022, p &lt; 0.002), suggesting that PCB contamination is more
spatially diffuse. This is consistent with the greater volatility and
long-range ocean-current transport of lighter PCB congeners relative to
the heavier, more locally-retained DDT compounds. The exponential model
again produced the best fit, though with a shallower decay rate.</p>
</div>
<div id="isotopes-log-linear-decay-reflecting-foraging-area-structure"
class="section level3">
<h3>Isotopes: Log-linear Decay Reflecting Foraging Area Structure</h3>
<p>δ¹³C + δ¹⁵N similarity followed a <strong>log-linear</strong> decay
most closely (best AIC = −8674, vs. −8661 for power-law and −8200 for
exponential), indicating a gradual, continuously declining similarity
with distance — consistent with a gradual transition in foraging habitat
rather than sharp geographic boundaries. The observed slope (-0.0228)
was significantly more negative than the spatially-constrained null
(-0.017), confirming that isotopic signatures track broad-scale foraging
zones.</p>
</div>
<div id="overall-multivariate-similarity" class="section level3">
<h3>Overall Multivariate Similarity</h3>
<p>The four-variable pooled similarity index (slope = -0.0164)
integrates contaminant and isotopic signals and recovers the strongest
model support (best AIC = −14,431 for exponential), reflecting that
multivariate distance-decay is more coherently structured than any
single variable alone.</p>
</div>
<div id="species-level-variation" class="section level3">
<h3>Species-Level Variation</h3>
<p><em>Uria aalge</em> and <em>Uria lomvia</em> contribute the majority
of within-species pairs (&gt; 12,500 and &gt; 5,500 respectively). Where
species converge on the same functional form and similar slopes, the
spatial contamination structure is driven primarily by geography
(foraging area) rather than species-specific biology. Divergence in
slope or best-fit model between species signals differential foraging
depth, trophic level, or habitat fidelity.</p>
</div>
<div id="model-selection-summary" class="section level3">
<h3>Model Selection Summary</h3>
<table>
<colgroup>
<col width="33%" />
<col width="33%" />
<col width="33%" />
</colgroup>
<thead>
<tr class="header">
<th>Response</th>
<th>Best functional form</th>
<th>Biological interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DDT</td>
<td>Exponential (ΔAIC &gt; 1784 over power-law)</td>
<td>Localised point-source with distance attenuation</td>
</tr>
<tr class="even">
<td>PCP/PCB</td>
<td>Exponential (shallower decay)</td>
<td>Diffuse atmosphere/ocean-current redistribution</td>
</tr>
<tr class="odd">
<td>Isotope</td>
<td>Log-linear</td>
<td>Gradual foraging gradient across latitude</td>
</tr>
<tr class="even">
<td>Overall</td>
<td>Exponential</td>
<td>Dominated by spatially structured DDT signal</td>
</tr>
</tbody>
</table>
</div>
<div id="limitations" class="section level3">
<h3>Limitations</h3>
<ul>
<li><strong>Spatial confounding</strong>: samples cluster by geographic
area; within-area pairs have distance = 0, anchoring high-similarity
values at <em>d</em> = 0.</li>
<li><strong>Non-independence</strong>: <em>n(n−1)/2</em> pairwise
comparisons are not independent — the null model permutation test
accounts for this partially.</li>
<li><strong>Unit harmonisation</strong>: DDT and PCB values retain units
from the modal unit per analyte group; cross-study mismatches would
inflate apparent dissimilarity.</li>
<li><strong>Missing predictive covariates</strong>: oceanographic
variables (SST, chlorophyll, bathymetry), diet, age, and sex are not
included but are essential for fuller mechanistic models.</li>
</ul>
<hr />
</div>
</div>
<div id="predictive-modeling-extensions" class="section level2">
<h2>14) Predictive Modeling Extensions</h2>
<div id="what-does-a-contamination-modeler-need" class="section level3">
<h3>What Does a Contamination Modeler Need?</h3>
<p>A researcher interested in predicting contamination at unsampled
sites or future time points would typically seek:</p>
<ol style="list-style-type: decimal">
<li><strong>Spatial autocorrelation structure</strong> (variogram /
distance-decay) — <em>done above</em> — defines the range at which
samples are spatially informative.</li>
<li><strong>Kriging or spatial interpolation</strong> — predicts
concentration at unsampled coordinates weighted by the empirical
variogram.</li>
<li><strong>GAM / GLMM spatial prediction</strong> — models
concentration as a smooth function of latitude, longitude, species, and
year; allows extrapolation.</li>
<li><strong>Spatial cross-validation</strong> — leave-one-area-out
(LOAO) or block holdout CV gives unbiased prediction error; standard
k-fold CV is anti-conservative for spatially autocorrelated data.</li>
<li><strong>Temporal trend modeling</strong> — tests whether
concentrations are declining (regulation effect) or increasing (new
sources).</li>
<li><strong>Environmental covariate linkage</strong> — SST, chlorophyll,
bathymetry as predictors for transfer to climate scenarios.</li>
</ol>
<p>Sections 14A–14C implement items 3, 4, and 5 using the
individual-level ZD Stamp sample data.</p>
</div>
<div id="a.-gam-spatial-prediction-ddt-concentration-surface"
class="section level3">
<h3>14A. GAM Spatial Prediction: DDT Concentration Surface</h3>
<p>A generalised additive model (GAM) with a 2-D thin-plate spline over
longitude and latitude is fitted to log(DDT + 1). Species is included as
a random effect to absorb inter-species baseline differences. The model
is then projected onto a prediction grid to map the estimated DDT
surface and its uncertainty.</p>
<pre class="r"><code>if (!exists(&quot;real_dat&quot;) || nrow(real_dat) &lt; 20) {
  cat(&quot;real_dat not available or too small for spatial GAM.\n&quot;)
} else {
  if (!requireNamespace(&quot;mgcv&quot;, quietly = TRUE))
    install.packages(&quot;mgcv&quot;, repos = &quot;https://cran.r-project.org/&quot;)
  library(mgcv)

  gdat &lt;- real_dat[
    is.finite(real_dat$DDT_real) &amp;
    is.finite(real_dat$LATITUDE) &amp;
    is.finite(real_dat$LONGITUDE), ]
  gdat$logDDT  &lt;- log1p(gdat$DDT_real)
  gdat$SPECIES &lt;- as.factor(gdat$SPECIES)
  k_sp &lt;- min(20, nrow(gdat) - 5)

  gm &lt;- tryCatch({
    if (length(levels(gdat$SPECIES)) &gt; 1) {
      gam(logDDT ~ s(LONGITUDE, LATITUDE, k = k_sp) + s(SPECIES, bs = &quot;re&quot;),
          data = gdat, method = &quot;REML&quot;)
    } else {
      gam(logDDT ~ s(LONGITUDE, LATITUDE, k = k_sp),
          data = gdat, method = &quot;REML&quot;)
    }
  }, error = function(e) { message(&quot;GAM failed: &quot;, e$message); NULL })

  if (!is.null(gm)) {
    gm_summ &lt;- summary(gm)
    cat(sprintf(
      &quot;**GAM deviance explained: %.1f%%**  |  R\u00b2 (adj.) = %.3f  |  n = %d\n\n&quot;,
      gm_summ$dev.expl * 100, gm_summ$r.sq, nrow(gdat)))

    lon_seq &lt;- seq(min(gdat$LONGITUDE) - 0.5, max(gdat$LONGITUDE) + 0.5, length.out = 60)
    lat_seq &lt;- seq(min(gdat$LATITUDE)  - 0.5, max(gdat$LATITUDE)  + 0.5, length.out = 60)
    grid_df &lt;- expand.grid(LONGITUDE = lon_seq, LATITUDE = lat_seq)
    modal_sp &lt;- names(sort(table(as.character(gdat$SPECIES)), decreasing = TRUE))[1]
    grid_df$SPECIES &lt;- factor(modal_sp, levels = levels(gdat$SPECIES))

    pred_out &lt;- tryCatch(
      predict(gm, newdata = grid_df, type = &quot;response&quot;, se.fit = TRUE),
      error = function(e) NULL)

    if (!is.null(pred_out)) {
      grid_df$pred_logDDT &lt;- pred_out$fit
      grid_df$se_logDDT   &lt;- pred_out$se.fit
      write.csv(grid_df, file.path(out_dir, &quot;gam_predicted_ddt_surface.csv&quot;),
                row.names = FALSE)

      par(mfrow = c(1, 2), mar = c(4, 4, 3, 2))

      mat_pred &lt;- matrix(grid_df$pred_logDDT, nrow = length(lon_seq))
      image(lon_seq, lat_seq, mat_pred,
            col  = hcl.colors(64, &quot;YlOrRd&quot;, rev = FALSE),
            xlab = &quot;Longitude&quot;, ylab = &quot;Latitude&quot;,
            main = sprintf(&quot;Predicted log(DDT+1)\n(%s, GAM spatial smooth)&quot;, modal_sp))
      points(gdat$LONGITUDE, gdat$LATITUDE, pch = 21, cex = 0.8,
             bg = &quot;white&quot;, col = &quot;black&quot;, lwd = 0.8)
      contour(lon_seq, lat_seq, mat_pred, add = TRUE,
              col = grey(0.3), lwd = 0.5, nlevels = 6)

      mat_se &lt;- matrix(grid_df$se_logDDT, nrow = length(lon_seq))
      image(lon_seq, lat_seq, mat_se,
            col  = hcl.colors(64, &quot;Blues 3&quot;, rev = TRUE),
            xlab = &quot;Longitude&quot;, ylab = &quot;Latitude&quot;,
            main = &quot;Prediction uncertainty (SE)\nHigher = fewer data nearby&quot;)
      points(gdat$LONGITUDE, gdat$LATITUDE, pch = 21, cex = 0.8,
             bg = &quot;white&quot;, col = &quot;black&quot;, lwd = 0.8)
    }
  }
}</code></pre>
<p><strong>GAM deviance explained: 70.7%</strong> | R² (adj.) = 0.686 |
n = 216</p>
<p><img src="outputs/figures/gam-spatial-1.png" width="1056" /></p>
</div>
<div id="b.-temporal-trend-analysis" class="section level3">
<h3>14B. Temporal Trend Analysis</h3>
<pre class="r"><code>if (!exists(&quot;real_dat&quot;)) {
  cat(&quot;real_dat not available.\n&quot;)
} else {
  tdat &lt;- real_dat[
    is.finite(real_dat$DDT_real) &amp;
    is.finite(real_dat$PCP_or_PCB) &amp;
    is.finite(real_dat$COLLECTION_YEAR), ]

  if (nrow(tdat) &lt; 10 || length(unique(tdat$COLLECTION_YEAR)) &lt; 3) {
    cat(&quot;Insufficient temporal variation for trend analysis.\n&quot;)
  } else {
    tdat$logDDT &lt;- log1p(tdat$DDT_real)
    tdat$logPCP &lt;- log1p(tdat$PCP_or_PCB)

    lm_ddt &lt;- summary(lm(logDDT ~ COLLECTION_YEAR, data = tdat))
    lm_pcp &lt;- summary(lm(logPCP ~ COLLECTION_YEAR, data = tdat))

    par(mfrow = c(1, 2), mar = c(4, 4, 3, 1))

    plot(tdat$COLLECTION_YEAR, tdat$logDDT,
         pch = 16, cex = 0.55, col = adjustcolor(&quot;firebrick&quot;, 0.45),
         xlab = &quot;Collection year&quot;, ylab = &quot;log(DDT + 1)&quot;,
         main = &quot;DDT: Temporal Trend&quot;)
    abline(lm(logDDT ~ COLLECTION_YEAR, data = tdat), col = &quot;firebrick&quot;, lwd = 2.5)
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.8,
           legend = c(sprintf(&quot;slope = %.4f/yr&quot;, lm_ddt$coefficients[2, 1]),
                      sprintf(&quot;p = %.3f&quot;,         lm_ddt$coefficients[2, 4]),
                      sprintf(&quot;R\u00b2 = %.3f&quot;,     lm_ddt$r.squared)))

    plot(tdat$COLLECTION_YEAR, tdat$logPCP,
         pch = 16, cex = 0.55, col = adjustcolor(&quot;darkorange3&quot;, 0.45),
         xlab = &quot;Collection year&quot;, ylab = &quot;log(PCP/PCB + 1)&quot;,
         main = &quot;PCP/PCB: Temporal Trend&quot;)
    abline(lm(logPCP ~ COLLECTION_YEAR, data = tdat), col = &quot;darkorange3&quot;, lwd = 2.5)
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.8,
           legend = c(sprintf(&quot;slope = %.4f/yr&quot;, lm_pcp$coefficients[2, 1]),
                      sprintf(&quot;p = %.3f&quot;,         lm_pcp$coefficients[2, 4]),
                      sprintf(&quot;R\u00b2 = %.3f&quot;,     lm_pcp$r.squared)))

    cat(sprintf(&quot;- **DDT**: slope = %.4f log-units/yr, R\u00b2 = %.3f, p = %.3f\n&quot;,
                lm_ddt$coefficients[2, 1], lm_ddt$r.squared, lm_ddt$coefficients[2, 4]))
    cat(sprintf(&quot;- **PCP/PCB**: slope = %.4f log-units/yr, R\u00b2 = %.3f, p = %.3f\n&quot;,
                lm_pcp$coefficients[2, 1], lm_pcp$r.squared, lm_pcp$coefficients[2, 4]))
  }
}</code></pre>
<p><img src="outputs/figures/temporal-trend-1.png" width="1056" />-
<strong>DDT</strong>: slope = -0.1014 log-units/yr, R² = 0.152, p =
0.000 - <strong>PCP/PCB</strong>: slope = -0.0753 log-units/yr, R² =
0.086, p = 0.000</p>
</div>
<div id="c.-spatial-cross-validation-leave-one-area-out-gam-ddt"
class="section level3">
<h3>14C. Spatial Cross-Validation (Leave-One-Area-Out, GAM DDT)</h3>
<p>Each geographic area is withheld in turn; a GAM is fit on the
remaining areas and used to predict log(DDT+1) in the withheld area.
RMSE and MAE are on the log(DDT+1) scale.</p>
<pre class="r"><code>if (!exists(&quot;real_dat&quot;) || nrow(real_dat) &lt; 20) {
  cat(&quot;real_dat not available.\n&quot;)
} else {
  if (!requireNamespace(&quot;mgcv&quot;, quietly = TRUE)) library(mgcv)

  gdat_cv &lt;- real_dat[
    is.finite(real_dat$DDT_real) &amp;
    is.finite(real_dat$LATITUDE) &amp;
    is.finite(real_dat$LONGITUDE), ]
  gdat_cv$logDDT &lt;- log1p(gdat_cv$DDT_real)

  areas_cv &lt;- unique(gdat_cv$GEOGRAPHIC_AREA)
  areas_cv &lt;- areas_cv[!is.na(areas_cv) &amp; nchar(trimws(areas_cv)) &gt; 0]

  if (length(areas_cv) &lt; 3) {
    cat(&quot;Fewer than 3 geographic areas — skipping leave-one-area-out CV.\n&quot;)
  } else {
    cv_rows &lt;- lapply(areas_cv, function(a) {
      train &lt;- gdat_cv[gdat_cv$GEOGRAPHIC_AREA != a, ]
      test  &lt;- gdat_cv[gdat_cv$GEOGRAPHIC_AREA == a, ]
      if (nrow(train) &lt; 15 || nrow(test) &lt; 2) return(NULL)
      k_cv &lt;- min(15, nrow(train) - 5)
      m_cv &lt;- tryCatch(
        gam(logDDT ~ s(LONGITUDE, LATITUDE, k = k_cv),
            data = train, method = &quot;REML&quot;),
        error = function(e) NULL)
      if (is.null(m_cv)) return(NULL)
      pred_cv &lt;- tryCatch(
        predict(m_cv, newdata = test, type = &quot;response&quot;),
        error = function(e) NULL)
      if (is.null(pred_cv)) return(NULL)
      data.frame(
        Area   = a,
        N_test = nrow(test),
        RMSE   = round(sqrt(mean((test$logDDT - pred_cv)^2)), 3),
        MAE    = round(mean(abs(test$logDDT - pred_cv)), 3),
        stringsAsFactors = FALSE)
    })

    cv_tab &lt;- do.call(rbind, Filter(Negate(is.null), cv_rows))

    if (!is.null(cv_tab) &amp;&amp; nrow(cv_tab) &gt; 0) {
      mean_row &lt;- data.frame(
        Area   = &quot;**Mean across areas**&quot;, N_test = NA,
        RMSE   = round(mean(cv_tab$RMSE), 3),
        MAE    = round(mean(cv_tab$MAE),  3),
        stringsAsFactors = FALSE)
      cv_out &lt;- rbind(cv_tab, mean_row)
      write.csv(cv_out, file.path(out_dir, &quot;spatial_cv_loao_results.csv&quot;),
                row.names = FALSE)
      print(knitr::kable(cv_out, row.names = FALSE,
        col.names = c(&quot;Held-out area&quot;, &quot;N test&quot;,
                      &quot;RMSE (log-scale)&quot;, &quot;MAE (log-scale)&quot;),
        caption = paste(
          &quot;Table 3. Leave-one-area-out spatial cross-validation (DDT, GAM).&quot;,
          &quot;Each geographic area is withheld in turn;&quot;,
          &quot;the GAM is fit on the remaining areas and predictions are evaluated&quot;,
          &quot;on withheld samples. Errors on log(DDT+1) scale.&quot;)))
    }
  }
}</code></pre>
<table>
<caption>Table 3. Leave-one-area-out spatial cross-validation (DDT,
GAM). Each geographic area is withheld in turn; the GAM is fit on the
remaining areas and predictions are evaluated on withheld samples.
Errors on log(DDT+1) scale.</caption>
<thead>
<tr class="header">
<th align="left">Held-out area</th>
<th align="right">N test</th>
<th align="right">RMSE (log-scale)</th>
<th align="right">MAE (log-scale)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Chukchi Sea</td>
<td align="right">14</td>
<td align="right">0.637</td>
<td align="right">0.437</td>
</tr>
<tr class="even">
<td align="left">Bering Strait</td>
<td align="right">15</td>
<td align="right">0.476</td>
<td align="right">0.384</td>
</tr>
<tr class="odd">
<td align="left">Gulf of Alaska</td>
<td align="right">110</td>
<td align="right">3.838</td>
<td align="right">3.681</td>
</tr>
<tr class="even">
<td align="left">Aleutian Islands</td>
<td align="right">24</td>
<td align="right">0.362</td>
<td align="right">0.299</td>
</tr>
<tr class="odd">
<td align="left">Bering Sea, Norton Sound</td>
<td align="right">10</td>
<td align="right">0.998</td>
<td align="right">0.952</td>
</tr>
<tr class="even">
<td align="left"><strong>Mean across areas</strong></td>
<td align="right">NA</td>
<td align="right">1.262</td>
<td align="right">1.151</td>
</tr>
</tbody>
</table>
</div>
<div id="d.-recommended-next-steps-for-predictive-modeling"
class="section level3">
<h3>14D. Recommended Next Steps for Predictive Modeling</h3>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Priority</th>
<th>Method</th>
<th>Purpose</th>
<th>R package</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Empirical variogram</td>
<td>Quantify spatial autocorrelation range</td>
<td><code>gstat</code>, <code>sf</code></td>
</tr>
<tr class="even">
<td>2</td>
<td>Ordinary kriging</td>
<td>Unbiased interpolation to unsampled sites</td>
<td><code>gstat</code></td>
</tr>
<tr class="odd">
<td>3</td>
<td>GAM + oceanographic covariates</td>
<td>Mechanistic spatial prediction</td>
<td><code>mgcv</code></td>
</tr>
<tr class="even">
<td>4</td>
<td>Block spatial CV</td>
<td>Honest prediction error for autocorrelated data</td>
<td><code>blockCV</code></td>
</tr>
<tr class="odd">
<td>5</td>
<td>Random forest + spatial CV</td>
<td>Non-linear covariate effects</td>
<td><code>ranger</code> + <code>blockCV</code></td>
</tr>
<tr class="even">
<td>6</td>
<td>Mixed model: species + year random effects</td>
<td>Partition spatial vs. temporal vs. species variance</td>
<td><code>lme4</code> / <code>glmmTMB</code></td>
</tr>
<tr class="odd">
<td>7</td>
<td>Temporal ARMA on annual means</td>
<td>Trend and cycle detection</td>
<td><code>forecast</code></td>
</tr>
<tr class="even">
<td>8</td>
<td>Transfer to unmonitored taxa</td>
<td>Exposure prediction for new species/regions</td>
<td>GAM with species factor</td>
</tr>
</tbody>
</table>
<p>The distance-decay slopes estimated in this report directly
parameterise kriging variograms: for the exponential model the spatial
range <em>r</em> = 1/<em>b</em> (where <em>b</em> is the fitted decay
coefficient). For DDT, <em>b</em> ≈ 2.54 × 10⁻⁴ km⁻¹ gives <em>r</em> ≈
3,937 km, indicating that samples within roughly 4,000 km carry
meaningful shared spatial information and are suitable co-variates for
kriging.</p>
</div>
</div>
<div id="spatiotemporal-scaling-model-distance-time"
class="section level2">
<h2>15) Spatiotemporal Scaling Model (Distance + Time)</h2>
<p>This section fits a joint scaling model for contaminant similarity as
a function of both geographic distance and collection-year
separation:</p>
<p><span class="math display">\[
    ext{sim}_{ij} = \beta_0 + \beta_1\log(d_{ij}+1) + \beta_2\log(\Delta
t_{ij}+1) + \beta_3\log(d_{ij}+1)\log(\Delta t_{ij}+1) +
\varepsilon_{ij}
\]</span></p>
<p>where <span class="math inline">\(d_{ij}\)</span> is pairwise
geographic distance (km) and <span class="math inline">\(\Delta
t_{ij}\)</span> is pairwise absolute time lag (years).</p>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping spatiotemporal scaling model.\n&quot;)
} else {
  if (!&quot;time_lag_years&quot; %in% names(pair_real)) {
    cat(&quot;time_lag_years missing in pair_real — rerun real-data analysis chunk first.\n&quot;)
  } else {
    resp_vars  &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
    resp_names &lt;- c(&quot;DDT&quot;, &quot;PCP/PCB&quot;, &quot;Isotope&quot;, &quot;Overall&quot;)

    fit_st &lt;- function(df, yvar) {
      ok &lt;- is.finite(df[[yvar]]) &amp; is.finite(df$distance_km) &amp; is.finite(df$time_lag_years)
      d  &lt;- df$distance_km[ok]
      t  &lt;- df$time_lag_years[ok]
      y  &lt;- df[[yvar]][ok]
      if (length(y) &lt; 30 || length(unique(t)) &lt; 2) return(NULL)

      st_df &lt;- data.frame(
        y = y,
        log_dist = log(d + 1),
        log_time = log(t + 1)
      )

      m_add &lt;- lm(y ~ log_dist + log_time, data = st_df)
      m_int &lt;- lm(y ~ log_dist * log_time, data = st_df)

      b_int &lt;- coef(summary(m_int))
      get_coef &lt;- function(term, col) if (term %in% rownames(b_int)) b_int[term, col] else NA_real_

      data.frame(
        response = yvar,
        n_pairs = nrow(st_df),
        dist_coef = coef(m_int)[&quot;log_dist&quot;],
        time_coef = coef(m_int)[&quot;log_time&quot;],
        interaction_coef = coef(m_int)[&quot;log_dist:log_time&quot;],
        p_dist = get_coef(&quot;log_dist&quot;, &quot;Pr(&gt;|t|)&quot;),
        p_time = get_coef(&quot;log_time&quot;, &quot;Pr(&gt;|t|)&quot;),
        p_interaction = get_coef(&quot;log_dist:log_time&quot;, &quot;Pr(&gt;|t|)&quot;),
        R2_additive = summary(m_add)$r.squared,
        R2_interaction = summary(m_int)$r.squared,
        AIC_additive = AIC(m_add),
        AIC_interaction = AIC(m_int),
        delta_AIC_int_vs_add = AIC(m_add) - AIC(m_int),
        stringsAsFactors = FALSE
      )
    }

    st_out &lt;- do.call(rbind, lapply(resp_vars, function(v) fit_st(pair_real, v)))

    if (!is.null(st_out) &amp;&amp; nrow(st_out) &gt; 0) {
      st_out$response &lt;- resp_names[match(st_out$response, resp_vars)]
      num_cols &lt;- setdiff(names(st_out), c(&quot;response&quot;))
      st_out[num_cols] &lt;- lapply(st_out[num_cols], function(x) round(x, 4))
      write.csv(st_out, file.path(out_dir, &quot;spatiotemporal_scaling_model_summary.csv&quot;), row.names = FALSE)

      print(knitr::kable(
        st_out,
        row.names = FALSE,
        col.names = c(
          &quot;Response&quot;, &quot;N pairs&quot;, &quot;Beta distance&quot;, &quot;Beta time&quot;, &quot;Beta distance x time&quot;,
          &quot;p distance&quot;, &quot;p time&quot;, &quot;p interaction&quot;, &quot;R2 additive&quot;, &quot;R2 interaction&quot;,
          &quot;AIC additive&quot;, &quot;AIC interaction&quot;, &quot;Delta AIC (int-add)&quot;
        ),
        caption = paste(
          &quot;Table 4. Spatiotemporal scaling models.&quot;,
          &quot;Positive Delta AIC indicates interaction model support over additive model.&quot;
        )
      ))
    }
  }
}</code></pre>
<table>
<caption>Table 4. Spatiotemporal scaling models. Positive Delta AIC
indicates interaction model support over additive model.</caption>
<colgroup>
<col width="5%" />
<col width="4%" />
<col width="8%" />
<col width="5%" />
<col width="12%" />
<col width="6%" />
<col width="4%" />
<col width="8%" />
<col width="7%" />
<col width="8%" />
<col width="7%" />
<col width="9%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="right">N pairs</th>
<th align="right">Beta distance</th>
<th align="right">Beta time</th>
<th align="right">Beta distance x time</th>
<th align="right">p distance</th>
<th align="right">p time</th>
<th align="right">p interaction</th>
<th align="right">R2 additive</th>
<th align="right">R2 interaction</th>
<th align="right">AIC additive</th>
<th align="right">AIC interaction</th>
<th align="right">Delta AIC (int-add)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DDT</td>
<td align="right">23220</td>
<td align="right">-0.0263</td>
<td align="right">-0.0798</td>
<td align="right">0.0105</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0210</td>
<td align="right">0.0237</td>
<td align="right">8243.655</td>
<td align="right">8181.710</td>
<td align="right">61.9449</td>
</tr>
<tr class="even">
<td align="left">PCP/PCB</td>
<td align="right">23220</td>
<td align="right">-0.0180</td>
<td align="right">-0.0909</td>
<td align="right">0.0125</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0052</td>
<td align="right">0.0090</td>
<td align="right">8586.229</td>
<td align="right">8499.252</td>
<td align="right">86.9766</td>
</tr>
<tr class="odd">
<td align="left">Isotope</td>
<td align="right">23220</td>
<td align="right">-0.0248</td>
<td align="right">-0.0451</td>
<td align="right">0.0038</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0659</td>
<td align="right">0.0666</td>
<td align="right">-8780.928</td>
<td align="right">-8796.158</td>
<td align="right">15.2298</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="right">23220</td>
<td align="right">-0.0230</td>
<td align="right">-0.0719</td>
<td align="right">0.0089</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0.0426</td>
<td align="right">0.0473</td>
<td align="right">-12880.027</td>
<td align="right">-12992.713</td>
<td align="right">112.6863</td>
</tr>
</tbody>
</table>
<pre class="r"><code>if (exists(&quot;pair_real&quot;) &amp;&amp; &quot;time_lag_years&quot; %in% names(pair_real)) {
  resp_vars  &lt;- c(&quot;sim_DDT&quot;, &quot;sim_PCP_or_PCB&quot;, &quot;sim_isotope&quot;, &quot;sim_overall&quot;)
  resp_names &lt;- c(&quot;DDT&quot;, &quot;PCP/PCB&quot;, &quot;Isotope&quot;, &quot;Overall&quot;)

  q &lt;- quantile(pair_real$time_lag_years, probs = c(0, 1/3, 2/3, 1), na.rm = TRUE)
  q[1] &lt;- min(q[1], 0)
  pair_real$time_group &lt;- cut(
    pair_real$time_lag_years,
    breaks = unique(q),
    include.lowest = TRUE,
    labels = c(&quot;Low time lag&quot;, &quot;Mid time lag&quot;, &quot;High time lag&quot;)[seq_len(length(unique(q)) - 1)]
  )

  par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
  cols &lt;- c(&quot;steelblue3&quot;, &quot;darkorange3&quot;, &quot;firebrick3&quot;)

  for (ii in seq_along(resp_vars)) {
    v &lt;- resp_vars[ii]
    d &lt;- pair_real$distance_km
    y &lt;- pair_real[[v]]
    g &lt;- pair_real$time_group
    ok &lt;- is.finite(d) &amp; is.finite(y) &amp; !is.na(g)
    d &lt;- d[ok]; y &lt;- y[ok]; g &lt;- droplevels(g[ok])

    plot(d, y,
         pch = 16, cex = 0.30,
         col = adjustcolor(&quot;black&quot;, alpha.f = 0.10),
         xlab = &quot;Distance (km)&quot;, ylab = &quot;Similarity&quot;,
         main = paste(resp_names[ii], &quot;by time-lag tercile&quot;))

    dseq &lt;- seq(0.1, max(d), length.out = 300)
    levs &lt;- levels(g)
    for (jj in seq_along(levs)) {
      idx &lt;- g == levs[jj]
      if (sum(idx) &lt; 20) next
      m &lt;- lm(y[idx] ~ log(d[idx] + 1))
      a &lt;- coef(m)[1]; b &lt;- coef(m)[2]
      lines(dseq, a + b * log(dseq + 1), col = cols[jj], lwd = 2.5)
    }
    legend(&quot;topright&quot;, bty = &quot;n&quot;, cex = 0.75,
           legend = levels(g), col = cols[seq_along(levels(g))], lwd = 2.5)
  }
}</code></pre>
<p><img src="outputs/figures/spatiotemporal-visualization-1.png" width="1248" /></p>
</div>
<div id="b-dyadic-mixed-effects-spatiotemporal-model-blocked-cv"
class="section level2">
<h2>15B) Dyadic Mixed-Effects Spatiotemporal Model + Blocked CV</h2>
<p>To reduce pseudo-replication from pairwise expansion, this section
fits a dyadic mixed-effects model with crossed random effects for both
members of each pair (individual IDs, species, and geographic areas),
then evaluates prediction using leave-one-area-out blocked
cross-validation.</p>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping dyadic mixed-effects model.\n&quot;)
} else if (!all(c(&quot;time_lag_years&quot;, &quot;id_i&quot;, &quot;id_j&quot;, &quot;area_i&quot;, &quot;area_j&quot;, &quot;species_i&quot;, &quot;species_j&quot;) %in% names(pair_real))) {
  cat(&quot;Required pairwise fields not found — rerun real-data analysis chunk first.\n&quot;)
} else {
  if (!requireNamespace(&quot;lme4&quot;, quietly = TRUE)) {
    install.packages(&quot;lme4&quot;, repos = &quot;https://cran.r-project.org/&quot;)
  }
  library(lme4)

  fit_dyadic &lt;- function(df, yvar) {
    keep &lt;- is.finite(df[[yvar]]) &amp;
      is.finite(df$distance_km) &amp; is.finite(df$time_lag_years) &amp;
      !is.na(df$id_i) &amp; !is.na(df$id_j) &amp; !is.na(df$area_i) &amp; !is.na(df$area_j) &amp;
      !is.na(df$species_i) &amp; !is.na(df$species_j)

    dat &lt;- df[keep, c(yvar, &quot;distance_km&quot;, &quot;time_lag_years&quot;, &quot;id_i&quot;, &quot;id_j&quot;, &quot;area_i&quot;, &quot;area_j&quot;, &quot;species_i&quot;, &quot;species_j&quot;)]
    names(dat)[1] &lt;- &quot;y&quot;

    if (nrow(dat) &lt; 100) return(NULL)

    dat$log_dist &lt;- log(dat$distance_km + 1)
    dat$log_time &lt;- log(dat$time_lag_years + 1)

    dat$id_i &lt;- as.factor(dat$id_i)
    dat$id_j &lt;- as.factor(dat$id_j)
    dat$area_i &lt;- as.factor(dat$area_i)
    dat$area_j &lt;- as.factor(dat$area_j)
    dat$species_i &lt;- as.factor(dat$species_i)
    dat$species_j &lt;- as.factor(dat$species_j)

    ctrl &lt;- lmerControl(optimizer = &quot;bobyqa&quot;, optCtrl = list(maxfun = 1e5))

    full_formula &lt;- y ~ log_dist * log_time +
      (1 | id_i) + (1 | id_j) +
      (1 | species_i) + (1 | species_j) +
      (1 | area_i) + (1 | area_j)

    fallback_formula &lt;- y ~ log_dist * log_time +
      (1 | species_i) + (1 | species_j) +
      (1 | area_i) + (1 | area_j)

    mod &lt;- try(lmer(full_formula, data = dat, REML = FALSE, control = ctrl), silent = TRUE)
    model_type &lt;- &quot;full_dyadic&quot;
    if (inherits(mod, &quot;try-error&quot;)) {
      mod &lt;- try(lmer(fallback_formula, data = dat, REML = FALSE, control = ctrl), silent = TRUE)
      model_type &lt;- &quot;fallback_species_area&quot;
    }
    if (inherits(mod, &quot;try-error&quot;)) return(NULL)

    sm &lt;- summary(mod)
    cf &lt;- as.data.frame(sm$coefficients)
    cf$term &lt;- rownames(cf)

    get_cf &lt;- function(term, colname) {
      if (!(term %in% cf$term)) return(NA_real_)
      cf[cf$term == term, colname][1]
    }

    fixed_row &lt;- data.frame(
      response = yvar,
      model_type = model_type,
      n_pairs = nrow(dat),
      beta_dist = get_cf(&quot;log_dist&quot;, &quot;Estimate&quot;),
      beta_time = get_cf(&quot;log_time&quot;, &quot;Estimate&quot;),
      beta_dist_time = get_cf(&quot;log_dist:log_time&quot;, &quot;Estimate&quot;),
      se_dist = get_cf(&quot;log_dist&quot;, &quot;Std. Error&quot;),
      se_time = get_cf(&quot;log_time&quot;, &quot;Std. Error&quot;),
      se_dist_time = get_cf(&quot;log_dist:log_time&quot;, &quot;Std. Error&quot;),
      t_dist = get_cf(&quot;log_dist&quot;, &quot;t value&quot;),
      t_time = get_cf(&quot;log_time&quot;, &quot;t value&quot;),
      t_dist_time = get_cf(&quot;log_dist:log_time&quot;, &quot;t value&quot;),
      AIC = AIC(mod),
      stringsAsFactors = FALSE
    )

    list(model = mod, data = dat, fixed = fixed_row)
  }

  run_blocked_cv &lt;- function(dat, model_type, yvar) {
    areas &lt;- sort(unique(c(as.character(dat$area_i), as.character(dat$area_j))))
    areas &lt;- areas[!is.na(areas) &amp; nchar(trimws(areas)) &gt; 0]
    if (length(areas) &lt; 3) return(NULL)

    ctrl &lt;- lmerControl(optimizer = &quot;bobyqa&quot;, optCtrl = list(maxfun = 1e5))
    full_formula &lt;- y ~ log_dist * log_time +
      (1 | id_i) + (1 | id_j) +
      (1 | species_i) + (1 | species_j) +
      (1 | area_i) + (1 | area_j)
    fallback_formula &lt;- y ~ log_dist * log_time +
      (1 | species_i) + (1 | species_j) +
      (1 | area_i) + (1 | area_j)

    cv_rows &lt;- lapply(areas, function(a) {
      test_idx &lt;- as.character(dat$area_i) == a | as.character(dat$area_j) == a
      train &lt;- dat[!test_idx, ]
      test &lt;- dat[test_idx, ]
      if (nrow(train) &lt; 100 || nrow(test) &lt; 20) return(NULL)

      form &lt;- if (model_type == &quot;full_dyadic&quot;) full_formula else fallback_formula
      fit &lt;- try(lmer(form, data = train, REML = FALSE, control = ctrl), silent = TRUE)
      if (inherits(fit, &quot;try-error&quot;)) {
        fit &lt;- try(lmer(fallback_formula, data = train, REML = FALSE, control = ctrl), silent = TRUE)
      }
      if (inherits(fit, &quot;try-error&quot;)) return(NULL)

      pred &lt;- try(predict(fit, newdata = test, allow.new.levels = TRUE), silent = TRUE)
      if (inherits(pred, &quot;try-error&quot;)) return(NULL)

      obs &lt;- test$y
      rmse &lt;- sqrt(mean((obs - pred)^2, na.rm = TRUE))
      mae &lt;- mean(abs(obs - pred), na.rm = TRUE)
      r2 &lt;- if (length(unique(obs)) &gt; 1) cor(obs, pred, use = &quot;complete.obs&quot;)^2 else NA_real_

      data.frame(
        response = yvar,
        held_out_area = a,
        n_test = nrow(test),
        RMSE = rmse,
        MAE = mae,
        R2_pred = r2,
        stringsAsFactors = FALSE
      )
    })

    cv_tab &lt;- do.call(rbind, Filter(Negate(is.null), cv_rows))
    if (is.null(cv_tab) || nrow(cv_tab) == 0) return(NULL)
    mean_row &lt;- data.frame(
      response = yvar,
      held_out_area = &quot;Mean across held-out areas&quot;,
      n_test = NA,
      RMSE = mean(cv_tab$RMSE, na.rm = TRUE),
      MAE = mean(cv_tab$MAE, na.rm = TRUE),
      R2_pred = mean(cv_tab$R2_pred, na.rm = TRUE),
      stringsAsFactors = FALSE
    )
    rbind(cv_tab, mean_row)
  }

  targets &lt;- c(&quot;sim_overall&quot;, &quot;sim_DDT&quot;)
  fit_objs &lt;- lapply(targets, function(v) fit_dyadic(pair_real, v))
  names(fit_objs) &lt;- targets
  fit_objs &lt;- fit_objs[!vapply(fit_objs, is.null, logical(1))]

  if (length(fit_objs) == 0) {
    cat(&quot;Dyadic mixed-effects models failed or insufficient data.\n&quot;)
  } else {
    fixed_tab &lt;- do.call(rbind, lapply(fit_objs, function(x) x$fixed))
    fixed_tab$response &lt;- c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[fixed_tab$response]

    num_cols &lt;- setdiff(names(fixed_tab), c(&quot;response&quot;, &quot;model_type&quot;))
    fixed_tab[num_cols] &lt;- lapply(fixed_tab[num_cols], function(x) round(x, 4))

    write.csv(fixed_tab, file.path(out_dir, &quot;dyadic_mixed_model_fixed_effects.csv&quot;), row.names = FALSE)

    print(knitr::kable(
      fixed_tab,
      row.names = FALSE,
      col.names = c(
        &quot;Response&quot;, &quot;Model&quot;, &quot;N pairs&quot;,
        &quot;Beta distance&quot;, &quot;Beta time&quot;, &quot;Beta distance x time&quot;,
        &quot;SE dist&quot;, &quot;SE time&quot;, &quot;SE dist x time&quot;,
        &quot;t dist&quot;, &quot;t time&quot;, &quot;t dist x time&quot;, &quot;AIC&quot;
      ),
      caption = paste(
        &quot;Table 5. Dyadic mixed-effects spatiotemporal model fixed effects.&quot;,
        &quot;Crossed random effects account for pair-member, species, and area dependence.&quot;
      )
    ))

    cv_tabs &lt;- do.call(rbind, lapply(names(fit_objs), function(v) {
      out &lt;- run_blocked_cv(fit_objs[[v]]$data, fit_objs[[v]]$fixed$model_type[1], v)
      out
    }))

    if (!is.null(cv_tabs) &amp;&amp; nrow(cv_tabs) &gt; 0) {
      cv_tabs$response &lt;- c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[cv_tabs$response]
      num_cols &lt;- c(&quot;n_test&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;R2_pred&quot;)
      for (nc in num_cols) {
        if (nc %in% names(cv_tabs)) cv_tabs[[nc]] &lt;- round(cv_tabs[[nc]], 4)
      }

      write.csv(cv_tabs, file.path(out_dir, &quot;dyadic_mixed_model_blocked_cv.csv&quot;), row.names = FALSE)

      print(knitr::kable(
        cv_tabs,
        row.names = FALSE,
        col.names = c(&quot;Response&quot;, &quot;Held-out area&quot;, &quot;N test&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;Predictive R2&quot;),
        caption = paste(
          &quot;Table 6. Leave-one-area-out blocked cross-validation for dyadic mixed models.&quot;,
          &quot;Test rows include any pair touching the held-out area, reducing spatial leakage.&quot;
        )
      ))
    }
  }
}</code></pre>
<table style="width:100%;">
<caption>Table 5. Dyadic mixed-effects spatiotemporal model fixed
effects. Crossed random effects account for pair-member, species, and
area dependence.</caption>
<colgroup>
<col width="6%" />
<col width="8%" />
<col width="5%" />
<col width="9%" />
<col width="6%" />
<col width="14%" />
<col width="5%" />
<col width="5%" />
<col width="10%" />
<col width="6%" />
<col width="5%" />
<col width="9%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="left">Model</th>
<th align="right">N pairs</th>
<th align="right">Beta distance</th>
<th align="right">Beta time</th>
<th align="right">Beta distance x time</th>
<th align="right">SE dist</th>
<th align="right">SE time</th>
<th align="right">SE dist x time</th>
<th align="right">t dist</th>
<th align="right">t time</th>
<th align="right">t dist x time</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">full_dyadic</td>
<td align="right">23220</td>
<td align="right">-0.0269</td>
<td align="right">-0.0162</td>
<td align="right">3e-04</td>
<td align="right">7e-04</td>
<td align="right">0.0040</td>
<td align="right">6e-04</td>
<td align="right">-40.3590</td>
<td align="right">-4.0472</td>
<td align="right">0.4220</td>
<td align="right">-29166.859</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">full_dyadic</td>
<td align="right">23220</td>
<td align="right">-0.0389</td>
<td align="right">0.0053</td>
<td align="right">-7e-04</td>
<td align="right">1e-03</td>
<td align="right">0.0061</td>
<td align="right">9e-04</td>
<td align="right">-38.4652</td>
<td align="right">0.8707</td>
<td align="right">-0.6965</td>
<td align="right">-9800.313</td>
</tr>
</tbody>
</table>
<table style="width:100%;">
<caption>Table 6. Leave-one-area-out blocked cross-validation for dyadic
mixed models. Test rows include any pair touching the held-out area,
reducing spatial leakage.</caption>
<colgroup>
<col width="12%" />
<col width="38%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="19%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="left">Held-out area</th>
<th align="right">N test</th>
<th align="right">RMSE</th>
<th align="right">MAE</th>
<th align="right">Predictive R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Aleutian Islands</td>
<td align="right">4884</td>
<td align="right">0.1366</td>
<td align="right">0.1112</td>
<td align="right">0.4478</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="left">Bering Sea</td>
<td align="right">8342</td>
<td align="right">0.1415</td>
<td align="right">0.1123</td>
<td align="right">0.4320</td>
</tr>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Bering Sea, Norton Sound</td>
<td align="right">2105</td>
<td align="right">0.1336</td>
<td align="right">0.1109</td>
<td align="right">0.6107</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="left">Bering Strait</td>
<td align="right">3120</td>
<td align="right">0.1344</td>
<td align="right">0.1086</td>
<td align="right">0.4302</td>
</tr>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Chukchi Sea</td>
<td align="right">2919</td>
<td align="right">0.1445</td>
<td align="right">0.1156</td>
<td align="right">0.4709</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="left">Gulf of Alaska</td>
<td align="right">17655</td>
<td align="right">0.2153</td>
<td align="right">0.1742</td>
<td align="right">0.0396</td>
</tr>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Mean across held-out areas</td>
<td align="right">NA</td>
<td align="right">0.1510</td>
<td align="right">0.1221</td>
<td align="right">0.4052</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Aleutian Islands</td>
<td align="right">4884</td>
<td align="right">0.2057</td>
<td align="right">0.1636</td>
<td align="right">0.4957</td>
</tr>
<tr class="odd">
<td align="left">DDT</td>
<td align="left">Bering Sea</td>
<td align="right">8342</td>
<td align="right">0.2227</td>
<td align="right">0.1765</td>
<td align="right">0.5045</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Bering Sea, Norton Sound</td>
<td align="right">2105</td>
<td align="right">0.1931</td>
<td align="right">0.1656</td>
<td align="right">0.5793</td>
</tr>
<tr class="odd">
<td align="left">DDT</td>
<td align="left">Bering Strait</td>
<td align="right">3120</td>
<td align="right">0.2130</td>
<td align="right">0.1775</td>
<td align="right">0.4985</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Chukchi Sea</td>
<td align="right">2919</td>
<td align="right">0.2060</td>
<td align="right">0.1632</td>
<td align="right">0.5381</td>
</tr>
<tr class="odd">
<td align="left">DDT</td>
<td align="left">Gulf of Alaska</td>
<td align="right">17655</td>
<td align="right">0.3844</td>
<td align="right">0.3187</td>
<td align="right">0.0046</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Mean across held-out areas</td>
<td align="right">NA</td>
<td align="right">0.2375</td>
<td align="right">0.1942</td>
<td align="right">0.4368</td>
</tr>
</tbody>
</table>
<pre class="r"><code>if (exists(&quot;fit_objs&quot;) &amp;&amp; length(fit_objs) &gt; 0) {
  par(mfrow = c(2, 2), mar = c(7, 4, 3, 1))

  for (nm in names(fit_objs)) {
    fit_obj &lt;- fit_objs[[nm]]
    cf &lt;- as.data.frame(summary(fit_obj$model)$coefficients)
    cf$term &lt;- rownames(cf)
    keep &lt;- cf$term %in% c(&quot;log_dist&quot;, &quot;log_time&quot;, &quot;log_dist:log_time&quot;)
    cf &lt;- cf[keep, , drop = FALSE]
    labs &lt;- c(log_dist = &quot;Distance&quot;, log_time = &quot;Time lag&quot;, `log_dist:log_time` = &quot;Distance x Time&quot;)
    xpos &lt;- seq_len(nrow(cf))
    ylim_r &lt;- range(c(cf$Estimate - 1.96 * cf$`Std. Error`, cf$Estimate + 1.96 * cf$`Std. Error`, 0))

    plot(xpos, cf$Estimate,
         ylim = ylim_r,
         xlim = c(0.5, nrow(cf) + 0.5),
         xaxt = &quot;n&quot;,
         xlab = &quot;&quot;,
         ylab = &quot;Coefficient estimate&quot;,
         main = paste(c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[nm], &quot;mixed model&quot;),
         pch = 19,
         col = if (nm == &quot;sim_overall&quot;) &quot;darkorchid4&quot; else &quot;firebrick&quot;)
    axis(1, at = xpos, labels = labs[cf$term], las = 2)
    abline(h = 0, lty = 2, col = &quot;grey50&quot;)
    segments(xpos, cf$Estimate - 1.96 * cf$`Std. Error`,
             xpos, cf$Estimate + 1.96 * cf$`Std. Error`,
             lwd = 2,
             col = if (nm == &quot;sim_overall&quot;) &quot;darkorchid4&quot; else &quot;firebrick&quot;)
  }

  if (exists(&quot;cv_tabs&quot;) &amp;&amp; !is.null(cv_tabs) &amp;&amp; nrow(cv_tabs) &gt; 0) {
    cv_plot &lt;- cv_tabs[cv_tabs$held_out_area != &quot;Mean across held-out areas&quot;, ]
    areas &lt;- unique(cv_plot$held_out_area)
    responses &lt;- unique(cv_plot$response)
    rmse_mat &lt;- sapply(responses, function(resp) cv_plot$RMSE[match(areas, cv_plot$held_out_area[cv_plot$response == resp])])
    r2_mat &lt;- sapply(responses, function(resp) cv_plot$R2_pred[match(areas, cv_plot$held_out_area[cv_plot$response == resp])])
    if (is.null(dim(rmse_mat))) rmse_mat &lt;- matrix(rmse_mat, ncol = 1, dimnames = list(areas, responses))
    if (is.null(dim(r2_mat))) r2_mat &lt;- matrix(r2_mat, ncol = 1, dimnames = list(areas, responses))

    barplot(t(rmse_mat), beside = TRUE,
            col = c(&quot;darkorchid4&quot;, &quot;firebrick&quot;)[seq_len(ncol(rmse_mat))],
            names.arg = areas,
            las = 2,
            ylab = &quot;Blocked CV RMSE&quot;,
            main = &quot;Dyadic mixed model blocked CV&quot;)
    legend(&quot;topright&quot;, bty = &quot;n&quot;,
           legend = c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[colnames(rmse_mat)],
           fill = c(&quot;darkorchid4&quot;, &quot;firebrick&quot;)[seq_len(ncol(rmse_mat))])

    matplot(seq_along(areas), r2_mat,
            type = &quot;b&quot;, pch = 19, lty = 1,
            col = c(&quot;darkorchid4&quot;, &quot;firebrick&quot;)[seq_len(ncol(r2_mat))],
            xaxt = &quot;n&quot;,
            xlab = &quot;Held-out area&quot;,
            ylab = expression(R^2),
            main = &quot;Dyadic mixed model predictive fit&quot;)
    axis(1, at = seq_along(areas), labels = areas, las = 2)
    legend(&quot;topright&quot;, bty = &quot;n&quot;,
           legend = c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[colnames(r2_mat)],
           col = c(&quot;darkorchid4&quot;, &quot;firebrick&quot;)[seq_len(ncol(r2_mat))],
           lty = 1, pch = 19)
  } else {
    plot.new(); title(&quot;Blocked CV RMSE&quot;)
    plot.new(); title(&quot;Blocked CV predictive fit&quot;)
  }
}</code></pre>
<p><img src="outputs/figures/dyadic-mixed-graphics-1.png" width="1152" /></p>
</div>
<div id="c-trophic-covariate-extension-for-transferability"
class="section level2">
<h2>15C) Trophic Covariate Extension for Transferability</h2>
<p>We do not yet have tracking-derived movement covariates in this
dataset, so the highest-value biodiversity extension currently available
is a <strong>trophic proxy</strong> model. Here, pairwise differences in
<span class="math inline">\(\delta^{15}N\)</span> and <span
class="math inline">\(\delta^{13}C\)</span> are used as proxies for
trophic-position mismatch and habitat/foraging mismatch, respectively.
These covariates test whether Gulf-of-Alaska transfer improves when
ecological similarity is modeled alongside space and time. All
trophic/habitat isotope covariates are interpreted as transfer-oriented
ecological similarity indices under a baseline-stability assumption.</p>
<pre class="r"><code>if (!exists(&quot;pair_real&quot;)) {
  cat(&quot;pair_real not available — skipping trophic extension.\n&quot;)
} else {
  if (!exists(&quot;real_dat&quot;)) {
    fp &lt;- file.path(out_dir, &quot;real_testcase_prepared_data.csv&quot;)
    if (file.exists(fp)) real_dat &lt;- read.csv(fp, stringsAsFactors = FALSE)
  }

  if (!exists(&quot;real_dat&quot;) || !all(c(&quot;GUALIQUOTID&quot;, &quot;delta13C_real&quot;, &quot;delta15N_real&quot;) %in% names(real_dat))) {
    cat(&quot;real_dat with isotope fields not available — skipping trophic extension.\n&quot;)
  } else {
    iso_map &lt;- real_dat[, c(&quot;GUALIQUOTID&quot;, &quot;delta13C_real&quot;, &quot;delta15N_real&quot;)]
    iso_i &lt;- iso_map
    names(iso_i) &lt;- c(&quot;id_i&quot;, &quot;delta13C_i&quot;, &quot;delta15N_i&quot;)
    iso_j &lt;- iso_map
    names(iso_j) &lt;- c(&quot;id_j&quot;, &quot;delta13C_j&quot;, &quot;delta15N_j&quot;)

    pair_trophic &lt;- merge(pair_real, iso_i, by = &quot;id_i&quot;, all.x = TRUE)
    pair_trophic &lt;- merge(pair_trophic, iso_j, by = &quot;id_j&quot;, all.x = TRUE)

    pair_trophic$trophic_diff_n15 &lt;- abs(pair_trophic$delta15N_i - pair_trophic$delta15N_j)
    pair_trophic$habitat_diff_c13 &lt;- abs(pair_trophic$delta13C_i - pair_trophic$delta13C_j)
    pair_trophic$mean_trophic_n15 &lt;- rowMeans(cbind(pair_trophic$delta15N_i, pair_trophic$delta15N_j), na.rm = TRUE)
    pair_trophic$mean_habitat_c13 &lt;- rowMeans(cbind(pair_trophic$delta13C_i, pair_trophic$delta13C_j), na.rm = TRUE)

    fit_dyadic_trophic &lt;- function(df, yvar) {
      keep &lt;- is.finite(df[[yvar]]) &amp;
        is.finite(df$distance_km) &amp; is.finite(df$time_lag_years) &amp;
        is.finite(df$trophic_diff_n15) &amp; is.finite(df$habitat_diff_c13) &amp;
        is.finite(df$mean_trophic_n15) &amp; is.finite(df$mean_habitat_c13) &amp;
        !is.na(df$id_i) &amp; !is.na(df$id_j) &amp; !is.na(df$area_i) &amp; !is.na(df$area_j) &amp;
        !is.na(df$species_i) &amp; !is.na(df$species_j)

      dat &lt;- df[keep, c(
        yvar, &quot;distance_km&quot;, &quot;time_lag_years&quot;,
        &quot;trophic_diff_n15&quot;, &quot;habitat_diff_c13&quot;, &quot;mean_trophic_n15&quot;, &quot;mean_habitat_c13&quot;,
        &quot;id_i&quot;, &quot;id_j&quot;, &quot;area_i&quot;, &quot;area_j&quot;, &quot;species_i&quot;, &quot;species_j&quot;
      )]
      names(dat)[1] &lt;- &quot;y&quot;
      if (nrow(dat) &lt; 100) return(NULL)

      dat$log_dist &lt;- log(dat$distance_km + 1)
      dat$log_time &lt;- log(dat$time_lag_years + 1)
      dat$id_i &lt;- as.factor(dat$id_i)
      dat$id_j &lt;- as.factor(dat$id_j)
      dat$area_i &lt;- as.factor(dat$area_i)
      dat$area_j &lt;- as.factor(dat$area_j)
      dat$species_i &lt;- as.factor(dat$species_i)
      dat$species_j &lt;- as.factor(dat$species_j)

      ctrl &lt;- lmerControl(optimizer = &quot;bobyqa&quot;, optCtrl = list(maxfun = 1e5))

      form_full &lt;- y ~ log_dist * log_time + trophic_diff_n15 + habitat_diff_c13 +
        mean_trophic_n15 + mean_habitat_c13 +
        (1 | id_i) + (1 | id_j) +
        (1 | species_i) + (1 | species_j) +
        (1 | area_i) + (1 | area_j)

      form_fallback &lt;- y ~ log_dist * log_time + trophic_diff_n15 + habitat_diff_c13 +
        mean_trophic_n15 + mean_habitat_c13 +
        (1 | species_i) + (1 | species_j) +
        (1 | area_i) + (1 | area_j)

      mod &lt;- try(lmer(form_full, data = dat, REML = FALSE, control = ctrl), silent = TRUE)
      model_type &lt;- &quot;trophic_full_dyadic&quot;
      if (inherits(mod, &quot;try-error&quot;)) {
        mod &lt;- try(lmer(form_fallback, data = dat, REML = FALSE, control = ctrl), silent = TRUE)
        model_type &lt;- &quot;trophic_fallback_species_area&quot;
      }
      if (inherits(mod, &quot;try-error&quot;)) return(NULL)

      sm &lt;- summary(mod)
      cf &lt;- as.data.frame(sm$coefficients)
      cf$term &lt;- rownames(cf)

      get_cf &lt;- function(term, colname) {
        if (!(term %in% cf$term)) return(NA_real_)
        cf[cf$term == term, colname][1]
      }

      fixed_row &lt;- data.frame(
        response = yvar,
        model_type = model_type,
        n_pairs = nrow(dat),
        beta_dist = get_cf(&quot;log_dist&quot;, &quot;Estimate&quot;),
        beta_time = get_cf(&quot;log_time&quot;, &quot;Estimate&quot;),
        beta_dist_time = get_cf(&quot;log_dist:log_time&quot;, &quot;Estimate&quot;),
        beta_trophic_diff = get_cf(&quot;trophic_diff_n15&quot;, &quot;Estimate&quot;),
        beta_habitat_diff = get_cf(&quot;habitat_diff_c13&quot;, &quot;Estimate&quot;),
        beta_mean_trophic = get_cf(&quot;mean_trophic_n15&quot;, &quot;Estimate&quot;),
        beta_mean_habitat = get_cf(&quot;mean_habitat_c13&quot;, &quot;Estimate&quot;),
        AIC = AIC(mod),
        stringsAsFactors = FALSE
      )

      list(model = mod, data = dat, fixed = fixed_row)
    }

    run_blocked_cv_trophic &lt;- function(dat, model_type, yvar) {
      areas &lt;- sort(unique(c(as.character(dat$area_i), as.character(dat$area_j))))
      areas &lt;- areas[!is.na(areas) &amp; nchar(trimws(areas)) &gt; 0]
      if (length(areas) &lt; 3) return(NULL)

      ctrl &lt;- lmerControl(optimizer = &quot;bobyqa&quot;, optCtrl = list(maxfun = 1e5))
      form_full &lt;- y ~ log_dist * log_time + trophic_diff_n15 + habitat_diff_c13 +
        mean_trophic_n15 + mean_habitat_c13 +
        (1 | id_i) + (1 | id_j) +
        (1 | species_i) + (1 | species_j) +
        (1 | area_i) + (1 | area_j)
      form_fallback &lt;- y ~ log_dist * log_time + trophic_diff_n15 + habitat_diff_c13 +
        mean_trophic_n15 + mean_habitat_c13 +
        (1 | species_i) + (1 | species_j) +
        (1 | area_i) + (1 | area_j)

      cv_rows &lt;- lapply(areas, function(a) {
        test_idx &lt;- as.character(dat$area_i) == a | as.character(dat$area_j) == a
        train &lt;- dat[!test_idx, ]
        test &lt;- dat[test_idx, ]
        if (nrow(train) &lt; 100 || nrow(test) &lt; 20) return(NULL)

        form &lt;- if (model_type == &quot;trophic_full_dyadic&quot;) form_full else form_fallback
        fit &lt;- try(lmer(form, data = train, REML = FALSE, control = ctrl), silent = TRUE)
        if (inherits(fit, &quot;try-error&quot;)) {
          fit &lt;- try(lmer(form_fallback, data = train, REML = FALSE, control = ctrl), silent = TRUE)
        }
        if (inherits(fit, &quot;try-error&quot;)) return(NULL)

        pred &lt;- try(predict(fit, newdata = test, allow.new.levels = TRUE), silent = TRUE)
        if (inherits(pred, &quot;try-error&quot;)) return(NULL)

        obs &lt;- test$y
        data.frame(
          response = yvar,
          held_out_area = a,
          n_test = nrow(test),
          RMSE = sqrt(mean((obs - pred)^2, na.rm = TRUE)),
          MAE = mean(abs(obs - pred), na.rm = TRUE),
          R2_pred = if (length(unique(obs)) &gt; 1) cor(obs, pred, use = &quot;complete.obs&quot;)^2 else NA_real_,
          stringsAsFactors = FALSE
        )
      })

      cv_tab &lt;- do.call(rbind, Filter(Negate(is.null), cv_rows))
      if (is.null(cv_tab) || nrow(cv_tab) == 0) return(NULL)
      mean_row &lt;- data.frame(
        response = yvar,
        held_out_area = &quot;Mean across held-out areas&quot;,
        n_test = NA,
        RMSE = mean(cv_tab$RMSE, na.rm = TRUE),
        MAE = mean(cv_tab$MAE, na.rm = TRUE),
        R2_pred = mean(cv_tab$R2_pred, na.rm = TRUE),
        stringsAsFactors = FALSE
      )
      rbind(cv_tab, mean_row)
    }

    targets &lt;- c(&quot;sim_overall&quot;, &quot;sim_DDT&quot;)
    trophic_objs &lt;- lapply(targets, function(v) fit_dyadic_trophic(pair_trophic, v))
    names(trophic_objs) &lt;- targets
    trophic_objs &lt;- trophic_objs[!vapply(trophic_objs, is.null, logical(1))]

    if (length(trophic_objs) == 0) {
      cat(&quot;Trophic mixed-effects models failed or insufficient data.\n&quot;)
    } else {
      trophic_fixed &lt;- do.call(rbind, lapply(trophic_objs, function(x) x$fixed))
      trophic_fixed$response &lt;- c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[trophic_fixed$response]
      num_cols &lt;- setdiff(names(trophic_fixed), c(&quot;response&quot;, &quot;model_type&quot;))
      trophic_fixed[num_cols] &lt;- lapply(trophic_fixed[num_cols], function(x) round(x, 4))
      write.csv(trophic_fixed, file.path(out_dir, &quot;dyadic_trophic_model_fixed_effects.csv&quot;), row.names = FALSE)

      print(knitr::kable(
        trophic_fixed,
        row.names = FALSE,
        col.names = c(
          &quot;Response&quot;, &quot;Model&quot;, &quot;N pairs&quot;, &quot;Beta distance&quot;, &quot;Beta time&quot;, &quot;Beta distance x time&quot;,
          &quot;Beta trophic diff&quot;, &quot;Beta habitat diff&quot;, &quot;Beta mean trophic&quot;, &quot;Beta mean habitat&quot;, &quot;AIC&quot;
        ),
        caption = paste(
          &quot;Table 7. Trophic-augmented dyadic mixed-effects models.&quot;,
          &quot;New biodiversity covariates are isotope-derived trophic and habitat proxies.&quot;
        )
      ))

      trophic_cv &lt;- do.call(rbind, lapply(names(trophic_objs), function(v) {
        run_blocked_cv_trophic(trophic_objs[[v]]$data, trophic_objs[[v]]$fixed$model_type[1], v)
      }))

      if (!is.null(trophic_cv) &amp;&amp; nrow(trophic_cv) &gt; 0) {
        trophic_cv$response &lt;- c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[trophic_cv$response]
        num_cols &lt;- c(&quot;n_test&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;R2_pred&quot;)
        for (nc in num_cols) {
          if (nc %in% names(trophic_cv)) trophic_cv[[nc]] &lt;- round(trophic_cv[[nc]], 4)
        }
        write.csv(trophic_cv, file.path(out_dir, &quot;dyadic_trophic_model_blocked_cv.csv&quot;), row.names = FALSE)

        base_cv_fp &lt;- file.path(out_dir, &quot;dyadic_mixed_model_blocked_cv.csv&quot;)
        if (file.exists(base_cv_fp)) {
          base_cv &lt;- read.csv(base_cv_fp, stringsAsFactors = FALSE)
          base_cv$model &lt;- &quot;Baseline mixed model&quot;
          trophic_cv$model &lt;- &quot;Trophic mixed model&quot;

          compare_cv &lt;- rbind(base_cv, trophic_cv)
          keep_rows &lt;- compare_cv$held_out_area %in% c(&quot;Gulf of Alaska&quot;, &quot;Mean across held-out areas&quot;)
          compare_cv &lt;- compare_cv[keep_rows, c(&quot;response&quot;, &quot;model&quot;, &quot;held_out_area&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;R2_pred&quot;)]
          names(compare_cv) &lt;- c(&quot;Response&quot;, &quot;Model&quot;, &quot;Held-out area&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;Predictive_R2&quot;)
          write.csv(compare_cv, file.path(out_dir, &quot;dyadic_trophic_transfer_comparison.csv&quot;), row.names = FALSE)

          print(knitr::kable(
            compare_cv,
            row.names = FALSE,
            col.names = c(&quot;Response&quot;, &quot;Model&quot;, &quot;Held-out area&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;Predictive R2&quot;),
            caption = paste(
              &quot;Table 8. Transfer-performance comparison for the baseline versus trophic-augmented mixed models.&quot;,
              &quot;Rows highlight Gulf of Alaska and the mean across held-out areas.&quot;
            )
          ))

          gulf_compare &lt;- compare_cv[compare_cv$`Held-out area` == &quot;Gulf of Alaska&quot;, ]
          if (nrow(gulf_compare) &gt; 0) {
            cat(&quot;\nGulf of Alaska remains the hardest transfer domain. The trophic extension should be interpreted as a first biodiversity-aware stress test, not a full ecological solution; meaningful further gains will likely require explicit movement/connectivity covariates or oceanographic predictors.\n&quot;)
          }
        }
      }
    }
  }
}</code></pre>
<table style="width:100%;">
<caption>Table 7. Trophic-augmented dyadic mixed-effects models. New
biodiversity covariates are isotope-derived trophic and habitat
proxies.</caption>
<colgroup>
<col width="5%" />
<col width="12%" />
<col width="4%" />
<col width="8%" />
<col width="6%" />
<col width="12%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="left">Model</th>
<th align="right">N pairs</th>
<th align="right">Beta distance</th>
<th align="right">Beta time</th>
<th align="right">Beta distance x time</th>
<th align="right">Beta trophic diff</th>
<th align="right">Beta habitat diff</th>
<th align="right">Beta mean trophic</th>
<th align="right">Beta mean habitat</th>
<th align="right">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">trophic_full_dyadic</td>
<td align="right">23220</td>
<td align="right">-0.0228</td>
<td align="right">-0.0081</td>
<td align="right">6e-04</td>
<td align="right">-0.0208</td>
<td align="right">-0.0417</td>
<td align="right">0.0093</td>
<td align="right">-0.0389</td>
<td align="right">-32573.747</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">trophic_full_dyadic</td>
<td align="right">23220</td>
<td align="right">-0.0389</td>
<td align="right">0.0050</td>
<td align="right">-7e-04</td>
<td align="right">0.0003</td>
<td align="right">0.0005</td>
<td align="right">0.0170</td>
<td align="right">-0.0479</td>
<td align="right">-9815.946</td>
</tr>
</tbody>
</table>
<table style="width:100%;">
<caption>Table 8. Transfer-performance comparison for the baseline
versus trophic-augmented mixed models. Rows highlight Gulf of Alaska and
the mean across held-out areas.</caption>
<colgroup>
<col width="10%" />
<col width="24%" />
<col width="31%" />
<col width="8%" />
<col width="8%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Response</th>
<th align="left">Model</th>
<th align="left">Held-out area</th>
<th align="right">RMSE</th>
<th align="right">MAE</th>
<th align="right">Predictive R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Baseline mixed model</td>
<td align="left">Gulf of Alaska</td>
<td align="right">0.2153</td>
<td align="right">0.1742</td>
<td align="right">0.0396</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="left">Baseline mixed model</td>
<td align="left">Mean across held-out areas</td>
<td align="right">0.1510</td>
<td align="right">0.1221</td>
<td align="right">0.4052</td>
</tr>
<tr class="odd">
<td align="left">DDT</td>
<td align="left">Baseline mixed model</td>
<td align="left">Gulf of Alaska</td>
<td align="right">0.3844</td>
<td align="right">0.3187</td>
<td align="right">0.0046</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Baseline mixed model</td>
<td align="left">Mean across held-out areas</td>
<td align="right">0.2375</td>
<td align="right">0.1942</td>
<td align="right">0.4368</td>
</tr>
<tr class="odd">
<td align="left">Overall</td>
<td align="left">Trophic mixed model</td>
<td align="left">Gulf of Alaska</td>
<td align="right">0.2285</td>
<td align="right">0.1818</td>
<td align="right">0.0839</td>
</tr>
<tr class="even">
<td align="left">Overall</td>
<td align="left">Trophic mixed model</td>
<td align="left">Mean across held-out areas</td>
<td align="right">0.1467</td>
<td align="right">0.1195</td>
<td align="right">0.4667</td>
</tr>
<tr class="odd">
<td align="left">DDT</td>
<td align="left">Trophic mixed model</td>
<td align="left">Gulf of Alaska</td>
<td align="right">0.3883</td>
<td align="right">0.3214</td>
<td align="right">0.0035</td>
</tr>
<tr class="even">
<td align="left">DDT</td>
<td align="left">Trophic mixed model</td>
<td align="left">Mean across held-out areas</td>
<td align="right">0.2430</td>
<td align="right">0.1992</td>
<td align="right">0.4309</td>
</tr>
</tbody>
</table>
<p>Gulf of Alaska remains the hardest transfer domain. The trophic
extension should be interpreted as a first biodiversity-aware stress
test, not a full ecological solution; meaningful further gains will
likely require explicit movement/connectivity covariates or
oceanographic predictors.</p>
<pre class="r"><code>if (exists(&quot;trophic_objs&quot;) &amp;&amp; length(trophic_objs) &gt; 0) {
  par(mfrow = c(2, 2), mar = c(8, 4, 3, 1))

  for (nm in names(trophic_objs)) {
    fit_obj &lt;- trophic_objs[[nm]]
    cf &lt;- fixef(fit_obj$model)
    keep_terms &lt;- c(&quot;log_dist&quot;, &quot;log_time&quot;, &quot;log_dist:log_time&quot;, &quot;trophic_diff_n15&quot;, &quot;habitat_diff_c13&quot;)
    cf &lt;- cf[names(cf) %in% keep_terms]
    labs &lt;- c(
      log_dist = &quot;Distance&quot;,
      log_time = &quot;Time lag&quot;,
      `log_dist:log_time` = &quot;Distance x Time&quot;,
      trophic_diff_n15 = expression(Delta*delta^{15}*N),
      habitat_diff_c13 = expression(Delta*delta^{13}*C)
    )
    cols &lt;- ifelse(cf &gt;= 0, &quot;steelblue4&quot;, &quot;firebrick&quot;)
    bp &lt;- barplot(cf,
                  col = cols,
                  las = 2,
                  ylab = &quot;Coefficient estimate&quot;,
                  main = paste(c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[nm], &quot;trophic model&quot;),
                  names.arg = rep(&quot;&quot;, length(cf)))
    axis(1, at = bp, labels = names(cf), las = 2)
    abline(h = 0, lty = 2, col = &quot;grey50&quot;)
  }

  if (exists(&quot;compare_cv&quot;) &amp;&amp; !is.null(compare_cv) &amp;&amp; nrow(compare_cv) &gt; 0) {
    gulf &lt;- compare_cv[compare_cv$`Held-out area` == &quot;Gulf of Alaska&quot;, ]
    mean_rows &lt;- compare_cv[compare_cv$`Held-out area` == &quot;Mean across held-out areas&quot;, ]

    plot_df &lt;- rbind(gulf, mean_rows)
    plot_df$group &lt;- paste(plot_df$Response, plot_df$`Held-out area`, sep = &quot;\n&quot;)
    groups &lt;- unique(plot_df$group)
    models &lt;- unique(plot_df$Model)
    rmse_mat &lt;- sapply(models, function(model) plot_df$RMSE[match(groups, plot_df$group[plot_df$Model == model])])
    r2_mat &lt;- sapply(models, function(model) plot_df$Predictive_R2[match(groups, plot_df$group[plot_df$Model == model])])
    if (is.null(dim(rmse_mat))) rmse_mat &lt;- matrix(rmse_mat, ncol = 1, dimnames = list(groups, models))
    if (is.null(dim(r2_mat))) r2_mat &lt;- matrix(r2_mat, ncol = 1, dimnames = list(groups, models))

    barplot(t(rmse_mat), beside = TRUE,
            col = c(&quot;grey55&quot;, &quot;darkgreen&quot;)[seq_len(ncol(rmse_mat))],
            names.arg = groups,
            las = 2,
            ylab = &quot;RMSE&quot;,
            main = &quot;Baseline vs trophic model transfer RMSE&quot;)
    legend(&quot;topright&quot;, bty = &quot;n&quot;, fill = c(&quot;grey55&quot;, &quot;darkgreen&quot;)[seq_len(ncol(rmse_mat))], legend = colnames(rmse_mat))

    barplot(t(r2_mat), beside = TRUE,
            col = c(&quot;grey55&quot;, &quot;darkgreen&quot;)[seq_len(ncol(r2_mat))],
            names.arg = groups,
            las = 2,
            ylab = expression(R^2),
            main = &quot;Baseline vs trophic model transfer predictive fit&quot;)
    legend(&quot;topleft&quot;, bty = &quot;n&quot;, fill = c(&quot;grey55&quot;, &quot;darkgreen&quot;)[seq_len(ncol(r2_mat))], legend = colnames(r2_mat))
  } else {
    plot.new(); title(&quot;Transfer RMSE comparison&quot;)
    plot.new(); title(&quot;Transfer predictive fit comparison&quot;)
  }
}</code></pre>
<p><img src="outputs/figures/dyadic-trophic-graphics-1.png" width="1152" /></p>
</div>
<div id="detailed-methods-and-hypothesis-testing-framework"
class="section level2">
<h2>16) Detailed Methods and Hypothesis-Testing Framework</h2>
<p>This section formalizes the analytical strategy as a scale-aware
hypothesis-testing workflow. The goal is not only to estimate
distance-decay, but to test whether observed patterns exceed what would
be expected under ecologically informed null structure.</p>
<div id="a.-core-inferential-setup" class="section level3">
<h3>16A. Core inferential setup</h3>
<p>The analysis is built around pairwise comparisons among samples. For
each pair, we quantify:</p>
<ul>
<li>geographic separation (km),</li>
<li>contaminant similarity (DDT family; PCP/PCB family),</li>
<li>isotope similarity (delta13C and delta15N structure), and</li>
<li>multivariate overall similarity.</li>
</ul>
<p>This pairwise framing makes scale explicit because each observation
is a contrast across space (and later time), not a single-site
value.</p>
</div>
<div id="b.-hypotheses-and-matched-tests" class="section level3">
<h3>16B. Hypotheses and matched tests</h3>
<p>The workflow tests the following hypotheses.</p>
<ol style="list-style-type: decimal">
<li><p><strong>H1: Spatial decay exists for each response</strong>.
Test: fit exponential, power-law, and log-linear distance-decay
functions to each response and evaluate slope direction, fit quality,
and AIC support.</p></li>
<li><p><strong>H2: Observed decay is stronger than expected under
structured randomness</strong>. Test: permutation null models comparing
observed log-distance slopes to null slope distributions (p_lower and
p_upper). This is the principal significance test for distance
structure.</p></li>
<li><p><strong>H3: Decay form differs by contaminant class</strong>.
Test: compare functional-form rankings and parameter values among
DDT-family, PCP/PCB-family, isotope, and overall similarity
responses.</p></li>
<li><p><strong>H4: Distance-decay is not species-invariant</strong>.
Test: species-level model fits and slope summaries, followed by
cross-species synthesis table of best models and decay
strength.</p></li>
<li><p><strong>H5: Time contributes independent structure beyond
distance</strong>. Test: spatiotemporal scaling models including
distance, temporal lag, and distance-by-time interaction terms.</p></li>
<li><p><strong>H6: Hierarchical dependence matters for inference and
prediction</strong>. Test: dyadic mixed-effects models with crossed
random effects for individuals, species, and areas, preventing
pseudoreplication from pairwise data reuse.</p></li>
<li><p><strong>H7: Biodiversity-relevant trophic structure improves
transferability</strong>. Test: extension of dyadic mixed models with
trophic and habitat isotope covariates, compared against baseline models
under blocked transfer tests.</p></li>
</ol>
</div>
<div id="c.-null-models-as-a-central-inferential-engine"
class="section level3">
<h3>16C. Null models as a central inferential engine</h3>
<p>Null models are not a side diagnostic in this workflow; they are the
backbone of hypothesis testing for spatial structure.</p>
<ul>
<li>In the synthetic demonstration, randomization establishes the
baseline slope distribution expected when spatial signal is absent.</li>
<li>In real data, spatially constrained permutations preserve broad area
and species composition while breaking fine-scale pairwise alignment,
producing a conservative counterfactual for H2.</li>
</ul>
<p>This design answers the key inferential question directly: is the
observed decay stronger than expected given the sampling structure and
broad ecological grouping?</p>
</div>
<div id="d.-scale-as-the-design-principle" class="section level3">
<h3>16D. Scale as the design principle</h3>
<p>Scale is explicitly embedded in each stage:</p>
<ul>
<li><strong>Fine-to-broad spatial scale</strong>: pairwise distances
from local to basin-wide extents, with flexible functional forms to
detect curvature and attenuation behavior.</li>
<li><strong>Temporal scale</strong>: year and pairwise lag terms test
whether spatial decay is stable or shifts with time separation.</li>
<li><strong>Biological scale</strong>: species-level and trophic
structure test whether ecological organization changes decay strength or
model transfer performance.</li>
<li><strong>Prediction scale</strong>: leave-one-area-out blocking
evaluates extrapolation to truly new spatial domains rather than
interpolative fit alone.</li>
</ul>
<p>Together, these choices convert scale from a descriptive backdrop
into an explicit driver of model architecture and hypothesis tests.</p>
</div>
<div id="e.-why-this-multi-method-sequence-is-necessary"
class="section level3">
<h3>16E. Why this multi-method sequence is necessary</h3>
<p>No single model can answer all questions in contamination
biogeography. The sequence used here is deliberate:</p>
<ol style="list-style-type: decimal">
<li>identify form and strength of decay,</li>
<li>validate against null expectations,</li>
<li>evaluate heterogeneity among species and chemistry classes,</li>
<li>incorporate temporal coupling,</li>
<li>model hierarchical dependence, and</li>
<li>test ecological covariates for spatial transfer.</li>
</ol>
<p>This sequence balances mechanistic interpretation and predictive
robustness, while keeping inference anchored to explicit null
expectations and scale-aware validation.</p>
</div>
<div id="f.-how-trophic-level-enters-the-models" class="section level3">
<h3>16F. How trophic level enters the models</h3>
<p>Trophic structure is entered through isotope-derived covariates in
the dyadic trophic model:</p>
<ul>
<li><code>trophic_diff_n15 = |delta15N_i - delta15N_j|</code>, a proxy
for trophic-level mismatch,</li>
<li><code>habitat_diff_c13 = |delta13C_i - delta13C_j|</code>, a proxy
for habitat/foraging mismatch,</li>
<li><code>mean_trophic_n15</code>, the pair-average trophic position
proxy,</li>
<li><code>mean_habitat_c13</code>, the pair-average habitat baseline
proxy.</li>
</ul>
<p>Interpretation on the similarity scale is direct: negative
coefficients for mismatch terms indicate that isotopically dissimilar
pairs are less similar in contaminants after accounting for distance,
time lag, and hierarchical random effects.</p>
<p>Important caution: these are ecological proxies, not direct causal
measurements of trophic level or habitat identity. delta15N and delta13C
each include baseline spatial variation, source mixing, and
tissue-integration effects; therefore, coefficients should be
interpreted as associational signals unless baseline correction and
discrimination-factor uncertainty are modeled explicitly.</p>
</div>
<div
id="g.-integrative-graphics-how-distance-time-species-and-trophic-effects-enter"
class="section level3">
<h3>16G. Integrative graphics: how distance, time, species, and trophic
effects enter</h3>
<pre class="r"><code>if (!exists(&quot;fit_objs&quot;) || length(fit_objs) == 0) {
  plot.new(); title(&quot;Integrative model-entry graphics unavailable (baseline model objects missing)&quot;)
} else {
  par(mfrow = c(2, 2), mar = c(8, 4, 3, 1))

  # Panel A: baseline fixed effects (distance, time, interaction)
  base_terms &lt;- c(&quot;log_dist&quot;, &quot;log_time&quot;, &quot;log_dist:log_time&quot;)
  lab_map &lt;- c(log_dist = &quot;Distance&quot;, log_time = &quot;Time lag&quot;, `log_dist:log_time` = &quot;Distance x Time&quot;)

  for (nm in names(fit_objs)) {
    cf &lt;- as.data.frame(summary(fit_objs[[nm]]$model)$coefficients)
    cf$term &lt;- rownames(cf)
    cf &lt;- cf[cf$term %in% base_terms, , drop = FALSE]
    if (nrow(cf) == 0) { plot.new(); title(paste(nm, &quot;baseline fixed effects unavailable&quot;)); next }

    xpos &lt;- seq_len(nrow(cf))
    ylim_r &lt;- range(c(cf$Estimate - 1.96 * cf$`Std. Error`, cf$Estimate + 1.96 * cf$`Std. Error`, 0), na.rm = TRUE)
    plot(xpos, cf$Estimate,
         ylim = ylim_r,
         xlim = c(0.5, nrow(cf) + 0.5),
         xaxt = &quot;n&quot;,
         xlab = &quot;&quot;,
         ylab = &quot;Coefficient estimate&quot;,
         main = paste(c(sim_overall = &quot;Overall&quot;, sim_DDT = &quot;DDT&quot;)[nm], &quot;baseline fixed effects&quot;),
         pch = 19,
         col = if (nm == &quot;sim_overall&quot;) &quot;darkorchid4&quot; else &quot;firebrick&quot;)
    axis(1, at = xpos, labels = lab_map[cf$term], las = 2)
    abline(h = 0, lty = 2, col = &quot;grey50&quot;)
    segments(xpos, cf$Estimate - 1.96 * cf$`Std. Error`,
             xpos, cf$Estimate + 1.96 * cf$`Std. Error`,
             lwd = 2,
             col = if (nm == &quot;sim_overall&quot;) &quot;darkorchid4&quot; else &quot;firebrick&quot;)
  }

  # Panel C: species and area random-effect SDs (shows hierarchical entry)
  first_nm &lt;- names(fit_objs)[1]
  vc &lt;- as.data.frame(VarCorr(fit_objs[[first_nm]]$model))
  vc &lt;- vc[vc$grp %in% c(&quot;species_i&quot;, &quot;species_j&quot;, &quot;area_i&quot;, &quot;area_j&quot;, &quot;id_i&quot;, &quot;id_j&quot;), c(&quot;grp&quot;, &quot;sdcor&quot;)]
  if (nrow(vc) &gt; 0) {
    ord &lt;- order(vc$sdcor, decreasing = TRUE)
    barplot(vc$sdcor[ord],
            names.arg = vc$grp[ord],
            las = 2,
            col = &quot;grey45&quot;,
            ylab = &quot;Random-effect SD&quot;,
            main = &quot;Hierarchical variance entry (example response)&quot;)
  } else {
    plot.new(); title(&quot;Random-effect SDs unavailable&quot;)
  }

  # Panel D: trophic covariate fixed effects if trophic models exist
  if (exists(&quot;trophic_objs&quot;) &amp;&amp; length(trophic_objs) &gt; 0) {
    tnm &lt;- names(trophic_objs)[1]
    tcf &lt;- as.data.frame(summary(trophic_objs[[tnm]]$model)$coefficients)
    tcf$term &lt;- rownames(tcf)
    keep &lt;- c(&quot;trophic_diff_n15&quot;, &quot;habitat_diff_c13&quot;, &quot;mean_trophic_n15&quot;, &quot;mean_habitat_c13&quot;)
    tcf &lt;- tcf[tcf$term %in% keep, , drop = FALSE]
    tlab &lt;- c(
      trophic_diff_n15 = &quot;Trophic mismatch (delta15N)&quot;,
      habitat_diff_c13 = &quot;Habitat mismatch (delta13C)&quot;,
      mean_trophic_n15 = &quot;Pair mean trophic proxy&quot;,
      mean_habitat_c13 = &quot;Pair mean habitat proxy&quot;
    )
    if (nrow(tcf) &gt; 0) {
      xpos &lt;- seq_len(nrow(tcf))
      ylim_r &lt;- range(c(tcf$Estimate - 1.96 * tcf$`Std. Error`, tcf$Estimate + 1.96 * tcf$`Std. Error`, 0), na.rm = TRUE)
      plot(xpos, tcf$Estimate,
           ylim = ylim_r,
           xlim = c(0.5, nrow(tcf) + 0.5),
           xaxt = &quot;n&quot;,
           xlab = &quot;&quot;,
           ylab = &quot;Coefficient estimate&quot;,
           main = &quot;Ecology entry via trophic proxies&quot;,
           pch = 19,
           col = &quot;darkgreen&quot;)
      axis(1, at = xpos, labels = tlab[tcf$term], las = 2)
      abline(h = 0, lty = 2, col = &quot;grey50&quot;)
      segments(xpos, tcf$Estimate - 1.96 * tcf$`Std. Error`,
               xpos, tcf$Estimate + 1.96 * tcf$`Std. Error`,
               lwd = 2,
               col = &quot;darkgreen&quot;)
    } else {
      plot.new(); title(&quot;Trophic fixed effects unavailable&quot;)
    }
  } else {
    plot.new(); title(&quot;Trophic model objects unavailable&quot;)
  }
}</code></pre>
<p><img src="outputs/figures/method-entry-graphics-1.png" width="1152" /></p>
<p>The figure above is designed to answer exactly how each driver
enters:</p>
<ul>
<li>distance and time enter as fixed effects (<code>log_dist</code>,
<code>log_time</code>) plus interaction,</li>
<li>species/area/individual repeated structure enters as random
effects,</li>
<li>ecology enters via trophic/habitat isotope proxy covariates.</li>
</ul>
<p>These panels are best interpreted as an entry map of model terms and
uncertainty, complemented by the dedicated performance plots in Sections
15B and 15C.</p>
</div>
<div id="h.-dyadic-mixed-models-explained-for-undergraduates"
class="section level3">
<h3>16H. Dyadic mixed models explained for undergraduates</h3>
<p>A dyadic mixed model is a model for data where each row describes a
<strong>pair</strong> (a dyad), not a single sample. Here, each row
compares sample <code>i</code> and sample <code>j</code>.</p>
<p>Why this matters: the same sample appears in many different pairs, so
pairwise rows are not independent. If we ignore that, we can get
overconfident p-values and unstable effects.</p>
<p>The model solves this by combining:</p>
<ul>
<li><strong>fixed effects</strong> (distance, time, trophic covariates):
average relationships we want to estimate, and</li>
<li><strong>random effects</strong> (id_i/id_j, species_i/species_j,
area_i/area_j): adjustments that absorb repeated-measure structure and
group-level dependence.</li>
</ul>
<p>In plain language: fixed effects tell us the average rule; random
effects acknowledge that each bird/species/area has its own baseline
around that rule. Because each pair has two members, modeling both
<code>i</code> and <code>j</code> keeps the analysis symmetric; if this
is ignored, repeated use of the same samples can make effects look more
certain than they really are.</p>
</div>
<div id="i.-method-citations" class="section level3">
<h3>16I. Method citations</h3>
<p>Methods used here follow established references for mixed models,
smooth spatial models, information-theoretic model comparison, and
null/permutation logic. For mixed models, interpretation here
prioritizes effect sizes, uncertainty, and blocked cross-validation
performance; where p-values are used, denominator-df approximations
depend on method choices.</p>
</div>
<div id="j.-references-for-methods" class="section level3">
<h3>16J. References for methods</h3>
<ul>
<li>Bates D, Machler M, Bolker B, Walker S. 2015. Fitting linear
mixed-effects models using lme4. Journal of Statistical Software
67(1):1-48.</li>
<li>Wood SN. 2017. Generalized Additive Models: An Introduction with R
(2nd ed.). Chapman and Hall/CRC.</li>
<li>Burnham KP, Anderson DR. 2002. Model Selection and Multimodel
Inference: A Practical Information-Theoretic Approach (2nd ed.).
Springer.</li>
<li>Manly BFJ. 2006. Randomization, Bootstrap and Monte Carlo Methods in
Biology (3rd ed.). Chapman and Hall/CRC.</li>
<li>Gotelli NJ, Graves GR. 1996. Null Models in Ecology. Smithsonian
Institution Press.</li>
<li>Legendre P, Fortin MJ, Borcard D. 2015. Should the Mantel test be
used in spatial analysis? Methods in Ecology and Evolution 6:1239-1247.
(Context for spatial dependence cautions and alternatives.)</li>
<li>Roberts DR, Bahn V, Ciuti S, et al. 2017. Cross-validation
strategies for data with temporal, spatial, hierarchical, or
phylogenetic structure. Ecography 40:913-929.</li>
<li>Post DM. 2002. Using stable isotopes to estimate trophic position:
models, methods, and assumptions. Ecology 83:703-718.</li>
<li>Fry B. 2006. Stable Isotope Ecology. Springer.</li>
<li>McMahon KW, McCarthy MD. 2016. Embracing variability in trophic
discrimination factors facilitates calculation of ecologically
meaningful trophic positions. Oecologia 181:991-1003.</li>
<li>Newsome SD, del Rio CM, Bearhop S, Phillips DL. 2007. A niche for
isotopic ecology. Frontiers in Ecology and the Environment
5:429-436.</li>
<li>Kenny DA, Kashy DA, Cook WL. 2006. Dyadic Data Analysis. Guilford
Press.</li>
</ul>
</div>
</div>
<div id="conclusion-main-drivers-of-contamination-variation"
class="section level2">
<h2>17) Conclusion: Main Drivers of Contamination Variation</h2>
<p>Across contaminants and isotopes, the dominant source of variation is
<strong>space</strong>: chemical similarity decreases with increasing
geographic distance, and this spatial decay is strongest for DDT-family
chemistry and strongest overall in the multivariate index.</p>
<p>The second driver is <strong>contaminant class and transport
behavior</strong>:</p>
<ul>
<li>DDT-family patterns are steep and typically best described by
exponential decay, consistent with spatially localized or regionally
concentrated sources plus distance attenuation.</li>
<li>PCP/PCB patterns are shallower, consistent with broader transport
and mixing.</li>
<li>Isotopes show smoother, more gradient-like structure (often better
log-linear support), indicating broad foraging/habitat transitions
rather than sharply bounded sources.</li>
</ul>
<p>The third driver is <strong>time and space-time
coupling</strong>:</p>
<ul>
<li>Temporal lags contribute additional variation, but usually less than
distance.</li>
<li>The joint space-time model indicates that distance-decay strength
can shift with temporal separation (interaction term), meaning spatial
structure is not fully time-stationary.</li>
</ul>
<p>The fourth driver is <strong>species/ecology context</strong>:</p>
<ul>
<li>Species-level fits show different slope magnitudes and best
functional forms, implying trophic ecology and movement behavior
modulate exposure patterns.</li>
<li>In this dataset, high-pair species (especially <em>Uria</em> spp.)
dominate signal strength, so future inference should balance species
representation.</li>
</ul>
<div id="synthesis-of-hypothesis-support" class="section level3">
<h3>Synthesis of hypothesis support</h3>
<p>The strongest empirical support is for H1 and H2: spatial decay is
consistently negative, and null-model comparisons indicate that observed
decay exceeds structured random expectation. H3 is also supported:
DDT-family responses show steeper and often more exponential behavior
than PCP/PCB-family and isotope structure. H4 and H6 are supported by
species-level heterogeneity and dyadic mixed-model performance under
blocked transfer. H5 and H7 are supported but context-dependent:
temporal terms and trophic covariates add information, especially in
difficult transfer settings, but gains vary by response and held-out
region. These trophic gains should be interpreted as improved ecological
transfer signals, not stand-alone proof of trophic causation.</p>
</div>
<div id="practical-take-away-for-predictive-modeling"
class="section level3">
<h3>Practical take-away for predictive modeling</h3>
<p>For prediction, prioritize a <strong>spatiotemporal model</strong>
where contamination is modeled as a function of distance structure, year
(or lag), and species effects simultaneously (for example, GAM or
mixed-effects spatial model with spatial cross-validation by area). This
workflow is best aligned with the evidence in this report: space is the
strongest axis, time is informative, and species modifies both.</p>
<p>If a single concise ranking is needed for this report, it is:</p>
<ol style="list-style-type: decimal">
<li>Geographic distance (spatial structure)</li>
<li>Contaminant chemistry class (DDT vs PCB/PCP vs isotope
behavior)</li>
<li>Time (collection year / pairwise lag)</li>
<li>Species ecological differences</li>
</ol>
</div>
</div>
<div id="graphics-gallery" class="section level2">
<h2>18) Graphics Gallery</h2>
<p>This appendix pulls together all graphics generated by the workflow
so they can be reviewed in one place, including the original
distance-decay plots and the new spatiotemporal and
biodiversity-augmented mixed-model figures.</p>
<div id="dummy-distance-decay-panels" class="section level3">
<h3>Dummy distance decay panels</h3>
<p>[1] “outputs/figures/plotting-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="generality-across-response-types" class="section level3">
<h3>Generality across response types</h3>
<p>[1] “outputs/figures/generality-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="real-data-distance-decay-fits" class="section level3">
<h3>Real data distance decay fits</h3>
<p>[1] “outputs/real_testcase_distance_decay_plots.png” attr(,“class”)
[1] “knit_image_paths” “knit_asis”</p>
</div>
<div id="binned-mean-similarity-with-95-ci" class="section level3">
<h3>Binned mean similarity with 95% CI</h3>
<p>[1] “outputs/figures/real-binned-ci-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="observed-versus-null-slope-distributions"
class="section level3">
<h3>Observed versus null slope distributions</h3>
<p>[1] “outputs/figures/real-null-slopes-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="observed-versus-null-decay-bands" class="section level3">
<h3>Observed versus null decay bands</h3>
<p>[1] “outputs/figures/real-null-decay-bands-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="functional-form-comparison" class="section level3">
<h3>Functional form comparison</h3>
<p>[1] “outputs/figures/fitted-curves-plot-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="gam-spatial-prediction" class="section level3">
<h3>GAM spatial prediction</h3>
<p>[1] “outputs/figures/gam-spatial-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="temporal-trends" class="section level3">
<h3>Temporal trends</h3>
<p>[1] “outputs/figures/temporal-trend-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="distance-decay-by-time-lag-tercile" class="section level3">
<h3>Distance decay by time lag tercile</h3>
<p>[1] “outputs/figures/spatiotemporal-visualization-1.png”
attr(,“class”) [1] “knit_image_paths” “knit_asis”</p>
</div>
<div id="dyadic-mixed-model-diagnostics" class="section level3">
<h3>Dyadic mixed model diagnostics</h3>
<p>[1] “outputs/figures/dyadic-mixed-graphics-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="trophic-mixed-model-diagnostics" class="section level3">
<h3>Trophic mixed model diagnostics</h3>
<p>[1] “outputs/figures/dyadic-trophic-graphics-1.png” attr(,“class”)
[1] “knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown" class="section level3">
<h3>species breakdown</h3>
<p>[1] “outputs/figures/species-breakdown-1.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-2" class="section level3">
<h3>Species breakdown 2</h3>
<p>[1] “outputs/figures/species-breakdown-2.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-3" class="section level3">
<h3>Species breakdown 3</h3>
<p>[1] “outputs/figures/species-breakdown-3.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-4" class="section level3">
<h3>Species breakdown 4</h3>
<p>[1] “outputs/figures/species-breakdown-4.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-5" class="section level3">
<h3>Species breakdown 5</h3>
<p>[1] “outputs/figures/species-breakdown-5.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-6" class="section level3">
<h3>Species breakdown 6</h3>
<p>[1] “outputs/figures/species-breakdown-6.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-7" class="section level3">
<h3>Species breakdown 7</h3>
<p>[1] “outputs/figures/species-breakdown-7.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
<div id="species-breakdown-8" class="section level3">
<h3>Species breakdown 8</h3>
<p>[1] “outputs/figures/species-breakdown-8.png” attr(,“class”) [1]
“knit_image_paths” “knit_asis”</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
