## add_new_sources_2025.R
## Appends 29 new source entries to manual_source_intake.csv
## Run once; safe to re-run — checks for existing source_ids first.

library(data.table)

proj_root <- "/Users/brianjenquist/VSCode/DryadPlantTraits"
f <- file.path(proj_root, "data", "manual_source_intake.csv")
existing <- fread(f)

new_rows <- data.table(
  source_id = c(
    "manual_rainbio_central_africa",
    "manual_ecat_central_africa",
    "manual_gabon_gbif_ipt",
    "manual_flora_russia_inaturalist",
    "manual_oxytropis_asian_russia",
    "manual_altb_virtual_herbarium",
    "manual_fleroff_georef_records",
    "manual_kyrgyzstan_alien_plants",
    "manual_kyrgyzstan_dryad_2025",
    "manual_flora_mongolia_inaturalist",
    "manual_lesser_sunda_endemics",
    "manual_sunda_sahul_checklist",
    "manual_sunda_sahul_suppl_dataset",
    "manual_myanmar_vascular_checklist",
    "manual_flora_sumatra_gbif_main",
    "manual_flora_sumatra_gbif_anda2",
    "manual_flora_sumatra_batang_toru",
    "manual_paciflora_bdj",
    "manual_paciflora_dryad",
    "manual_southern_islands_flora_paper",
    "manual_sivflora_zenodo",
    "manual_amazon_checklist_cardoso",
    "manual_colombia_bioregions_bystriakova",
    "manual_theobroma_occurrences",
    "manual_pucv_herbarium_chile_bdj",
    "manual_pucv_herbarium_gbif",
    "manual_luebert_chile_diversity",
    "manual_arroyo_high_andes_chile",
    "manual_subantarctic_chile_potential"
  ),
  intake_type = c(
    "doi",
    "doi",
    "gbif_occurrence_dataset",
    "doi",
    "doi",
    "doi",
    "doi",
    "doi",
    "dryad_dataset",
    "doi",
    "doi",
    "doi",
    "doi",
    "doi",
    "gbif_occurrence_dataset",
    "gbif_occurrence_dataset",
    "gbif_occurrence_dataset",
    "doi",
    "dryad_dataset",
    "doi",
    "zenodo_dataset",
    "doi",
    "doi",
    "doi",
    "doi",
    "gbif_occurrence_dataset",
    "doi",
    "doi",
    "url"
  ),
  display_name = c(
    "RAINBIO: mega-database tropical African vascular plants",
    "ECAT: endemic and sub-endemic trees of Central Africa",
    "Gabon Vascular Plant Occurrences — Herbier National du Gabon",
    "Flora of Russia on iNaturalist citizen-science dataset",
    "Diversity and distribution of Oxytropis DC. in Asian Russia",
    "Virtual Herbarium ALTB — Altai Mountain Country vascular plants",
    "Fleroff goes digital — georeferenced historical vascular plant records",
    "First checklist of alien vascular plants of Kyrgyzstan",
    "Taxonomic corrections and new records for vascular plants of Kyrgyzstan — Dryad dataset",
    "Flora of Mongolia — iNaturalist plant observations",
    "Vouchered and georeferenced checklist of endemic vascular plants of the Lesser Sunda Islands",
    "Checklist of vascular flora of the Sunda-Sahul Convergence Zone",
    "Joyce et al. 2020 supplementary checklist dataset — Sunda-Sahul",
    "Updated checklist of vascular plants of Myanmar",
    "Flora of Sumatra — vascular plant collection ANDA Herbarium (selected families)",
    "Flora Sumatra — digitizing ANDA Herbarium specimens Part 2",
    "Flora of Sumatra — Batang Toru Forest ANDA Herbarium specimens",
    "Pacific Introduced Flora — PacIFlora island plant distributions",
    "Pacific Introduced Flora — PacIFlora Dryad dataset",
    "Southern Islands Vascular Flora — Guerrero et al. 2025",
    "SIVFLORA — Southern Islands Vascular Flora database (Zenodo)",
    "Amazon plant diversity — taxonomically verified species list",
    "Colombia bioregions as a source of useful plants",
    "Preserved specimen occurrences of Theobroma and Herrania",
    "Herbarium collection of Pontificia Universidad Catolica de Valparaiso (PUCV) Chile",
    "Vascular flora from PUCV Herbarium — GBIF occurrence dataset",
    "Geographic patterns of vascular plant diversity and endemism in Chile",
    "Vascular plant composition along elevation gradients in High Andes of Central Chile",
    "Potential vascular plant diversity in sub-Antarctic regions of Aysen and Magallanes"
  ),
  source_group = c(
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "gbif_occurrence_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "dryad_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "gbif_occurrence_dataset",
    "gbif_occurrence_dataset",
    "gbif_occurrence_dataset",
    "published_paper_with_dataset",
    "dryad_dataset",
    "published_paper_with_dataset",
    "zenodo_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "gbif_occurrence_dataset",
    "published_paper_with_dataset",
    "published_paper_with_dataset",
    "gbif_occurrence_dataset"
  ),
  supplied_filename_or_url = c(
    "https://doi.org/10.3897/phytokeys.74.9723",
    "https://doi.org/10.3897/phytokeys.206.77379",
    "https://www.gbif.org/dataset/10.15468/apz3nj",
    "https://doi.org/10.3897/BDJ.8.e59249",
    "https://doi.org/10.3897/BDJ.10.e78666",
    "https://doi.org/10.3897/BDJ.9.e67616",
    "https://doi.org/10.3897/BDJ.9.e75299",
    "https://doi.org/10.3897/BDJ.9.e75590",
    "https://doi.org/10.5061/dryad.x3ffbg7wt",
    "https://doi.org/10.1002/ppp3.70054",
    "https://doi.org/10.3897/phytokeys.273.184780",
    "https://doi.org/10.3897/BDJ.8.e51094",
    "https://doi.org/10.3897/BDJ.8.e51094.suppl1",
    "https://doi.org/10.3897/phytokeys.261.154986",
    "https://www.gbif.org/dataset/10.15468/sncpxn",
    "https://www.gbif.org/dataset/10.15468/55evew",
    "https://www.gbif.org/dataset/10.15468/ue7xyn",
    "https://doi.org/10.3897/BDJ.9.e67318",
    "https://doi.org/10.5061/dryad.qfttdz0hd",
    "https://doi.org/10.1038/s41597-025-04702-9",
    "https://doi.org/10.5281/zenodo.13997147",
    "https://doi.org/10.1073/pnas.1706756114",
    "https://doi.org/10.1371/journal.pone.0256457",
    "https://doi.org/10.3897/BDJ.11.e99646",
    "https://doi.org/10.3897/BDJ.10.e90591",
    "https://www.gbif.org/dataset/10.15468/k485f5",
    "https://doi.org/10.3390/d14040271",
    "https://doi.org/10.1016/j.dib.2024.111128",
    "https://www.gbif.org/dataset/"
  ),
  canonical_url_or_doi = c(
    "10.3897/phytokeys.74.9723",
    "10.3897/phytokeys.206.77379",
    "10.15468/apz3nj",
    "10.3897/BDJ.8.e59249",
    "10.3897/BDJ.10.e78666",
    "10.3897/BDJ.9.e67616",
    "10.3897/BDJ.9.e75299",
    "10.3897/BDJ.9.e75590",
    "10.5061/dryad.x3ffbg7wt",
    "10.1002/ppp3.70054",
    "10.3897/phytokeys.273.184780",
    "10.3897/BDJ.8.e51094",
    "10.3897/BDJ.8.e51094.suppl1",
    "10.3897/phytokeys.261.154986",
    "10.15468/sncpxn",
    "10.15468/55evew",
    "10.15468/ue7xyn",
    "10.3897/BDJ.9.e67318",
    "10.5061/dryad.qfttdz0hd",
    "10.1038/s41597-025-04702-9",
    "10.5281/zenodo.13997147",
    "10.1073/pnas.1706756114",
    "10.1371/journal.pone.0256457",
    "10.3897/BDJ.11.e99646",
    "10.3897/BDJ.10.e90591",
    "10.15468/k485f5",
    "10.3390/d14040271",
    "10.1016/j.dib.2024.111128",
    NA_character_
  ),
  related_publication = c(
    "Dauby et al. 2016. RAINBIO: a mega-database of tropical African vascular plants distributions. PhytoKeys 74. doi:10.3897/phytokeys.74.9723",
    "Tack et al. 2022. The ECAT dataset: expert-validated distribution data of endemic and sub-endemic trees of Central Africa. PhytoKeys 206. doi:10.3897/phytokeys.206.77379",
    "Herbier National du Gabon GBIF/IPT dataset. Gabon vascular plant herbarium occurrence/specimen data.",
    "Seregin et al. 2020. 'Flora of Russia' on iNaturalist: a dataset. Biodiversity Data Journal 8:e59249. doi:10.3897/BDJ.8.e59249",
    "Sandanov et al. 2022. Diversity and distribution of Oxytropis DC. species in Asian Russia. Biodiversity Data Journal 10:e78666. doi:10.3897/BDJ.10.e78666",
    "Vaganov et al. 2021. Virtual Herbarium ALTB: collection of vascular plants of the Altai Mountain Country. Biodiversity Data Journal 9:e67616. doi:10.3897/BDJ.9.e67616",
    "Seregin & Basov 2021. Fleroff goes digital: georeferenced records from 'Flora des Gouvernements Wladimir'. Biodiversity Data Journal 9:e75299. doi:10.3897/BDJ.9.e75299",
    "Sennikov & Lazkov 2021. The first checklist of alien vascular plants of Kyrgyzstan, contribution 1. Biodiversity Data Journal 9:e75590. doi:10.3897/BDJ.9.e75590",
    "Sennikov & Lazkov 2025. Taxonomic corrections and new records for vascular plants of Kyrgyzstan. Dryad dataset doi:10.5061/dryad.x3ffbg7wt. Darwin Core format.",
    "Baasanmunkh et al. 2025. iNaturalist projects represent a valuable resource for aggregating plant observations: Flora of Mongolia. Plants People Planet. doi:10.1002/ppp3.70054",
    "Jennings et al. 2026. A vouchered and georeferenced checklist of endemic vascular plants of the Lesser Sunda Islands. PhytoKeys 273. doi:10.3897/phytokeys.273.184780",
    "Joyce et al. 2020. Checklist of the vascular flora of the Sunda-Sahul Convergence Zone. Biodiversity Data Journal 8:e51094. doi:10.3897/BDJ.8.e51094",
    "Joyce et al. 2020. Supplementary dataset for Sunda-Sahul Convergence Zone vascular flora checklist. doi:10.3897/BDJ.8.e51094.suppl1",
    "Aung et al. 2025. An updated checklist of vascular plants of Myanmar. PhytoKeys 261. doi:10.3897/phytokeys.261.154986",
    "Flora of Sumatra: vascular plant collection of selected families deposited at Herbarium of Andalas University (ANDA). GBIF occurrence dataset.",
    "Flora Sumatra: digitizing and databasing specimens of the Sumatran Flora, ANDA Part 2. GBIF occurrence dataset.",
    "Flora of Sumatra: vascular plant collection from Batang Toru Forest deposited in ANDA Herbarium. GBIF occurrence dataset.",
    "Wohlwend et al. 2021. Pacific Introduced Flora / PacIFlora. Biodiversity Data Journal 9:e67318. doi:10.3897/BDJ.9.e67318",
    "Wohlwend et al. 2021. Data: Pacific Introduced Flora. Dryad dataset doi:10.5061/dryad.qfttdz0hd.",
    "Guerrero et al. 2025. Southern Islands Vascular Flora dataset. Scientific Data. doi:10.1038/s41597-025-04702-9",
    "SIVFLORA: Southern Islands Vascular Flora database. Zenodo dataset doi:10.5281/zenodo.13997147.",
    "Cardoso et al. 2017. Amazon plant diversity revealed by a taxonomically verified species list. PNAS 114. doi:10.1073/pnas.1706756114",
    "Bystriakova et al. 2021. Colombia's bioregions as a source of useful plants. PLoS ONE 16. doi:10.1371/journal.pone.0256457",
    "Colli-Silva et al. 2023. A taxonomic dataset of preserved specimen occurrences of Theobroma and Herrania. Biodiversity Data Journal 11:e99646. doi:10.3897/BDJ.11.e99646",
    "Cordero et al. 2022. Herbarium collection of the Pontificia Universidad Catolica de Valparaiso, Chile. Biodiversity Data Journal 10:e90591. doi:10.3897/BDJ.10.e90591",
    "Vascular flora from the PUCV Herbarium. GBIF occurrence dataset. doi:10.15468/k485f5",
    "Luebert et al. 2022. Geographic patterns of vascular plant diversity and endemism using different taxonomic and spatial units. Diversity 14(4):271. doi:10.3390/d14040271",
    "Arroyo et al. 2024. Data on vascular plant species composition along two elevation gradients in the high Andes of central Chile. Data in Brief. doi:10.1016/j.dib.2024.111128",
    "Sub-Antarctic Chile vascular flora. GBIF/IPT dataset. 4476 occurrence records most georeferenced. No stable DOI confirmed at time of intake."
  ),
  provenance_status = "user-supplied",
  harvest_status = "pending_review",
  already_present_in_pipeline = "no",
  existing_match_notes = "",
  next_action = c(
    "Fetch RAINBIO dataset from associated Zenodo/Dryad deposit or PhytoKeys supplementary; map georeferenced vascular plant occurrences to Darwin Core; ingest to BIEN pipeline.",
    "Download ECAT dataset from PhytoKeys supplementary or associated data repository; map specimen occurrences (DRC/Rwanda/Burundi) to Darwin Core and BIEN schema.",
    "Download occurrence records via GBIF API using dataset DOI 10.15468/apz3nj; map to Darwin Core and BIEN schema.",
    "Download dataset from BDJ supplementary or linked GBIF deposit; map large citizen-science vascular plant observations for Russia to Darwin Core and BIEN.",
    "Download 5172 distribution records from BDJ supplementary; taxon-specific but well-georeferenced. Map to Darwin Core and BIEN.",
    "Fetch herbarium dataset from BDJ dataset link; map Altai Mountain Country vascular plant data to Darwin Core and BIEN.",
    "Download georeferenced historical vascular plant records from BDJ dataset page; map to Darwin Core and BIEN.",
    "Obtain checklist and associated occurrence records from BDJ; map to Darwin Core and BIEN.",
    "Download from Dryad (already in Darwin Core format); run through compile pipeline and map to BIEN schema. High priority — DwC-ready.",
    "Identify associated iNaturalist project or dataset download link from paper; map recent plant observations for Mongolia to Darwin Core and BIEN.",
    "Fetch dataset from PhytoKeys supplementary; map vouchered/georeferenced endemic plant data for Lesser Sunda Islands to Darwin Core and BIEN.",
    "Determine if point occurrence data accompanies this checklist or if it serves best as regional taxonomic backbone; map available data to Darwin Core.",
    "Download supplementary dataset directly; parse tabular data for occurrence records with coordinates. Map to Darwin Core and BIEN.",
    "Primarily a checklist — determine if georeferenced point occurrence records accompany the publication; use as taxonomic backbone if no coordinates.",
    "Download via GBIF API using dataset DOI 10.15468/sncpxn; map herbarium specimen occurrences to Darwin Core and BIEN.",
    "Download via GBIF API using dataset DOI 10.15468/55evew; map to Darwin Core and BIEN.",
    "Download via GBIF API using dataset DOI 10.15468/ue7xyn; map to Darwin Core and BIEN.",
    "Download PacIFlora data from BDJ or associated Dryad deposit; note that data may be island-level distributions rather than point coordinates. Map available occurrence data to Darwin Core and BIEN.",
    "Download from Dryad; inspect tabular files for georeferenced occurrence records; map to Darwin Core and BIEN.",
    "Download dataset from Zenodo (see SIVFLORA Zenodo DOI 10.5281/zenodo.13997147); map to Darwin Core and BIEN.",
    "Download from Zenodo and run through zenodo compile pipeline; map to Darwin Core and BIEN.",
    "Primarily a voucher-based seed-plant checklist — determine if georeferenced occurrence records accompany the paper or exist in a GBIF deposit; use as Amazon taxonomic backbone if no coordinates.",
    "Fetch georeferenced vascular plant collection localities from paper supplementary or associated data deposit; includes Amazon bioregion Colombia. Map to Darwin Core and BIEN.",
    "Download specimen occurrence dataset from BDJ; taxon-specific (Theobroma/Herrania only) but well-georeferenced. Map to Darwin Core and BIEN.",
    "Download 10721 Chilean vascular plant specimens from BDJ dataset or associated GBIF deposit; map to Darwin Core and BIEN.",
    "Download via GBIF API using dataset DOI 10.15468/k485f5; map to Darwin Core and BIEN.",
    "Identify and download the 181796 unique occurrence records used in this analysis from associated data repository or GBIF; map to Darwin Core and BIEN.",
    "Download plot-level georeferenced vascular plant data from Data in Brief repository or linked data deposit; map to Darwin Core and BIEN.",
    "Locate stable GBIF dataset DOI for sub-Antarctic Aysen and Magallanes Chile dataset; then download and map to Darwin Core and BIEN. 4476 georeferenced records expected."
  ),
  notes = c(
    "Data fit: Excellent. Georeferenced vascular plant records across tropical Africa. Region: Central Africa.",
    "Data fit: Excellent. Expert-validated specimen occurrences for DRC/Rwanda/Burundi. Region: Central Africa.",
    "Data fit: Excellent. Herbarium occurrence/specimen data for Gabon. Region: Central Africa/Gabon.",
    "Data fit: Excellent. Very large citizen-science vascular plant observation dataset. Region: Russia.",
    "Data fit: Excellent but taxon-specific (Oxytropis only). 5172 distribution records. Region: Russia/Asian Russia.",
    "Data fit: Excellent. Herbarium data for Altai Mountain Country including Russia/Kazakhstan/Mongolia/China. Region: Russia/Central Asia/Altai.",
    "Data fit: Good. Historical georeferenced vascular plant records for Russia. Region: Russia.",
    "Data fit: Good. Checklist plus occurrence records for Kyrgyzstan. Region: Central Asia/Kyrgyzstan.",
    "Data fit: Good. Dryad dataset in Darwin Core format. Region: Central Asia/Kyrgyzstan.",
    "Data fit: Excellent for recent observation data. Region: Central Asia/Mongolia.",
    "Data fit: Excellent. Vouchered georeferenced endemic plant checklist. Region: Southeast Asia/Lesser Sunda Islands.",
    "Data fit: Strong checklist; best used as regional taxonomic backbone. Region: Southeast Asia/Sunda-Sahul.",
    "Data fit: Dataset DOI — download and inspect for occurrence coordinates. Region: Southeast Asia/Sunda-Sahul.",
    "Data fit: Checklist not primarily point occurrence data; useful as taxonomic backbone. Region: Southeast Asia/Myanmar.",
    "Data fit: Excellent. GBIF herbarium occurrence/specimen dataset. Region: Southeast Asia/Sumatra.",
    "Data fit: Excellent. GBIF herbarium occurrence/specimen dataset. Region: Southeast Asia/Sumatra.",
    "Data fit: Excellent. GBIF herbarium occurrence/specimen dataset. Region: Southeast Asia/Sumatra.",
    "Data fit: Good for island-level naturalized plant distributions; not necessarily georeferenced point coordinates. Region: Pacific Islands.",
    "Data fit: Dataset DOI for PacIFlora. Region: Pacific Islands.",
    "Data fit: Excellent. Southern Ocean island plant database. Region: Southern Ocean/Pacific-adjacent islands.",
    "Data fit: Excellent. Dataset DOI for SIVFLORA. Region: Southern Ocean/Pacific-adjacent islands.",
    "Data fit: Strong checklist based on vouchers; not primarily a point-coordinate occurrence dataset. Region: Amazon.",
    "Data fit: Good. Uses georeferenced vascular plant collection localities; includes Amazon bioregion. Region: Amazon/Colombia.",
    "Data fit: Good but taxon-specific (Theobroma/Herrania only). Includes Amazonian cacao relatives. Region: Brazil/Amazon-adjacent.",
    "Data fit: Excellent. 10721 specimens from Chilean vascular flora. Region: Chile.",
    "Data fit: Excellent. GBIF occurrence dataset. Region: Chile.",
    "Data fit: Excellent analytical paper using 181796 unique occurrence records for Chile. Region: Chile.",
    "Data fit: Excellent. Plot-level georeferenced vascular plant data along two elevation gradients. Region: Chile/High Andes.",
    "Data fit: Good. 4476 occurrence records mostly georeferenced. No stable DOI confirmed — requires DOI resolution first. Region: Chile/sub-Antarctic."
  )
)

# Filter to only truly new source_ids
new_rows <- new_rows[!source_id %in% existing$source_id]
cat("New rows to add:", nrow(new_rows), "\n")

combined <- rbindlist(list(existing, new_rows), fill = TRUE)
fwrite(combined, f)
cat("Written:", nrow(combined), "total rows to", f, "\n")
