## add_new_sources_2026_apr29.R
## Appends a second batch of plot/trait observation source candidates to manual_source_intake.csv
## Sources supplied by user via chat on 2026-04-29.

library(data.table)

proj_root <- "/Users/brianjenquist/VSCode/DryadPlantTraits"
f <- file.path(proj_root, "data", "manual_source_intake.csv")
existing <- fread(f)

new_rows <- data.table(
  source_id = c(
    "manual_arctic_vegetation_archive_ava",
    "manual_caff_flora_group_arctic",
    "manual_darkdivnet",
    "manual_rasgos_cl_chile_traits",
    "manual_tubives_turkish_plants",
    "manual_russian_arctic_vegetation_archive",
    "manual_amazon_tree_diversity_network_atdn",
    "manual_enquist_macrosystems_gentry_plots",
    "manual_canadian_forest_inventory",
    "manual_science_i_global_forest_biodiversity",
    "manual_syntreesys_cesab",
    "manual_dryflor_seasonally_dry_tropical_forest",
    "manual_asean_biodiversity_rbim",
    "manual_central_african_plot_network_cafriplot",
    "manual_givd_global_index_vegetation_databases",
    "manual_gloria_alpine_plant_network",
    "manual_herbase_amazon_herbs",
    "manual_red_argentina_parcelas_permanentes",
    "manual_inventario_nacional_bosques_nativos_argentina"
  ),
  intake_type = c(
    "url",
    "url",
    "url",
    "url",
    "url",
    "doi",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url",
    "url"
  ),
  display_name = c(
    "Arctic Vegetation Archive (AVA) — UAF Geobotany Center",
    "CAFF Flora Group — overview of national arctic plant databases",
    "DarkDivNet — global dark diversity plot network (presence/absence)",
    "Rasgos-CL — Chilean plant trait database (Dylan Craven)",
    "TUBIVES — Turkish plant database (coarse grid species lists)",
    "Russian Arctic Vegetation Archive — 2873 open-access geobotanical plots",
    "Amazon Tree Diversity Network (ATDN)",
    "Enquist Lab plot data — Forest Macrosystems and additional Gentry plots",
    "Canadian National Forest Inventory (NFI)",
    "Global Forest Biodiversity Initiative — Science-i platform",
    "SYNTREESYS — Latin American synthetic tree plot database (CESAB/FRB)",
    "DryFlor — Latin American Seasonally Dry Tropical Forest Floristic Network",
    "ASEAN Biodiversity Information Management — Regional Biodiversity Information Management",
    "Central African Plot Network (CAFRIPLOT) — 233 plots plus traits and herbarium specimens",
    "GIVD — Global Index of Vegetation Plot Databases (overview registry)",
    "GLORIA — Global Observation Research Initiative in Alpine Environments",
    "HERBase — Herbs of the Amazon flora database",
    "Red Argentina de Parcelas Permanentes de Bosques Nativos",
    "Inventario Nacional de Bosques Nativos — Argentina national forest monitoring"
  ),
  source_group = c(
    "vegetation_plot_database",
    "regional_database_overview",
    "vegetation_plot_database",
    "trait_database",
    "vegetation_plot_database",
    "published_paper_with_dataset",
    "vegetation_plot_database",
    "vegetation_plot_database",
    "national_forest_inventory",
    "vegetation_plot_database",
    "vegetation_plot_database",
    "vegetation_plot_database",
    "regional_database_overview",
    "vegetation_plot_database",
    "vegetation_plot_database_registry",
    "vegetation_plot_database",
    "vegetation_plot_database",
    "vegetation_plot_database",
    "national_forest_inventory"
  ),
  supplied_filename_or_url = c(
    "https://www.geobotany.uaf.edu/ava/",
    "https://www.caff.is/work/projects/cfg-caffs-flora-group/",
    "https://macroecology.ut.ee/en/darkdivnet/",
    "https://bibliotecadigital.infor.cl/handle/20.500.12220/32648",
    "https://nadidem.net/flora/www.tubives.com/indexf8ae.html?sayfa=300",
    "https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13724",
    "https://sites.google.com/naturalis.nl/amazon-tree-diversity-network/homepage",
    "https://www.forestmacrosystems.org/methods/",
    "https://nfi.nfis.org/en/",
    "https://science-i.org/",
    "https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/syntreesys/",
    "http://www.dryflor.info/",
    "https://bkmd.aseanbiodiversity.org/dashboard/rbim.php",
    "https://cafriplot.net/",
    "https://www.givd.info/faces/database_details.xhtml",
    "https://www.gloria.ac.at/network/general",
    "https://www.scielo.br/j/aa/a/9Tp47pFS4bMsjRT6LkPjcHQ/?lang=en",
    "https://www.researchgate.net/publication/362452924_Red_Argentina_de_Parcelas_Permanentes_de_Bosques_Nativos_para_promover_colaboraciones_cientificas_en_estudios_de_largo_plazo",
    "https://www.argentina.gob.ar/jefatura/turismo-y-ambiente/ambiente/recursos-naturales/sistema-nacional-de-monitoreo-de-bosques-8"
  ),
  canonical_url_or_doi = c(
    "https://www.geobotany.uaf.edu/ava/",
    "https://www.caff.is/work/projects/cfg-caffs-flora-group/",
    "https://macroecology.ut.ee/en/darkdivnet/",
    "https://bibliotecadigital.infor.cl/handle/20.500.12220/32648",
    "https://nadidem.net/flora/www.tubives.com/",
    "10.1111/geb.13724",
    "https://sites.google.com/naturalis.nl/amazon-tree-diversity-network/homepage",
    "https://www.forestmacrosystems.org/methods/",
    "https://nfi.nfis.org/en/",
    "https://science-i.org/",
    "https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/syntreesys/",
    "http://www.dryflor.info/",
    "https://bkmd.aseanbiodiversity.org/dashboard/rbim.php",
    "https://cafriplot.net/",
    "https://www.givd.info/",
    "https://www.gloria.ac.at/",
    "https://www.scielo.br/j/aa/a/9Tp47pFS4bMsjRT6LkPjcHQ/?lang=en",
    NA_character_,
    "https://www.argentina.gob.ar/jefatura/turismo-y-ambiente/ambiente/recursos-naturales/sistema-nacional-de-monitoreo-de-bosques-8"
  ),
  related_publication = c(
    "Walker et al. — Arctic Vegetation Archive (AVA) project. UAF Geobotany Center; ~31,000 plots target.",
    "Conservation of Arctic Flora and Fauna (CAFF) Flora Group — coordinating body for national arctic plant databases.",
    "Partel et al. — DarkDivNet: a global network estimating dark diversity from standardized vegetation plots (presence/absence 1/0).",
    "Craven D. and collaborators — Rasgos-CL Chilean plant trait database. Hosted at INFOR digital library handle 20.500.12220/32648.",
    "TUBIVES — Turkish Plants Data Service (taxonomic checklist with coarse-grid species lists).",
    "Walker et al. 2023. Russian Arctic Vegetation Archive: 2873 open-access geobotanical plots. Global Ecology and Biogeography. doi:10.1111/geb.13724",
    "ter Steege et al. — Amazon Tree Diversity Network (ATDN). Hosted by Naturalis Biodiversity Center.",
    "Enquist Lab — Forest Macrosystems network plus additional unpublished Gentry transect plots. https://www.forestmacrosystems.org/methods/",
    "Canadian National Forest Inventory (NFI) — federal/provincial standardized forest plot network.",
    "Global Forest Biodiversity Initiative (GFBI) — Science-i collaborative platform for forest plot data.",
    "SYNTREESYS — Synthetic tree plot database project, CESAB / Foundation pour la Recherche sur la Biodiversité (FRB).",
    "DryFlor — Latin American Seasonally Dry Tropical Forest Floristic Network. http://www.dryflor.info/",
    "ASEAN Centre for Biodiversity — Regional Biodiversity Information Management (RBIM) dashboard.",
    "CAFRIPLOT — Central African Plot Network. 233 forest plots plus associated trait measurements and herbarium specimens.",
    "Dengler et al. — GIVD: Global Index of Vegetation Plot Databases. Registry/overview table of global plot databases.",
    "GLORIA — Global Observation Research Initiative in Alpine Environments. Standardized alpine summit vegetation monitoring network.",
    "HERBase — Herbs of the Amazon database. SciELO Acta Amazonica reference.",
    "Red Argentina de Parcelas Permanentes de Bosques Nativos. ResearchGate publication 362452924.",
    "Sistema Nacional de Monitoreo de Bosques Nativos / Inventario Nacional de Bosques Nativos — Argentina Ministerio de Ambiente."
  ),
  provenance_status = "user-supplied",
  harvest_status = "pending_review",
  already_present_in_pipeline = "no",
  existing_match_notes = c(
    "Some AVA plots may already be in sPlot or other vegetation plot syntheses; verify deduplication before ingest.",
    "Coordinating overview only; individual national databases need to be enumerated separately.",
    "Likely overlaps with sPlot/EVA where contributing teams shared plots; verify deduplication.",
    "Trait dataset — fits trait-side of pipeline rather than occurrence; coordinate with existing Chile sources (PUCV, Luebert).",
    "May overlap with GBIF Turkish vascular plant occurrence datasets; verify deduplication.",
    "Likely deposited in Pangaea or similar repository as accompanying open dataset; locate dataset DOI before ingest. Possible overlap with sPlot.",
    "Likely overlaps with RAINFOR plot network and other Amazon tree plot syntheses; verify deduplication.",
    "Some Gentry transects already in BIEN; Macrosystems plots may not be. Coordinate directly with Enquist Lab.",
    "May already be partially represented via GBIF Canadian government datasets; verify and check NFI data sharing terms.",
    "Likely overlaps with sPlot/RAINFOR/ATDN contributing networks; verify deduplication.",
    "Likely overlaps with sPlot, ATDN, RAINFOR; verify deduplication.",
    "Likely overlaps with NeoTropTree and other Latin American floristic networks; verify deduplication.",
    "Aggregator dashboard; may contain only checklists rather than open occurrence records — verify what is downloadable.",
    "May overlap with RAINBIO and other Central African plot syntheses; verify deduplication.",
    "Registry of registries — use to enumerate additional databases not yet ingested rather than as a primary data source.",
    "Standardized alpine plot network; verify whether sPlot or EVA already incorporates GLORIA contributions.",
    "Specific to Amazonian herb taxa; coordinate with broader Amazon plot data.",
    "Argentina forest plot network; coordinate with Inventario Nacional de Bosques Nativos and SiPAN.",
    "Argentina national forest inventory; verify data sharing terms before ingest."
  ),
  next_action = c(
    "Contact AVA team and/or check geobotany.uaf.edu data portal for downloadable plot tables; map to Darwin Core Event/Occurrence and BIEN plot schema. ~31000 plots potential.",
    "Enumerate the national-level databases listed by CAFF Flora Group; create separate intake entries for each downloadable database.",
    "Identify DarkDivNet data release (likely paper-associated supplementary or repository deposit); ingest 1/0 presence-absence plots and map to BIEN plot schema.",
    "Download Rasgos-CL trait dataset from INFOR handle; map traits to BIEN trait schema with provenance.",
    "Crawl TUBIVES taxonomic backbone and any downloadable distribution data; assess whether grid-cell species lists can be mapped to BIEN occurrence schema.",
    "Locate dataset DOI from the Walker et al. 2023 GEB paper supplementary information; download 2873 plots and map to Darwin Core/BIEN plot schema.",
    "Coordinate with ATDN team (Hans ter Steege, Naturalis) to obtain plot-level data; map to BIEN plot schema. May overlap with RAINFOR.",
    "Coordinate within Enquist Lab to gather Macrosystems plot data and any additional Gentry transects not already in BIEN.",
    "Investigate NFI data sharing terms; download what is publicly available and map to BIEN plot schema.",
    "Register on Science-i platform; identify which contributed plot datasets are downloadable; coordinate with GFBI leadership for bulk data access.",
    "Contact CESAB SYNTREESYS coordinators to obtain synthetic tree plot database; map to BIEN plot schema.",
    "Crawl DryFlor portal for downloadable floristic data; map to BIEN occurrence/plot schema.",
    "Crawl ASEAN RBIM dashboard for downloadable checklist or occurrence data; assess whether anything beyond checklists is open.",
    "Coordinate with CAFRIPLOT consortium for plot, trait, and herbarium data; map to BIEN plot/trait/occurrence schemas.",
    "Use GIVD as a discovery registry — enumerate plot databases not already represented in BIEN/sPlot and create individual intake entries.",
    "Coordinate with GLORIA coordinators or check sPlot/EVA for already-incorporated GLORIA plots; map alpine summit plots to BIEN plot schema.",
    "Identify HERBase data portal beyond the SciELO paper; download and map to BIEN occurrence/plot schema.",
    "Contact Red Argentina de Parcelas Permanentes coordinators to obtain plot data; map to BIEN plot schema.",
    "Investigate Argentina Ministerio de Ambiente data sharing terms for the Inventario Nacional de Bosques Nativos; ingest publicly available data and map to BIEN plot schema."
  ),
  notes = c(
    "Data fit: Excellent for arctic plot data. ~31000 plots target. Region: Arctic.",
    "Data fit: Aggregator overview rather than direct dataset; useful for discovery. Region: Arctic.",
    "Data fit: Excellent for global standardized presence-absence vegetation plots. Region: Global (plot-level).",
    "Data fit: Trait database (not primarily occurrence); high value for Chilean trait coverage. Region: Chile.",
    "Data fit: Coarse grid species lists; useful as Turkey taxonomic backbone with coarse occurrence data. Region: Turkey.",
    "Data fit: Excellent. 2873 open-access geobotanical plots. Region: Russian Arctic.",
    "Data fit: Excellent for Amazon tree plot data. Region: Amazon.",
    "Data fit: Excellent — directly aligned with Enquist Lab BIEN curation. Region: Americas (NEON/Macrosystems and Gentry-style transects).",
    "Data fit: Excellent national forest inventory if data sharing permits. Region: Canada.",
    "Data fit: Potentially excellent global forest plot aggregator; access depends on platform terms. Region: Global.",
    "Data fit: Excellent Latin American tree plot synthesis. Region: Latin America.",
    "Data fit: Excellent for seasonally dry tropical forest floristics. Region: Latin America (SDTF).",
    "Data fit: Likely checklist-only; verify downloadable open data. Region: Southeast Asia (ASEAN member states).",
    "Data fit: Excellent. 233 plots plus traits and herbarium specimens. Region: Central Africa.",
    "Data fit: Registry of plot databases for source discovery rather than direct data. Region: Global.",
    "Data fit: Standardized alpine plot data. Region: Global alpine.",
    "Data fit: Amazon herb-specific plot data. Region: Amazon.",
    "Data fit: Argentine forest permanent plot network. Region: Argentina.",
    "Data fit: Argentine national forest inventory. Region: Argentina."
  )
)

new_rows <- new_rows[!source_id %in% existing$source_id]
cat("New rows to add:", nrow(new_rows), "\n")

combined <- rbindlist(list(existing, new_rows), fill = TRUE)
fwrite(combined, f)
cat("Written:", nrow(combined), "total rows to", f, "\n")
